### ISSUE TITLE
聊天频道框体不能移动，不是左下角的那个

### ISSUE THREAD

**Issue by dylumian** [fang2hou/ElvUI_WindTools#101]
不是左下角的那个聊天框体，是聊天频道 esc界面 按键设置 界面面板里的那个聊天频道
![image](https://user-images.githubusercontent.com/37278466/89241890-b749d700-d632-11ea-8a11-8c35e7802f5a.png)

**Comment by fang2hou** [comment]
2.0 已经修复, 前夕更新.
