### ISSUE TITLE
希望聊天条增加一些功能

### ISSUE THREAD

**Issue by dylumian** [fang2hou/ElvUI_WindTools#102]
希望聊天条可以添加altchat的一些功能
比如就位确认/左键倒计时右键取消倒计时
属性通报,还有短频道名,例如大脚世界频道->世
(都可以单独选择是否加入聊天条)
感谢作者大大

**Comment by fang2hou** [comment]
除了属性通报, 其他功能新版本都有了.
就位确认, 倒计时放在了团队标记条中

**Comment by fang2hou** [comment]
属性通报等前夕之后再斟酌更新到新的鼠标右键增强菜单中.
