### ISSUE TITLE
Game Bar Hide 

### ISSUE THREAD

**Issue by Fizgig1973** [fang2hou/ElvUI_WindTools#103]
Would it be possible to add an option to have the Game Bar show only on mouse over?

I love the addon, but only want the game bar to show when needed. 

Thank you so much for your work!

**Comment by fang2hou** [comment]
Sure, many users ask the same question like these, I'll add an option in next version.

**Comment by Fizgig1973** [comment]
Thank you so much =)

**Comment by fang2hou** [comment]
the new version 2.01-alpha-4 has added the option, the issue will be closed.
