### ISSUE TITLE
WA美化导致部分贴图显示异常

### ISSUE THREAD

**Issue by asdf12303116** [fang2hou/ElvUI_WindTools#104]
如题，这WA可确定触发

https://wago.io/Afenar_Druid

触发问题后如图
![开启](https://user-images.githubusercontent.com/14955115/96141938-1631a380-0f34-11eb-9b43-d119c97eaf32.PNG)
![未开启](https://user-images.githubusercontent.com/14955115/96141950-192c9400-0f34-11eb-8e97-25561a3e47f2.PNG)

**Comment by fang2hou** [comment]
有关闭美化试过么?

**Comment by asdf12303116** [comment]
两张图就是，开启后能量条 深灰色，关闭之后 显示为正常的亮白色。第一张图是开启美化后，第二张是关闭后。
截图之前AddOnSkins已经禁用

**Comment by fang2hou** [comment]
嗯, 我会排查一下的.

**Comment by asdf12303116** [comment]
刚上beta试了下，windtools-2.0-beta11,WA版本和正式服一致，同样可以触发相同的问题

**Comment by fang2hou** [comment]
其实大概知道怎么回事了, 因为他自己做了美化, 我再美化就覆盖掉了.
