### ISSUE TITLE
Welcome screen

### ISSUE THREAD

**Issue by Gennoken** [fang2hou/ElvUI_WindTools#110]
Using v 2.01-b8
The welcome screen keeps popping out after every loading screen (ex: changing zone)
also, when it pops out, i can't move my character with keyboard unless i dismiss the screen
very annoying :(

**Comment by fang2hou** [comment]
my miss, it will be fixed.

**Comment by Gennoken** [comment]
Hey, just to let you know, what i stated above has been fixed, but i noticed something else, if the changelog screen pops after an update you must click open changelog, if you click cancel it disappears but return after any loading/reload UI
@fang2hou

**Comment by fang2hou** [comment]
You need to read the changelog once at least, I do not show the changelog directly because sometimes players may in combat.
The point is that I dont want to get some report about the problems I already fixed before or sometimes the options moved.

**Comment by Gennoken** [comment]
i get your point and you are right, but also forcing people to read the changelog is not good either, that's why there is a "cancel" button anyway.

**Comment by fang2hou** [comment]
I know nobody likes been forced to do something.
For now, every update changes a lot, maybe after several versions, I will not force the user to read it.
