### ISSUE TITLE
Missing Heart Essence

### ISSUE THREAD

**Issue by JWalters-DravenIT** [fang2hou/ElvUI_WindTools#111]
Heart Essence
169774
Progression Sprocket

Other than that, thank you for the wonderful addon.

**Comment by fang2hou** [comment]
which module do you want to add the spell?
actually I did not play 8.2&8.3 so I dont know this contents.

**Comment by JWalters-DravenIT** [comment]
> which module do you want to add the spell?
> actually I did not play 8.2&8.3 so I dont know this contents.

Sorry, nevermind about the Heart Essence.  Wrong addon.

But still wonderful addon.
