### ISSUE TITLE
[Request] Game Bar

### ISSUE THREAD

**Issue by Gennoken** [fang2hou/ElvUI_WindTools#115]
Hey, can you :
1. Add the ability to Game Bar panels to detect LDB Brokers so we can add custom stuff or launch addons from it

2. If you do the above, then adding the ability to add custom panels to the Game Bar and move them around would be great and helps customizing stuff better.

Thx

**Comment by fang2hou** [comment]
Actually it is impossible for now, there are 2 reasons:
1. If add the support of creating bars, I need to rewrite all bar generation logic, database and more.
2. LDB broker button do not have a nice styled icon, it is hard to allow them display in the bar.

As instead,
1. Adding support for creating button with customization is in plan.
2. Unlocking the left panel, middle panel and right panel will be allowed in the next stable version.

**Comment by Gennoken** [comment]
Nice and keep up the good work
