### ISSUE TITLE
Gamebar error

### ISSUE THREAD

**Issue by Pharou80** [fang2hou/ElvUI_WindTools#116]
1x ...faceElvUI_WindTools\Modules\Misc\GameBar.lua:116: attempt to concatenate local 'name' (a nil value)
[string "@ElvUI_WindTools\Modules\Misc\GameBar.lua"]:116: in function <...faceElvUI_WindTools\Modules\Misc\GameBar.lua:95>
[string "@ElvUI_WindTools\Modules\Misc\GameBar.lua"]:299: in function `tooltips'
[string "@ElvUI_WindTools\Modules\Misc\GameBar.lua"]:797: in function `?'
[string "@ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0-8.lua"]:90: in function <...Ons\ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:87>

Locals:
itemID = 180290
prefix = "|TTUTORIALFRAME\UI-TUTORIAL-FRAME:13:11:0:-1:512:512:12:66:230:307|t "
name = nil
texture = 3489827
icon = "|T3489827:16:18:0:0:64:64:4:60:7:57:255:255:255|t"
startTime = 0
duration = 0
cooldownTime = -330173.575000
canUse = true
cooldownTimeString = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = DataTextTooltip {
 BottomLeftCorner = <unnamed> {
 }
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
 textLeft1Font = "GameTooltipHeaderText"
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:443
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
 RightEdge = <unnamed> {
 }
 template = "Transparent"
 textRight2Font = "GameTooltipText"
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:347
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:382
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:335
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:462
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:400
 comparing = false
 windStyle = true
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:319
 shadow = <unnamed> {
 }
 0 = <userdata>
 PixelSnapDisabled = true
 BottomRightCorner = <unnamed> {
 }
 TextLeft1 = DataTextTooltipTextLeft1 {
 }
 customBackdropAlpha = 0.800000
 BottomEdge = <unnamed> {
 }
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:235
 BottomOverlay = <unnamed> {
 }
 backdropInfo = <table> {
 }
 Center = <unnamed> {
 }
 textRight1Font = "GameTooltipHeaderText"
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:331
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
 updateTooltip = 0.200000
 textLeft2Font = "GameTooltipText"
 TopEdge = <unnamed> {
 }
 TextRight2 = DataTextTooltipTextRight2 {
 }
 TextLeft2 = DataTextTooltipTextLeft2 {
 }
 TopRightCorner = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 needsReset = true
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:299
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:452
 LeftEdge = <unnamed> {
 }
 TextRight1 = DataTextTooltipTextRight1 {
 }
}
(*temporary) = "|TTUTORIALFRAME\UI-TUTORIAL-FRAME:13:11:0:-1:512:512:12:66:230:307|t "
(*temporary) = "|T3489827:16:18:0:0:64:64:4:60:7:57:255:255:255|t"
(*temporary) = " "
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'name' (a nil value)"
type = <function> defined =[C]:-1
tonumber = <function> defined =[C]:-1
HeartstonesTable = <table> {
 172179 = "Eternal Traveler's Hearthstone"
 163045 = "Headless Horseman's Hearthstone"
 166747 = "Brewfest Reveler's Hearthstone"
 141605 = "Flight Master's Whistle"
 168907 = "Holographic Digitalization Hearthstone"
 165670 = "Peddlefeet's Lovely Hearthstone"
 165669 = "Lunar Elder's Hearthstone"
 165802 = "Noble Gardener's Hearthstone"
 162973 = "Greatfather Winter's Hearthstone"
 6948 = "Hearthstone"
 166746 = "Fire Eater's Hearthstone"
}
tostring = <function> defined =[C]:-1
GetItemIcon = <function> defined =[C]:-1
format = <function> defined =[C]:-1
IconString = "|T%s:16:18:0:0:64:64:4:60:7:57"
GetItemCooldown = <function> defined =[C]:-1
GetTime = <function> defined =[C]:-1
floor = <function> defined =[C]:-1
mod = <function> defined =[C]:-1
DT = <table> {
 OnLeave = <function> defined @ElvUI\Modules\DataTexts\DataTexts.lua:135
 SingleHyperMode = <function> defined @ElvUI\Modules\DataTexts\DataTexts.lua:78
 PanelSizeChanged = <function> defined @ElvUI\Modules\DataTexts\DataTexts.lua:557
 HyperDT = <function> defined @ElvUI\Modules\DataTexts\DataTexts.lua:636
 EnableModule = <function> defined @ElvUI\Libraries\Ace3\A

**Comment by fang2hou** [comment]
Already fixed in alpha version.
Btw, the problem occured because the item with id 180290 is a new hearthstone add in 9.0, but in prepatch, you cannot access to this item info. So when you set the hearthstone to it (it will display a text in nothing because GetItemInfo() is failed), it will broken.
