### ISSUE TITLE
Context menu conflicts with the Raider.io addon

### ISSUE THREAD

**Issue by Xyxeii** [fang2hou/ElvUI_WindTools#119]
[https://i.imgur.com/e4BABlL.png](url)
[https://i.imgur.com/QQFJSsx.png](url)

The Raider.io addon has a get url on right click and it's sharing the same space as the context menu created by windtools. While this issue can just as easily be reported to raider.io, I figured I'd let you know here

**Comment by fang2hou** [comment]
Work on it!

**Comment by fang2hou** [comment]
Fix in 389f394, it will be first added in 2.03-beta-4.
