### ISSUE TITLE
[Feature Request] Quest Turn In Slash Command

### ISSUE THREAD

**Issue by Xyxeii** [fang2hou/ElvUI_WindTools#120]
Love the auto turn-in feature and the ignored npcs, but having a more convenient way to enable and disable the turn-in would be nice. Similar to the addon Turn In that uses /ti on, /ti off. Something along the lines of /wti on, /wti off would be a nice thing to have. Possibly even an additional slash command to add a target to the ignored list rather then doing it through the addon panel.

**Comment by fang2hou** [comment]
Added in 7d96fa1053a2eca27cd3f54edd0c33118b90c882

**Comment by fang2hou** [comment]
btw, the new command support:
`/wti [on|1|enable|true]`
`/wti [off|0|disable|false]`
`/wti [add|addtarget|add target|ignore]`

`/windturnin` and `/windquestturnin` are the aliases of `/wti`
