### ISSUE TITLE
加入SL的商人界面增强

### ISSUE THREAD

**Issue by WeijieH** [fang2hou/ElvUI_WindTools#125]
作者你好，我一直都是SL和WT混用的。自从新版WT推出后SL方面的功能我已经越用越少，唯一不能割舍的就是商人界面增强。
![vaqOCLr1EI](https://user-images.githubusercontent.com/16510655/97722683-4aaf6e80-1aa1-11eb-9905-fcce72954e0a.png)

希望WT可以同样整合这个实用的小功能，这样我就能彻底抛弃SL了。

**Comment by fang2hou** [comment]
嗯, 有空做一做

**Comment by Sooongz** [comment]
同样需要商人界面的增强

**Comment by fang2hou** [comment]
增加了 ce8754da0efe08de25626fa0531bce40666fa3ea
