### ISSUE TITLE
2.07 冒险手册无法开启与显示

### ISSUE THREAD

**Issue by jyuny1** [fang2hou/ElvUI_WindTools#127]
按了 shift+j 仍然无法打开。但 unload windtool 后在 ElvUI 可以正常显示。请问如何解决？

**Comment by fang2hou** [comment]
清除移动窗体记忆.
如果有同时安装别的移动窗体插件, 或者增强, 请关掉这个功能.

**Comment by jyuny1** [comment]
我没安装其他移动窗体的增强插件，想问下怎么清除移动窗体记忆

**Comment by fang2hou** [comment]
其他 - 移动框体, 如果经常出现问题, 建议直接关掉位置记忆

**Comment by fang2hou** [comment]
目前并不知道什么原因导致的, 我自己一次都没有复现过.

**Comment by jyuny1** [comment]
好的，到时试试看，非常感谢回答。windtool 非常好用

**Comment by fang2hou** [comment]
还有问题再reopen吧.
