### ISSUE TITLE
[Bug] 字体显示异常

### ISSUE THREAD

**Issue by daleqq** [fang2hou/ElvUI_WindTools#128]
**描述问题**
开启elvui同wind tools后在神器选择界面跟奥格公告板，字体无法看清

**错误复现**
错误复现步骤:
1. wind tools使用默认选项
2. 新号到 '神器选择界面' 或者 '公告板‘

**预期功能**
字体清晰

**截图**
只开启elvui时:
![image](https://user-images.githubusercontent.com/1555563/98430950-5546b500-20ec-11eb-8581-674fc5816f5b.png)
开启elvui跟windtool时
![image](https://user-images.githubusercontent.com/1555563/98430954-5f68b380-20ec-11eb-947a-6b3e4a2fab22.png)

**插件信息 (请填写基本信息, 你可以在 [信息] 中找到):**
 - 插件版本: 2.07
 - ElvUI 版本: 12.08
 - 游戏版本: 9.0.1 (36492)

**Comment by fang2hou** [comment]
9641a6c
