### ISSUE TITLE
[Skin Issue] There are some small issues with the WeakAuras Options skinning

### ISSUE THREAD

**Issue by Xyxeii** [fang2hou/ElvUI_WindTools#131]
These are a list of small skinning issues with the Weak Auras Options skinning. I believe some of these might be the fault of WeakAuras and their strata choices but some can be solved here. While not a pressing issue and I urge you to put this at the back of your TODO, I hope they can be addressed at some point. 

### Search Bar Isn't Skinned
[https://i.imgur.com/g2xF7Cf.png](https://i.imgur.com/g2xF7Cf.png)

### Add Aura to Group Button isn't Skinned (It's actually missing)
[https://i.imgur.com/YPrvce9.png](https://i.imgur.com/YPrvce9.png)

### Move Aura Up and Down Icon Not Skinned or Missing on Most Auras
This one is interesting because (as the screenshot shows) some icons are there and some are not. This issue can occur in aura's of the same group. It's much more common to find auras that have this icon missing. 

[https://i.imgur.com/cgUefIP.png](https://i.imgur.com/cgUefIP.png)

### Some Clipping in the Bottom Right
[https://i.imgur.com/1RgmuBn.png](https://i.imgur.com/1RgmuBn.png)

### Strata and Clipping Issue with the Top Right Buttons
[https://i.imgur.com/97RNMG5.png](https://i.imgur.com/97RNMG5.png)

**Comment by fang2hou** [comment]
please update to the latest beta version and test again

**Comment by fang2hou** [comment]
some parts are very hard to handle with, like the button that put the aura into a group, the mover button of each aura, etc.
btw WeakAuras seems dont like other addons reskin their addon, they always try to avoid the access from other addon.
the weakauras skin is created in a tricky way, maybe someday it cannot work anymore.

**Comment by Xyxeii** [comment]
Everything looks great on the latest dev version. Awesome job. Yea I know thing's are a little weird with skinning certain addons but you definitely pulled this one off. Thanks!

**Comment by Xyxeii** [comment]
Reopening this because as someone pointed out on Curse, the load times for WeakAuras options has significantly gone up. With some very minor testing, it seems to be related to the `S:AddCallbackForAceGUIWidget("WeakAurasDisplayButton")`. I'm assuming this is firing each time the buttons are being skinned. Commenting this out in the code seems to address the load times with no effect on skinning. I'm sure there's more to it, but hopefully that helps.

**Comment by fang2hou** [comment]
The logic of skinning button is catch the button frame when it initialized by weakaura, and check it every time on opening option .
the reason to do this is that weakaura add additional textures after the initialization, and actually there is no index to recognize which should be cleared. The current algorithm is loop to get each path of texture and clear the specific texture like borders.
making weakauras options skin is really a hard work than others.

**Comment by fang2hou** [comment]
I will stiil look forward to a better solution of skinning buttons.

**Comment by fang2hou** [comment]
if you have time, please update to 2.10-alpha-2 and test again, I have found a new solution on it.

**Comment by Xyxeii** [comment]
The load times are a lot better, nice job. There is still an increased load time when using the skin, but it's a lot smaller then before. I'm doing this test with about ~400 auras being loaded and we're talking maybe a 20% increase or less. I assume it'll get worse with more auras, but as you've said before, there might not be anything you can do about it. I would consider it good enough.

I did notice another issue and I'm not sure if this existed in previous versions or not. Without the skin, when the add to group button is pressed, aura groups are highlighted to indicate you can add the aura to it. [https://i.imgur.com/jnyZvVr.png](https://i.imgur.com/jnyZvVr.png) When skinned, nothing happens. [https://i.imgur.com/7K7zxhz.png](https://i.imgur.com/7K7zxhz.png)

**Comment by fang2hou** [comment]
Fixed in 3a29175

**Comment by Xyxeii** [comment]
are you tired of hearing from me yet? lol

I believe `widget.frame.backdrop.color = {widget.frame.backdrop.Center:SetVertexColor()}` is supposed to be `widget.frame.backdrop.color = {widget.frame.backdrop.Center:GetVertexColor()}` 

and I changed the onHide colour to `(1, 1, 1, 0.3)` personal preference. Otherwise looks like everything is good now. 

Thanks for the good work on this!

**Comment by fang2hou** [comment]
yeah, you are right.
The color is for non-group auras, so red maybe better in my mind 😃

**Comment by Xyxeii** [comment]
haha, you're the boss. Thanks again for the work you put into this. I'll close the issue and bug you if anything else comes up later.
