### ISSUE TITLE
Local Error 103[Bug]

### ISSUE THREAD

**Issue by spliffmaster** [fang2hou/ElvUI_WindTools#132]
**Describe the bug**

**To Reproduce**

Simply logging in gives me this error

 - Addon Version: 2.09
 - ElvUI Version 12.11
 - WoW Build 9.0.2 (36639)

Error from BugSack:

17x ...dOns\ElvUI_WindTools\Modules\Skins\Blizzard\Help.lua:12: attempt to index field 'Header' (a nil value)
[string "@ElvUI_WindTools\Modules\Skins\Blizzard\Help.lua"]:12: in function <...dOns\ElvUI_WindTools\Modules\Skins\Blizzard\Help.lua:6>
[string "=[C]"]: ?
[string "@ElvUI_WindTools\Modules\Skins\Core.lua"]:369: in function <ElvUI_WindTools\Modules\Skins\Core.lua:363>
[string "=[C]"]: ?
[string "@ElvUI_WindTools\Core\Core.lua"]:59: in function `InitializeModules'
[string "@ElvUI_WindTools\Initialize.lua"]:47: in function `?'
[string "@ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0-36.lua"]:303: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:299>
[string "=[C]"]: in function `Initialize'
[string "@ElvUI\init.lua"]:156: in function <ElvUI\init.lua:155>
[string "=[C]"]: ?
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...ceDetails\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...ceDetails\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by fang2hou** [comment]
I think the bug is only on sl beta, because there is no help frame in beta.
Do you have same issue in retail?

**Comment by fang2hou** [comment]
I added a confirmation before skinning in 2.10-beta-5, you can download the dev version from curse or github publish.

**Comment by spliffmaster** [comment]
> I think the bug is only on sl beta, because there is no help frame in beta.
> Do you have same issue in retail?

Correct.  I'm using the same ElvUI and Windtools versions in both retail and beta.  **I am only getting the error in beta.**

Thank you!
