### ISSUE TITLE
[Bug] Rematch皮肤错误

### ISSUE THREAD

**Issue by WeijieH** [fang2hou/ElvUI_WindTools#133]
**描述问题**
如图，放入恩佐斯掉落的宠物时贴图出错。其他小宠物暂时没发现问题。
![yJzpKhzfbW](https://user-images.githubusercontent.com/16510655/99431110-37413780-28d8-11eb-82d6-a3f0b7115504.png)

**Comment by fang2hou** [comment]
关掉皮肤有错么

**Comment by WeijieH** [comment]
又看了一下 应该不是WT的bug
