### ISSUE TITLE
[Bug][Module>Item>Delete Item] 'Fill by click' breaks when using the delete key

### ISSUE THREAD

**Issue by Xyxeii** [fang2hou/ElvUI_WindTools#134]
When 'Fill by click' is selected in the 'Delete Item' module and you attempt to delete an item with the delete key, an error is thrown.
`1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI_WindTools' tried to call the protected function 'DeleteCursorItem()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: ?
[string "@ElvUI_WindTools\Modules\Item\DeleteItem.lua"]:51: in function <...eElvUI_WindTools\Modules\Item\DeleteItem.lua:49>`

Blizzard seems to have made DeleteCursorItem() a [protected function that can only be called by hardware event](https://wow.gamepedia.com/API_DeleteCursorItem) so you might have to make a workaround to this functionality. You could possibly merge the functionality of 'Auto fill' and capture the delete key and have it confirm the dialog box.

**Comment by fang2hou** [comment]
I will check it tmr, zhCN and zhTW now is still 9.0.1

**Comment by fang2hou** [comment]
fixed in 4a121182b9ca955e4cc6532a13b7685a65ef87b8

**Comment by Xyxeii** [comment]
It's a shame that blizzard protected this function cause I really loved the one click delete. I'm finding the auto-fill option to be much more useful now after this change since I just press enter to delete. 

I'm not sure if you wanted to add `if DI.fillInButton then DI.fillInButton:SetText("|cff2ecc71" .. L["Confirmed"] .. "|r") end` after the line you changed or something similar to update the fillInbutton text when you press delete.
