### ISSUE TITLE
请问是否愿意接手并加入boss战自动修改专精拾取

### ISSUE THREAD

**Issue by yongri0** [fang2hou/ElvUI_WindTools#136]
[ToggleLootSpeciazation.zip](https://github.com/fang2hou/ElvUI_WindTools/files/5577727/ToggleLootSpeciazation.zip)
![WoWScrnShot_112120_215233](https://user-images.githubusercontent.com/74823931/99879007-64794700-2c44-11eb-9669-b55f7506237b.jpg)
本人插件入门小白
手里有一个很古老且轻量化的小插件，因为拾取列表及下拉框选择锚定在地下城手册的boss列表里，直接通过获取boss信息关联，不用建立list，所以易维护，随游戏版本更迭后简易修复下依然可用。对多职责职业收集装备避免疏忽而错误专精拾取比较有用。

希望能对大秘境的拾取切换进行支持，参考了一部分其他插件的原理进行改造，但对代码一知半解而未能解决问题。如果大佬愿意接手并加入windtools最好。
希望能看到大佬的正确作业并学习。

todo：
1、对大米支持，专精选择下拉框体可以锚定在地下城列表页，通过api获取副本名称，这样版本更新依然可用。
![WoWScrnShot_112120_215246](https://user-images.githubusercontent.com/74823931/99879170-f6358400-2c45-11eb-8ac6-0feb4b04e299.jpg)
2、目前插件无法对难度进行分别存储，存在团本H、M难度同boss不同拾取的需求，设想过关联地下城手册中的难度下拉框
![WoWScrnShot_112120_221050](https://user-images.githubusercontent.com/74823931/99879276-ca66ce00-2c46-11eb-9bb8-4133b95a6439.jpg)

部分功能借鉴学习LootSpecManager：难度分组，大米完成拾取动作后改回原拾取设置

**Comment by fang2hou** [comment]
有空看看吧

**Comment by fang2hou** [comment]
10.0 起已经不再需要这类功能了.
