### ISSUE TITLE
Lua error 

### ISSUE THREAD

**Issue by spliffmaster** [fang2hou/ElvUI_WindTools#137]
_Simply logging in produces the error_

 - Addon Version: 2.11 RETAIL
 - ElvUI Version 12.13
 - WoW Build 9.0.2 (36710)

**Not sure if this is a bugsack error or WindTools:**

9x ElvUI_WindTools\Modules\Skins\Core.lua:101: attempt to index field 'skins' (a nil value)
[string "@ElvUI_WindTools\Modules\Skins\Core.lua"]:101: in function `CreateBackdropShadow'
[string "@ElvUI_WindTools\Modules\Skins\Addons\BugSack-v9.0.1.lua"]:18: in function <...Ons\ElvUI_WindTools\Modules\Skins\Addons\BugSack.lua:8>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `OpenSack'
[string "@BugSack\core.lua"]:59: in function <BugSack\core.lua:46>
[string "=[C]"]: ?
[string "@AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@!BugGrabber\BugGrabber.lua"]:147: in function <!BugGrabber\BugGrabber.lua:145>
[string "@!BugGrabber\BugGrabber.lua"]:380: in function <!BugGrabber\BugGrabber.lua:294>
[string "=[C]"]: in function `?'
[string "@XRoll\XRoll-5.0.1.lua"]:3124: in function <XRoll\XRoll.lua:3123>

Locals:
self = <table> {
 Blizzard_Channels = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\Channels.lua:6
 WeakAuras_ShowOptions = <function> defined @ElvUI_WindTools\Modules\Skins\Addons\WeakAurasOptions.lua:177
 ElvUI_AFK = <function> defined @ElvUI_WindTools\Modules\Skins\ElvUI\AFK.lua:7
 modules = <table> {
 }
 CancelTimer = <function> defined @Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:147
 GuildInviteFrame = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\Guild.lua:6
 ElvUI_UnitFrames_Configure_Threat = <function> defined @ElvUI_WindTools\Modules\Skins\ElvUI\UnitFrames.lua:11
 SkinCriteriaAlert = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\Alerts.lua:62
 RaidUtility_ShowButton_OnClick = <function> defined @ElvUI_WindTools\Modules\Skins\ElvUI\RaidUtility.lua:9
 Blizzard_LossOfControlFrame_SetUpDisplay = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\LossOfControl.lua:6
 Rematch_Standalone = <function> defined @ElvUI_WindTools\Modules\Skins\Addons\Rematch.lua:796
 ScheduleTimer = <function> defined @Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 SkinItemButton = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\ObjectiveTracker.lua:20
 ADDON_LOADED = <function> defined @ElvUI_WindTools\Modules\Skins\Core.lua:279
 ElvUI_CastBars = <function> defined @ElvUI_WindTools\Modules\Skins\ElvUI\CastBars.lua:14
 Rematch = <function> defined @ElvUI_WindTools\Modules\Skins\Addons\Rematch.lua:904
 ElvUI_SkinOptionsUI = <function> defined @ElvUI_WindTools\Modules\Skins\ElvUI\Option.lua:7
 SetEnabledState = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:274
 enteredLoad = <table> {
 }
 DressUpFrame = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\DressingRoom.lua:6
 BigWigs_Plugins = <function> defined @ElvUI_WindTools\Modules\Skins\Addons\BigWigs.lua:22
 AAP_SkinOrderList = <function> defined @ElvUI_WindTools\Modules\Skins\Addons\AzerothAutoPilot.lua:11
 UnregisterAllEvents = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SkinWorldQuestCompleteAlert = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\Alerts.lua:171
 WeakAuras = <function> defined @ElvUI_WindTools\Modules\Skins\Addons\WeakAuras.lua:161
 Blizzard_Calendar = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\Calendar.lua:6
 ElvUI_ClassBars = <function> defined @ElvUI_WindTools\Modules\Skins\ElvUI\ClassBars.lua:12
 ElvUI_SkinDataBar = <function> defined @ElvUI_WindTools\Modules\Skins\ElvUI\DataBars.lua:8
 SkinLegendaryItemAlert = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\Alerts.lua:236
 Blizzard_DebugTools = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\DebugTools.lua:7
 name = "ElvUI_WindTools_Skins"
 StaticPopup = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\StaticPopup.lua:6
 SkinFindGroupButton = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\ObjectiveTracker.lua:32
 TTGameTooltip_SetDefaultAnchor = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\Tooltips.lua:14
 Unhook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:418
 WeakAuras_RegisterRegionOptions = <function> defined @ElvUI_WindTools\Modules\Skins\Addons\WeakAurasOptions.lua:32
 Blizzard_BlackMarketUI = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\BlackMarket.lua:6
 Blizzard_IslandsQueueUI = <function> defined @AddOns

**Comment by fang2hou** [comment]
do you try to reload ui once?
it perhaps happened when elvui updating database

**Comment by spliffmaster** [comment]
I'll check and see.
