### ISSUE TITLE
WindTools导致支持无法打开

### ISSUE THREAD

**Issue by lvv787** [fang2hou/ElvUI_WindTools#138]
问题：WindTools导致“主菜单-支持”无法打开，一直在转圈。
详细信息：
1、elvui 12.13   windtools 2.11
2、只有ElvUI和ElvUI_WindTools开启
3、BugSack没有反馈
4、只开启elvui大退进入，打开“支持”这是OK的，加上windtools重载“支持”无法打开

**Comment by fang2hou** [comment]
哪个服务器?

**Comment by lvv787** [comment]
燃烧之刃

**Comment by lvv787** [comment]
> 哪个服务器?

燃烧之刃

**Comment by fang2hou** [comment]
开启过滤器或者反和谐会造成这个情况.

**Comment by fang2hou** [comment]
如果你想开启这两个, 那么客服这里爆炸就是必定的, 毕竟修改地区到非国服了.

**Comment by lvv787** [comment]
> 如果你想开启这两个, 那么客服这里爆炸就是必定的, 毕竟修改地区到非国服了.

OK！我关闭了“社交-过滤器”（尽管我不知道他是干什么的）现在可以打开“支持”了，“反和谐”我没有改依旧是0，可能我是直接改Config.wtf（我在windtools里没有找到）。感谢你有效的回复and你们团队做的贡献。

**Comment by fang2hou** [comment]
过滤器就是用来解锁国服锁定的不当言语过滤器
反和谐是要手动的, 但如果地区不强制改到其他地区那么也不会生效

**Comment by lvv787** [comment]
> 过滤器就是用来解锁国服锁定的不当言语过滤器
> 反和谐是要手动的, 但如果地区不强制改到其他地区那么也不会生效

好的，谢谢解答
