### ISSUE TITLE
[Request] LDB or Datatext For Guild/Friends

### ISSUE THREAD

**Issue by Gennoken** [fang2hou/ElvUI_WindTools#139]
Hey,
WT is a kind of AiO package, and it's growing, i can see that it it sometimes inspire from other addons functions or code.

Can you consider adding a Datatexts for Guild members and Friends just like SLE do ?

For example
[https://www.curseforge.com/wow/addons/iguild](url)
[https://www.curseforge.com/wow/addons/ifriends](url)

Fix them for 9.01 and add them to WT ? if you see what i mean.

Thank you

**Comment by fang2hou** [comment]
I don't use datatext for long time, so I have no motivation on the development of additional datatexts, but it may added some day if I have time.
