### ISSUE TITLE
功能请求：不显示橙装的制造者信息

### ISSUE THREAD

**Issue by qyh214** [fang2hou/ElvUI_WindTools#143]
希望能增加一个小功能，不显示橙装的制造者信息
目前9.0中如果是橙装胚子来源他人制作，则会显示他人名字

**Comment by fang2hou** [comment]
为啥要隐藏? 这不是暴雪故意加上的名字么

**Comment by qyh214** [comment]
哈哈，主要是自己辛辛苦苦爬塔弄的材料，然后因为自己不是相关专业的，因为胚子的关系，就会带上别人制造的信息，有点难受，哈哈，如果能做个开关不显示制造者信息就更好了

**Comment by fang2hou** [comment]
OK, 加好了.
在[其他]里面, 可以先下载测试版试试.
