### ISSUE TITLE
[Bug]战场右键举报时有一个函数报错

### ISSUE THREAD

**Issue by JerichoZG** [fang2hou/ElvUI_WindTools#144]
战场，大地图右键举报玩家AFK时报错，BugSack内容如下：
1x [ADDON_ACTION_FORBIDDEN] 插件 'ElvUI_WindTools' 尝试调用保护功能 'ReportPlayerIsPVPAFK()'。
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `ReportPlayerIsPVPAFK'
[string "@Blizzard_SharedMapDataProviders\GroupMembersDataProvider.lua"]:189: in function `func'
[string "@SharedXML\UIDropDownMenu.lua"]:905: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

**Comment by fang2hou** [comment]
我没法修复这个, 因为我不打PVP

**Comment by JerichoZG** [comment]
收到，我自己试试吧，谢谢啦
