### ISSUE TITLE
[Bug] No shadows on custom DataText Panels

### ISSUE THREAD

**Issue by Beet4** [fang2hou/ElvUI_WindTools#146]
**Describe the bug**
There are no shadows on the custom DataText Panels you can create in ElvUI. The default DataText-panels such as those below the chat panels have shadows but not the custom ones. Please see screenshot below, DataTexts under Chat Panels have shadow but the custom one in the bottom middle under my actionbar does not have shadows.

**To Reproduce**
1. Enable Shadows in ElvUI WindTools
2. Go to ElvUI - >DataTexts -> Panels
3. Create a new Panel
4. No shadow is applied to the new panel

**Expected behavior**
Have shadow on these DataTexts as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/38279393/102667709-53abea80-418a-11eb-822b-43234403aeec.png)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: [e.g. 2.15]
 - ElvUI Version [e.g. 12.16]

**Comment by fang2hou** [comment]
fixed in 651b1927b7c84ed7acdfbd26127900d02515795f
