### ISSUE TITLE
[Bug] No Shadow on Castbar icons when inside castbar

### ISSUE THREAD

**Issue by Beet4** [fang2hou/ElvUI_WindTools#147]
**Describe the bug**
If you have icons on castbars enabled and set to show icon inside the castbar shadow does not extend to include the icon part If you have the icon separated from the castbar it has a shadow. It seems to be the same for all unitframes castbars.

**To Reproduce**
1. Go to Unitframes -> (for example) Player -> Castbar
2. Enable Icon
3. Set to show icon inside castbar
4. See error (might need a reload of icon was previous separated).

**Expected behavior**
It would be logical if the shadow from the castbar extends around the icon as well.

**Screenshots**
Icon inside castbar without shadow:
![WoWScrnShot_122020_220338](https://user-images.githubusercontent.com/38279393/102724409-9fd46780-430f-11eb-88ca-d63dff499b30.jpg)

Separate icon with shadow:
![WoWScrnShot_122020_220228](https://user-images.githubusercontent.com/38279393/102724391-91864b80-430f-11eb-9d95-cdcd6eaead1b.jpg)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.15
 - ElvUI Version 12.16
 - WoW Build 9.0.2

**Comment by fang2hou** [comment]
actually i added it before, however 2 shadows are not looks good, the overlap is weird.
you can separate the icon from cast bar and make a little bit offset, that is the better way.
