### ISSUE TITLE
关于 Modules/Chat/ChatMod.lua

### ISSUE THREAD

**Issue by someblu** [fang2hou/ElvUI_WindTools#15]
是否可以考虑把tab切换功能移出工具箱？
原因是

1. 已经有现成的聊天插件 [tinychat](http://bbs.ngacn.cc/read.php?tid=10240957) 和 [chatbar](http://bbs.ngacn.cc/read.php?tid=9633520&rand=40)
2. tab切换模块的频道循环不支持扩展，因为他采用枚举法遍历几个常用频道，添加新频道及其的麻烦，而上面提到的两个聊天插件的tab切换模块是支持在用户已加入的所有频道中循环的。
3. 的确可以将前两个聊天插件的tab切换模块移植到windtools（只需要简单的复制粘贴，且不需要加入elvui设置项），但这样就没有必要了，不如直接引导用户去下载这两个插件。

**Comment by fang2hou** [comment]
那就默认关闭好了，因为我现在不用任何其他的聊天插件，只用这个来循环发话，移除之后我就没法用了 T_T

**Comment by someblu** [comment]
我是之前一直在用chatbar，而后今天试了下windtools的tab切换，发现独立密语循环的开关不是很有用。
在chatbar中，密语是始终独立循环的，不过可以通过按shift+tab的组合键的方式，跳出密语循环，回归频道循环。

**Comment by fang2hou** [comment]
要不索性哪天直接把聊天条放进去算了，一劳永逸

**Comment by someblu** [comment]
我有一个大胆的想法，就是联系[chatbar](https://github.com/tytannial/ChatBar)的作者 @tytannial，征求他的同意并把chatbar整合到windtools里面。
比较麻烦的是，他目前是通过直接修改lua文件的形式修改插件配置，这样的话整合的时候就需要为每个模块都新增elvui设置项，不过好在他已经专门为elvui适配新增了一个分支，支持通过elvui移动框体。

**Comment by fang2hou** [comment]
看了下他的代码感觉还是不整合了，很多功能只是面向中文玩家的，现在上了 Curse 还是要考虑下外国玩家的。反正逛NGA的基本也都会看到他的帖子，应该也没事，到时候帖子里推荐他的链接。
