### ISSUE TITLE
[Bug]标记mark条骷髅标记问题

### ISSUE THREAD

**Issue by 133930722** [fang2hou/ElvUI_WindTools#150]
**描述问题**
mark条骷髅标记点选范围有问题，只能在边缘点选，其他标记图示点选范围为整个图示区域

**Comment by fang2hou** [comment]
无法复现.

**Comment by 133930722** [comment]
无法复现的话只能用手机拍个照给您看下，抱歉
![2021_01_17_20_38_IMG_8166](https://user-images.githubusercontent.com/43874766/104843162-1f9c2480-5904-11eb-92d5-a070bafd7b0c.JPG)
![2021_01_17_20_37_IMG_8164](https://user-images.githubusercontent.com/43874766/104843169-29258c80-5904-11eb-8c98-55e32be1806f.JPG)
![2021_01_17_20_37_IMG_8165](https://user-images.githubusercontent.com/43874766/104843172-2cb91380-5904-11eb-814c-799303db5ef2.JPG)
指针在骷髅标志的下半部分无法点选，以及和其他标志的下半部对比

**Comment by 133930722** [comment]
抱歉 自查已解决问题~
