### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by tramperdk** [fang2hou/ElvUI_WindTools#153]
**Describe the bug**
There seems to be some sizing issues with adding the Garrison icon to your Minimap button bar.

**To Reproduce**
1. Enable Garrison under Maps -> Minimap buttons -> Blizzard Buttons
2. Fly to Oribos from any location

**Expected behavior**
I expect the button to be the same size and position as the rest of the buttons, but the icon moves (Please note the space it should be in actually stays open as if it was there.

**Screenshots**
https://i.imgur.com/UoHVVJn.png

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.16
 - ElvUI Version 12.17
 - WoW Build 9.0.2 (37176)

**Additional context**
I don't know if Oribos is related but it happens when you're just about to get to it.
Let me know if you want a recording.

**Comment by fang2hou** [comment]
Confirmed.
WindTools cannot handle garrison icon very well now, I will fix it if I have time.

**Comment by fang2hou** [comment]
fixed in a481df279100a34b0dc489a19687640c9ba0b6e0
