### ISSUE TITLE
无法显示队友进度

### ISSUE THREAD

**Issue by anyclub** [fang2hou/ElvUI_WindTools#155]
已用桃乐豆 更新最新版本
但是还是无法显示堆有大米次数等信息
鼠标提示里面已经开启相关选项,还是需要什么其他操作么

**Comment by fang2hou** [comment]
按住 shift 看.

**Comment by anyclub** [comment]
只能用SHIFT么
能设置其他按键么?

**Comment by fang2hou** [comment]
这是跟随 ElvUI 的.
因为进度其实是成就统计比对, 还是非常消耗资源, 如果默认不按修饰键就进行比对的话会造成很大的性能问题.
