### ISSUE TITLE
[Bug] Power frames attached to a unitframe do not extend shadows to account for the attached frame

### ISSUE THREAD

**Issue by NotJamesM** [fang2hou/ElvUI_WindTools#158]
**Describe the bug**
Power frames attached to a unitframe do not extend shadows to account for the attached frame. If the power frame is detatched from another unitframe then the shadow is applied.

**To Reproduce**
1. Enable Skins -> check the "Shadows" option
2. UnitFrames -> Individual Frames -> Player -> Power -> Uncheck "Detach From Frame"
3. Shadow has not been extended to account for the attached frame

**Expected behavior**
When the power frame is attached to a unitframe the shadow should be extended to account for the attached power frame.

**Screenshots**
Attached
![image](https://user-images.githubusercontent.com/13240950/108235583-dbd44f00-713d-11eb-9b16-c730794715a7.png)
Detached
![image](https://user-images.githubusercontent.com/13240950/108235657-f1497900-713d-11eb-88b0-7feb4c81d880.png)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: [e.g. 2.17]
 - ElvUI Version [e.g. 12.2]
 - WoW Build [e.g. 9.0.2 (37474)]

**Comment by fang2hou** [comment]
the shadow of attached power bar is not supported now, because some features from elvui (e.g. threat indicator) also using the shadow, so the reposition will be overrided by elvui.
