### ISSUE TITLE
关于 Modules/Quest/CloseQuestVoice.lua

### ISSUE THREAD

**Issue by someblu** [fang2hou/ElvUI_WindTools#16]
我对比了一下代码发现这个模块和[bequiet](https://www.curseforge.com/wow/addons/bequiet)的代码重复度很高，是不是来源于这个插件，如果是的话鸣谢名单可能需要增加一项。

而后，在bequiet中，是有对当前所处地图进行过滤的：
```Lua
--Query subzone text when the talkinghead plays
zoneName = GetSubZoneText();
--If we are not doing withered training, suppress the talkinghead
if zoneName ~= "Temple of Fal'adora" and
   zoneName ~= "Falanaar Tunnels" and
   zoneName ~= "Shattered Locus" then
     TalkingHeadFrame_CloseImmediately()
end
```

是否考虑要将这段代码加入windtools，不过这个和bfa的任务地图无关，只有练级的时候可能会遇到。

**Comment by someblu** [comment]
可能需要改为调用C_Map.GetBestMapForUnit()来支持多语言环境

**Comment by fang2hou** [comment]
我的代码来源是官方论坛回复，BeQuiet估计和我看到的一样。
之前我看过BeQuiet的代码，地区过滤这个我感觉其实没啥用，如果你有空可以加一下。

**Comment by someblu** [comment]
感觉也不是很有必要。。都是些苏拉玛任务涉及到的图，会用这个模块功能的人也估计都已经做过了。
