### ISSUE TITLE
[Bug] 任务追踪列表字体阴影错误

### ISSUE THREAD

**Issue by xanahopper** [fang2hou/ElvUI_WindTools#161]
**描述问题**
更新 9.0.5 之后，任务追踪列表中文字的阴影丢失，尝试禁用 Wind 工具箱后恢复。
（也未找到对应的任务文字样式修改，可能是没看到？）

**错误复现**
错误复现步骤:
1. 更新至 9.0.5
2.  进入游戏
4. 看到了错误

**预期功能**
文字具有默认的、便于识别的阴影

**截图**
无

**插件信息 (请填写基本信息, 你可以在 [信息] 中找到):**
 - 插件版本: 2.17
 - ElvUI 版本 12.21
 - 游戏版本 9.0.5

**Comment by fang2hou** [comment]
不好意思之前很忙, 没有在看插件相关的问题.

是下面这样的任务追踪么? 请问是哪一种阴影呢?
![image](https://user-images.githubusercontent.com/6694722/114222878-1625d400-99aa-11eb-893e-e6d4a38ea411.png)

**Comment by xanahopper** [comment]
> 不好意思之前很忙, 没有在看插件相关的问题.
> 
> 是下面这样的任务追踪么? 请问是哪一种阴影呢?
> ![image](https://user-images.githubusercontent.com/6694722/114222878-1625d400-99aa-11eb-893e-e6d4a38ea411.png)

就是截图中这个文字的 outline，不过我看似乎最近两天更新之后正常了？

**Comment by fang2hou** [comment]
没有问题了就好~
