### ISSUE TITLE
[Enhancement] Separate Auto-Accept and Auto-Turn-in functionality

### ISSUE THREAD

**Issue by JaxxArmstrong** [fang2hou/ElvUI_WindTools#162]
Hello and thank you for a great ElvUI addon. Much appreciated, thank you.

As it stands now Auto-Accept quests and Auto-Turn-in quests are linked to the same on/off toggle, ie if you turn on the Auto-Turn-in functionality you automatically enable the Auto-Accept functionality, which is not always what you want.

May I humbly ask that you separate those functionalities above into separate on/off switches so the user can explicitly choose what he/she wants, please.

**Comment by fang2hou** [comment]
added in [97c8c59](https://github.com/fang2hou/ElvUI_WindTools/commit/97c8c5945d9c1488a47cb06e2f8e037a5cc70cea)
