### ISSUE TITLE
[Bug] Community invitation blocked

### ISSUE THREAD

**Issue by mutanzoom** [fang2hou/ElvUI_WindTools#164]
**Describe the bug**
The bug (error message) came when I was invited to a community and I could not accept this invitation.

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.18 Windtool
 - ElvUI Version 12.24
 - WoW Build Version 9.05.(38556) 

**Additional context**
Here is the error code I got. When I deactivated Windtool, I was only able to accept the invitation.

> 1x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI_WindTools' hat versucht die geschützte Funktion 'AcceptInvitation()' aufzurufen.
> [string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
> [string "=[C]"]: in function `AcceptInvitation'
> [string "@Blizzard_Communities\CommunitiesInvitationFrame.lua"]:89: in function `AcceptInvitation'
> [string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

**Comment by fang2hou** [comment]
Did you test with only ElvUI_WindTools & ElvUI enabled?
To my experience, ADDON_ACTION_FORBIDDEN usually occurred by other addons.

**Comment by mutanzoom** [comment]
You might be right about that. Later I looked again at the Bug Sack (addon). I received 2 error messages. These from Windtool and MoveAnything.
It could of course also be that MoveAnything is causing the error.
1x [ADDON_ACTION_FORBIDDEN] AddOn 'MoveAnything' hat versucht die geschützte Funktion 'AcceptInvitation()' aufzurufen.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `AcceptInvitation'
[string "@Blizzard_Communities\CommunitiesInvitationFrame.lua"]:89: in function `AcceptInvitation'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

**Comment by fang2hou** [comment]
Stop all modules/addons that making frames movable may helped.
Some protected Blizzard functions are easily getting error if you moved some frames.

**Comment by fang2hou** [comment]
Reopen this issue if you confirmed this problem caused by WindTools.
