### ISSUE TITLE
paragon reputation error

### ISSUE THREAD

**Issue by Heldwiin** [fang2hou/ElvUI_WindTools#167]
65x ...\ElvUI_WindTools\Modules\Quest\ParagonReputation.lua:117: attempt to index field '?' (a nil value)
[string "@ElvUI_WindTools\Modules\Quest\ParagonReputation.lua"]:117: in function `Tooltip'
[string "@ElvUI_WindTools\Modules\Quest\ParagonReputation.lua"]:136: in function <...\ElvUI_WindTools\Modules\Quest\ParagonReputation.lua:135>
[string "=[C]"]: ?

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:367
 ChangeReputationBars = <function> defined @ElvUI_WindTools\Modules\Quest\ParagonReputation.lua:260
 Enable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:235
 EnableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 SecureHookScript = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:410
 defaultModuleLibraries = <table> {
 }
 RawHookScript = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:395
 QUEST_ACCEPTED = <function> defined @ElvUI_WindTools\Modules\Quest\ParagonReputation.lua:228
 CreateToast = <function> defined @ElvUI_WindTools\Modules\Quest\ParagonReputation.lua:196
 GetName = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
 initialized = true
 toast = ParagonReputation_Toast {
 }
 defaultModuleState = true
 name = "ElvUI_WindTools_ParagonReputation"
 Initialize = <function> defined @ElvUI_WindTools\Modules\Quest\ParagonReputation.lua:367
 IsEnabled = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 baseName = "ElvUI_WindTools"
 DisableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:350
 HookReputationBars = <function> defined @ElvUI_WindTools\Modules\Quest\ParagonReputation.lua:130
 ProfileUpdate = <function> defined @ElvUI_WindTools\Modules\Quest\ParagonReputation.lua:397
 WaitToast = <function> defined @ElvUI_WindTools\Modules\Quest\ParagonReputation.lua:190
 CreateBarOverlay = <function> defined @ElvUI_WindTools\Modules\Quest\ParagonReputation.lua:240
 RegisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 HookScript = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:366
 SendMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 Tooltip = <function> defined @ElvUI_WindTools\Modules\Quest\ParagonReputation.lua:112
 IsHooked = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:493
 SetupParagonTooltip = <function> defined @ElvUI_WindTools\Modules\Quest\ParagonReputation.lua:93
 ColorWatchbar = <function> defined @ElvUI_WindTools\Modules\Quest\ParagonReputation.lua:82
 IsModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:217
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:387
 UnregisterAllEvents = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 ShowToast = <function> defined @ElvUI_WindTools\Modules\Quest\ParagonReputation.lua:149
 SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 UnregisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 RegisterEvent = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 hooks = <table> {
 }
 SetDefaultModulePrototype = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 SecureHook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:336
 IterateModules = <function> defined @Interf

**Comment by fang2hou** [comment]
can you help me to test `2.21-beta-1`?
https://github.com/fang2hou/ElvUI_WindTools/tree/2.21-beta-1

**Comment by Heldwiin** [comment]
Hello
Yes I test today :)

**Comment by fang2hou** [comment]
if you still have problem in `2.21`, reopen this issue.

**Comment by Heldwiin** [comment]
It’s work perfectly 😊

 

Thanks

 

De : Zhou Fang ***@***.***> 
Envoyé : samedi 3 juillet 2021 05:06
À : fang2hou/ElvUI_WindTools ***@***.***>
Cc : Heldwiin ***@***.***>; Author ***@***.***>
Objet : Re: [fang2hou/ElvUI_WindTools] paragon reputation error (#167)

 

can you help me to test 2.21-beta-1?
https://github.com/fang2hou/ElvUI_WindTools/tree/2.21-beta-1
