### ISSUE TITLE
[Bug]任务列表无法控制位置

### ISSUE THREAD

**Issue by yufan-zhao** [fang2hou/ElvUI_WindTools#168]
**描述问题**
打开ElvUI设置面板，点击切换定位开关，任务列表并未加入到可选移动。

**错误复现**
错误复现步骤:
1. 打开 ElvUI配置面板
2. 点击 切换定位开关
3. 看到了错误

**预期功能**
任务面板可移动

**截图**
![image](https://user-images.githubusercontent.com/15375987/124372771-7d100c00-dcbf-11eb-9c7b-1bd7ea47fac1.png)

**插件信息 (请填写基本信息, 你可以在 [信息] 中找到):**
 - 插件版本: 2.21
 - ElvUI 版本 12.24
 - 游戏版本 9.1.0[39291]

**更多信息**
暂时没时间做更多测试来确定是否是本身的缺陷还是其他插件的影响

**Comment by fang2hou** [comment]
更新 ElvUI 到 12.31
