### ISSUE TITLE
[Bug] Player Choice Frame shows border shadow

### ISSUE THREAD

**Issue by Toludin** [fang2hou/ElvUI_WindTools#169]
**Describe the bug**
As of 9.1, the Player Choice Frame (when you pick an Anima Power) shows a rectangular shadow when you have ElvUI's Player Choice Frame skin on *and* have the Shadow option on Windtools turned on. If Shadow is off in Windtools, this doesn't appear.

**To Reproduce**
1. Enable ElvUI and Windtools
2. Make sure ElvUI's Player Choice Frame skin is on
3. Make sure Windtools' Shadow option is on under Skins
4. Go into Torghast and look at the frame when you pick an anima power

**Expected behavior**
No shadow shows around the non-existent border of this frame

**Screenshots**
With Windtools' Shadow option on and ElvUI's skin on:
https://i.imgur.com/QXozUgw.png

With Windtools' Shadow option off:
https://i.imgur.com/5XwwSOH.png

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.21
 - ElvUI Version: 12.33
 - WoW Build 9.1.0.39291

**Comment by fang2hou** [comment]
checked

**Comment by fang2hou** [comment]
fixed in 36556944daefff8041a6a6250a8d99386fb6f697
