### ISSUE TITLE
Use Tab key cannot switch to world trade channel

### ISSUE THREAD

**Issue by yvx5166** [fang2hou/ElvUI_WindTools#170]
**Describe the bug**
Tab cannot switch to world trade channel

**To Reproduce**

**Expected behavior**
You could use tab to change to all channel including world channel, world trading channel. and even your personal channel

**Screenshots**

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.21
 - ElvUI Version 12.33
 - WoW Build 9.1
 - 
**Additional context**
很好用的一个elvui插件 希望作者能够增加用tab切换到全聊天频道的功能 包括交易和全球频道

**Comment by fang2hou** [comment]
暴雪不允许.
只能支持以下频道: https://wowwiki-archive.fandom.com/wiki/ChatTypeId
