### ISSUE TITLE
[Bug]Wind工具箱会导致国服游戏客户端的“支持”菜单打开台服的登录页面

### ISSUE THREAD

**Issue by z16166** [fang2hou/ElvUI_WindTools#171]
游戏版本：国服9.1.0.39335
Wind工具箱版本： 2.21
ElvUI版本：12.33

重现步骤：
1、在游戏的角色选择界面，禁用所有插件。
2、选择一个角色进入游戏。
3、启用ElvUI和ElvUI Options插件，重新加载全部插件。
     按ESC，点击游戏的“支持"菜单，能打开国服的客服支持页面。
4、在步骤3的基础上进一步启用"ElvUi Wind工具箱"插件，重新加载全部插件。
     按ESC，点击游戏的“支持"菜单，不能打开国服的客服支持页面，而是试图打开的台服的单点登录网址。
5、禁用"ElvUI Wind工具箱"插件，重新加载全部插件。还是不能打开国服的客服页面。
但是重启游戏客户端后，把1~5再走一遍，是必现的。

游戏内置的chrome浏览器所打开的URL在如下日志文件中能看到：
C:\Program Files (x86)\World of Warcraft\_retail_\Logs\BlizzardBrowser\Browser-*.log

对应的这条日志内容为：
[INFO]-[BNL_Browser]: 2021-07-11T03:11:43 {9dcc} [INFO] - denied navigation to 'https://tw.battle.net/login/sso?token=CN-XXXX&ref=https://www.battlenet.com.cn/support/zh/help/home'.

**Comment by fang2hou** [comment]
现在除了强制修改地区没有其他办法可以解除屏蔽词.
如果觉得不能接受, 可以取消勾选过滤器解锁功能.

**Comment by z16166** [comment]
这会干扰游戏的正常功能，那我觉得是不是默认不要启用这个功能，而且在用户启用这个功能时给出一个警告呢？

**Comment by fang2hou** [comment]
> 这会干扰游戏的正常功能，那我觉得是不是默认不要启用这个功能，而且在用户启用这个功能时给出一个警告呢？
> 
> 我可是折腾了好久才定位这个问题的，包括重装整个wow客户端、重装战网客户端、删除wow Agent目录，仔细对比wow的WTF目录的内容，以及逐个启用插件。
> 
> 幸好我也算是个资深码农，不然小白用户碰到这种情况，不明白原因，还在游戏内联系不了GM，他如何是好？

确实一定程度上干扰了普通 GM 功能. 不过游戏内的 GM 功能本来就有很多问题, 经常访问不了. 网页端的 GM 功能才是一直稳定可用的.
现在这个功能所有国内的插件都是标配了, 几年下来事实上很少有人问这个, nga 也有不少帖子讲解这个原理.
ElvUI 的逻辑是 `if 当前配置 == 默认配置 then 不保存配置, 直接读取默认`.
如果我现在改默认, 全部人的反和谐都会失效, 所以默认关闭的话要下个大版本改动的时候才能改了.
