### ISSUE TITLE
Missing shadows

### ISSUE THREAD

**Issue by Beet4** [fang2hou/ElvUI_WindTools#172]
**Describe the bug**
Since last time I played I noticed that shadows on Power-bar and information panel does not work. Please see screenshots.

**To Reproduce**
1. Enable shadows in WindTools
2. Have power bar attached to frame
3. Have information panel activated

**Expected behavior**
Shadows should be visible on power-bar and information panel as well. Looks a bit strange as it is now.

**Screenshots**
Old screenshot from January:
![image](https://user-images.githubusercontent.com/38279393/125510793-079cea0d-1617-4d25-bc3b-9e7945c9f9ac.png)

How it looks now with newer version:
![image](https://user-images.githubusercontent.com/38279393/125510885-a4e09821-5b82-45e5-adc6-0bc939d04c97.png)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.21
 - ElvUI Version 12.34
 - WoW Build 9.1.0 (39335)

**Comment by fang2hou** [comment]
It seems elvui make some changes in their unitframes, I will check it.

**Comment by fang2hou** [comment]
fixed in af044141d8836118ec31673108319ba1443f15ef
