### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by merodahero** [fang2hou/ElvUI_WindTools#173]
**Describe the bug**
i have only elvui and windtools loaded  and whenever i open the character window by pressing "c"
 it gives this error (file attatched) and the character screen does not open, same happens when i press u to open the reputation 

 - Addon Version: 2.21
 - ElvUI Version : 12.34
 - WoW Build:  9.1.0 (39427)
[error.txt](https://github.com/fang2hou/ElvUI_WindTools/files/6833267/error.txt)

**Comment by fang2hou** [comment]
The bug probably not caused by WindTools, and I also cannot reproduce it in my game.
If you still have this problem, we can talk about it in Discord server.
