### ISSUE TITLE
[Bug] WeakAuras Bar Icon stays if toggled off

### ISSUE THREAD

**Issue by Nercus** [fang2hou/ElvUI_WindTools#174]
**Describe the bug**
WeakAuras Bars have an option to toggle an icon. If the icon is toggled off the background of the icon stays on the screen where the initial position of the WA was. Only reloading removes that frame.

**To Reproduce**
1. Create a new Bar in WeakAuras
2. Set the _Show Icon_ to `on`
3. Set the _Show Icon_ to `off`
4. Move the Bar to somewhere else on the screen
5. The background/shadow of the icon can be seen

**Expected behavior**
No icon background if a bar doesn't have an icon. 

**Screenshots**
The lower box is the background of the previously enabled icon of the bar seen above it. The bar was moved up there.
![image](https://user-images.githubusercontent.com/48932939/128134289-0f310eed-19ce-47e4-90b8-b365beca509e.png)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: [2.22]
 - ElvUI Version [12.38]
 - WoW Build [9.1.0 (Build 39617)]

**Additional context**
Sometimes the same happens if a group with several different bars is selected in the WeakAuras options where some of the WAs inside have _Show Icon_ set to off. I havn't found clear steps to fully reproduce this issue, but that is the more annoying problem.

**Comment by fang2hou** [comment]
you can disable skins for wa temporally.
The details I will check in-game later.

**Comment by fang2hou** [comment]
fixed in 2.24.
