### ISSUE TITLE
[Bug] My transmog/wardrobe is broken when Windtools is enabled

### ISSUE THREAD

**Issue by dnbarclay** [fang2hou/ElvUI_WindTools#175]
**Describe the bug**
With Windtools enabled, my Wardrobe/Transmog UI is broken, in that Art is missing for all items, buttons are unclickable/missing text, and inspect frame is non-existent.

**To Reproduce**
1. Go to any Transmog vendor and click the option to Transmogify my gear.

**Expected behavior**
The above described problem occurs.

**Screenshots**
https://cdn.discordapp.com/attachments/222356141785612288/874696688860807198/unknown.png

**Information (you can find these in [WindTools-Information]):**
https://cdn.discordapp.com/attachments/222356141785612288/874717918162739241/unknown.png

**Additional context**

**Comment by fang2hou** [comment]
maybe you can try `clear history` in `move frames` module.

**Comment by dnbarclay** [comment]
Clearing the history did not help

**Comment by fang2hou** [comment]
Could you try one more time with ___only___ Elvui and Elvui Windtools 2 addons opened?
And then clear the history of `Move Frames` module, or just disbale `Move Frames` may helped.

This problem always occured by conflict with other addons.

**Comment by fang2hou** [comment]
If you still have this problem, reopen this issue.
