### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Darkut** [fang2hou/ElvUI_WindTools#176]
https://github.com/fang2hou/ElvUI_WindTools/blob/331463deb2e882d1ec2ec100d2243f7988f93ec1/Locales/ruRU.lua#L620

Should be - Идеал

**Comment by fang2hou** [comment]
@Evgeniy-ONiX fixed this translation in 1a951a9e4f074fa4b25079419011a670a92110f9.
Thanks for you feedback.
