### ISSUE TITLE
[Bug] Covenant minimap button randomly returns to its original position

### ISSUE THREAD

**Issue by gokomer** [fang2hou/ElvUI_WindTools#177]
Covenant minimap button randomly returns to its original position. I've no idea what triggers this behavior.

**To Reproduce**
1. Go to Maps->Minimap Buttons and enable it
2. Button randomly returns to the its original position.

**Expected behavior**
It should be stay at minimap buttons bar

**Screenshots**
![windtools](https://user-images.githubusercontent.com/11593018/133141542-2c6dea1b-863e-489b-9cbd-de71a3b9cba5.JPG)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.25 ( I've experienced the issue in 2.24 too)
 - ElvUI Version 12.44
 - WoW Build 9.1.0

**Comment by fang2hou** [comment]
Same as https://github.com/fang2hou/ElvUI_WindTools/issues/153

**Comment by fang2hou** [comment]
Can you test the latest alpha version?
I add some stuffs to handle the icon in 2.26-alpha-1

**Comment by gokomer** [comment]
I was in torghast and when I left there it became like this.

![windtools](https://user-images.githubusercontent.com/11593018/133278740-2b6a6a03-51a6-4976-bd80-a48516cc447d.JPG)

**Comment by fang2hou** [comment]
😭 that's bad, I'll keep looking for solution

**Comment by fang2hou** [comment]
@ #153

**Comment by fang2hou** [comment]
fixed in a481df279100a34b0dc489a19687640c9ba0b6e0
