### ISSUE TITLE
[Bug] Minimap buttons shows a gray square on top of the icon

### ISSUE THREAD

**Issue by Toludin** [fang2hou/ElvUI_WindTools#178]
**Describe the bug**
Minimap buttons are showing a backdrop on top of the icon.

**To Reproduce**
1. Turn on Maps > Minimap Buttons in Windtools
2. View the icons below the minimap
3. Note the gray/black squares on top of some/most icons

**Expected behavior**
Icons should be clearly visible, like the Altoholic icon in my screenshot (as opposed to the other icons)

**Screenshots**
https://i.imgur.com/9UEHZ30.png

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.26
 - ElvUI Version: 12.46
 - WoW Build 9.1.5

**Additional context**
I haven't fully tested without other addons loaded, so if this isn't readily reproducible for anyone else, I can try turning off other addons to see if there's another culprit.

Also, while the setup seen in my screenshot (the right-most 6 icons have issues while Altoholic does not) is the most common I've seen, there are times where some other icons don't have the issue present.

**Comment by fang2hou** [comment]
I will take a look after asian server updated.

**Comment by fang2hou** [comment]
The problem has been fixed in 52db8a77221c934e4fb73c45dbc4a660d7eab4dd commit.

Thank you for your reporting with clearly information.
