### ISSUE TITLE
是否可以发布到Twitch/Curse上

### ISSUE THREAD

**Issue by liugongkai111** [fang2hou/ElvUI_WindTools#18]
非常感谢您的贡献, 对我来说, 这个工具箱就是对elvui的**最完美**增强. 

因此, 是否可以请您将此工具箱发布到Twitch/Curse的服务器上?
如果这样做, 可能会有以下好处:

- 让更多的人了解这款优秀的插件

- 更方便的用户体验, 第一时间就能使用到最新版本, 从而减少不必要的错误报告

- 设置参数备份

- 版本追踪及管理

- and more...

再次感谢您的贡献, 并且希望您能够参考我的建议.

**Comment by fang2hou** [comment]
嗯，分离媒体包就是有这个打算了。
