### ISSUE TITLE
[BUG] 2.26版本更新后小地图图标

### ISSUE THREAD

**Issue by YuuChoi** [fang2hou/ElvUI_WindTools#181]
![Shot_2021-11-06_14-51-21](https://user-images.githubusercontent.com/73652784/140600876-8a4fa1b9-0fd5-47c4-8ba5-ebbf32931651.png)
小地图图标显示错误

**Comment by fang2hou** [comment]
测试版本已经修复.

**Comment by fang2hou** [comment]
https://github.com/fang2hou/ElvUI_WindTools/issues/178
