### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by devil81** [fang2hou/ElvUI_WindTools#183]
**Describe the bug**

**To Reproduce**

Every time i click on extra bar i get this error , my extra bar its show on mousover ... i use last release version of elvui and wintools

16x ElvUI_WindTools\Modules\Item\ExtraItemBar.lua:886: attempt to perform arithmetic on field 'alphaMin' (a nil value)
[string "@ElvUI_WindTools\Modules\Item\ExtraItemBar.lua"]:886: in function <ElvUI_WindTools\Modules\Item\ExtraItemBar.lua:881>

Locals:
self = WTExtraItemsBar1 {
 0 = <userdata>
 WrapScript = <function> defined @FrameXML\SecureHandlers.lua:782
 buttons = <table> {
 }
 id = 1
 backdrop = <unnamed> {
 }
 UnwrapScript = <function> defined @FrameXML\SecureHandlers.lua:788
 register = true
 SetFrameRef = <function> defined @FrameXML\SecureHandlers.lua:793
 fadeInfo = <table> {
 }
 alphaMin = 0
 alphaMax = 1
 FadeObject = <table> {
 }
 Execute = <function> defined @FrameXML\SecureHandlers.lua:777
}
alphaCurrent = 0
(*temporary) = <function> defined @ElvUI\Core\General\Animation.lua:327
(*temporary) = <table> {
 GetTimeInfo = <function> defined @ElvUI\Core\General\Math.lua:389
 mylevel = 60
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 FormatMoney = <function> defined @ElvUI\Core\General\Math.lua:441
 StaticPopup_EscapePressed = <function> defined @ElvUI\Core\General\StaticPopups.lua:439
 UpdateUnitFrames = <function> defined @ElvUI\Core\General\Core.lua:1381
 SetMoversPositions = <function> defined @ElvUI\Core\General\Movers.lua:463
 ScheduleTimer = <function> defined @ElvUI\Core\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:94
 PriestColors = <table> {
 }
 RemoveEmptySubTables = <function> defined @ElvUI\Core\General\Core.lua:633
 Cooldown_Options = <function> defined @ElvUI\Core\General\Cooldowns.lua:121
 UIScale = <function> defined @ElvUI\Core\General\PixelPerfect.lua:55
 db = <table> {
 }
 SetEnabledState = <function> defined @ElvUI\Core\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 Layout = <table> {
 }
 UnregisterEventForObject = <function> defined @ElvUI\Core\General\Core.lua:1693
 Distributor = <table> {
 }
 DBConvertSL = <function> defined @ElvUI\Core\General\Core.lua:1261
 INCOMPATIBLE_ADDONS = <table> {
 }
 PositionGameMenuButton = <function> defined @ElvUI\Core\General\API.lua:592
 UIFrameFade = <function> defined @ElvUI\Core\General\Animation.lua:274
 TimeIndicatorColors = <table> {
 }
 TexturePath = "ElvUI\Media\Textures\"
 StaticPopup_CreateSecureButton = <function> defined @ElvUI\Core\General\StaticPopups.lua:1103
 Truncate = <function> defined @ElvUI\Core\General\Math.lua:139
 TimeThreshold = 3
 ToggleMoveMode = <function> defined =[C]:-1
 RemoveTableDuplicates = <function> defined @ElvUI\Core\General\Core.lua:655
 WorldMap = <table> {
 }
 Disable = <function> defined @ElvUI\Core\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:314
 DF = <table> {
 }
 SlideOut = <function> defined @ElvUI\Core\General\Animation.lua:209
 Unhook = <function> defined @ElvUI\Core\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:418
 UnregisterObjectForVehicleLock = <function> defined @ElvUI\Core\General\API.lua:441
 LockedCVars = <table> {
 }
 EscapeString = <function> defined @ElvUI\Core\init.lua:148
 ObjectEventFrame = <unnamed> {
 }
 StaticPopup_Resize = <function> defined @ElvUI\Core\General\StaticPopups.lua:704
 Tutorials = <function> defined @ElvUI\Core\General\Tutorials.lua:110
 mynameRealm = "Devilblast - Kazzak"
 ProfileTableToPluginFormat = <function> defined @ElvUI\Core\General\Core.lua:858
 ShortValueDec = "%.1f"
 oUF = <table> {
 }
 IterateEmbeds = <function> defined @ElvUI\Core\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 valueColorUpdateFuncs = <table> {
 }
 Config_CreateBottomButtons = <function> defined @ElvUI\Core\General\Config.lua:949
 RawHookScript = <function> defined @ElvUI\Core\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:395
 Classic = false
 BuildPrefixValues = <function> defined @ElvUI\Core\General\Math.lua:34
 myrole = "DAMAGER"
 CreateStatusFrame = <funct

**Expected behavior**

**Screenshots**

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: [e.g. 2.00]
 - ElvUI Version [e.g. 12.00]
 - WoW Build [e.g. 9.0.1 (25600)]

**Additional context**

**Comment by devil81** [comment]
Seems its fine with last alpha version

**Comment by fang2hou** [comment]
is the bug still exist? if you met some bugs with alphamin, try change the transparent setting in windtools options.

**Comment by fang2hou** [comment]
close this issue temporarily. if you met the bug again, please reopen this issue again.
