### ISSUE TITLE
Dash wouldn't gone if I enabled quest tracker feature of Windtools.

### ISSUE THREAD

**Issue by hobulian** [fang2hou/ElvUI_WindTools#184]
like below.. using latest ver updated 6 hours ago.
using shadow and light but disabled it's quest window function.
https://imgur.com/a/PgITIP2

My settings
https://imgur.com/a/U0pNsJZ

**Comment by fang2hou** [comment]
did you try reload the ui?

**Comment by hobulian** [comment]
> did you try reload the ui?

Tried. But same. Think lua code seems to force dash to be shown.

**Comment by fang2hou** [comment]
how is it going in latest version?

**Comment by fang2hou** [comment]
The code about the feature that removing the dash have been rewrite in latest version, it should be fixed.
If you meet this question again, please reopen this issue.

**Comment by hobulian** [comment]
https://imgur.com/a/N7s8ev3

Still happened
