### ISSUE TITLE
[Bug] Shadows does not work on actionbar when using Masque skins

### ISSUE THREAD

**Issue by Beet4** [fang2hou/ElvUI_WindTools#185]
**Describe the bug**
WindTools shadows does not work on actionsbars when Masque skins are enabled for actionbars in ElvUI.

**To Reproduce**
1. Enable shadows in WindTools 
2. Install Masque + skin
3. Enable Masque support for actionbars in Elvui
4. Reload

**Expected behavior**
Shadows to work even when masque is used on actionbars.

**Screenshots**
![image](https://user-images.githubusercontent.com/38279393/143722069-085c710d-c3e3-4cbd-bd89-405829d1d711.png)
Masque support disabled in ElvUI actionbars

![image](https://user-images.githubusercontent.com/38279393/143722037-f40f8449-efda-4f3b-a4a1-563539a7937e.png)
Masque enabled + KlixUI skin used on actionbars. No shadow

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.28
 - ElvUI Version 12.57
 - WoW Build 9.1.5 (build 41079)

**Comment by fang2hou** [comment]
This is not bug, the shadow is annoying when using some masque skins (circle, etc.)

**Comment by fang2hou** [comment]
in addition, you can add shadows of masque skins with editing textures inside the directory of masque skin addons.
