### ISSUE TITLE
[Bug?] Windows Defender reports ElvUI WindTools update as a trojan

### ISSUE THREAD

**Issue by Toludin** [fang2hou/ElvUI_WindTools#186]
**Describe the bug**
Updating to 2.28 today via WowUp triggered Windows Defender, reporting that it was a trojan. Other addons updated just fine at the same time.

**To Reproduce**
1. Make sure Windows Defender is running (Windows 10)
2. Using WowUp, attempt to download the most recent WindTools file (2.28)

**Expected behavior**
No trojan report from Windows Defender

**Screenshots**
https://i.imgur.com/FUQyO1e.png

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.28

**Additional context**
Haven't tried using WowInterface as the source.

**Comment by fang2hou** [comment]
I dont use windows defender, you can check the report from other virus defense software providers.
https://www.virustotal.com/gui/file/59e4717bb6b28c27c3e28e50fe1eeda9cce64ef2b9ebef1e2ac14ea2351d4736/detection

**Comment by fang2hou** [comment]
please make sure you download the file from curseforge, some updater program may download the version from other sites.
