### ISSUE TITLE
[Feature Request] Key bindings for Logout & Leave Group

### ISSUE THREAD

**Issue by Tbzz** [fang2hou/ElvUI_WindTools#188]
**Key Binding Options for:**
- Log out -> [/logout](https://wowpedia.fandom.com/wiki/MACRO_logout)
- Leave group -> [/script C_PartyInfo.LeaveParty()](https://wowpedia.fandom.com/wiki/Leave_Party)
- _BONUS_: Macro to leave instance if alone -> [/inv 1; /pr 1; /script C_PartyInfo.LeaveParty()](https://wowpedia.fandom.com/wiki/Leave_Party)

**Example hotkeys I currently use with macros:**
- CTRL + | -> Log out
- ALT + SHIFT + | -> Leave party
- _BONUS_: CTRL + SHIFT + | -> Leave instance if alone

**Usecase:**
- Save space on action bars by not needing a macro for each of these.

**Comment by fang2hou** [comment]
added in 2b3ac9d7941b87f2167779bbe4f1bd1a87ac062e
