### ISSUE TITLE
[Bug] Strange bug when i mouseover the extra bars from wintools

### ISSUE THREAD

**Issue by devil81** [fang2hou/ElvUI_WindTools#189]
Message: ...AddOns\ElvUI_WindTools\Modules\Item\ExtraItemBar.lua:871: attempt to perform arithmetic on field 'alphaMax' (a nil value)
Time: Fri Dec 24 18:31:16 2021
Count: 35
Stack: ...AddOns\ElvUI_WindTools\Modules\Item\ExtraItemBar.lua:871: attempt to perform arithmetic on field 'alphaMax' (a nil value)

Locals: 

im using last version of elvui + last version of windtools , i get this alot after reload its ok ... 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: [e.g. 2.00]
 - ElvUI Version [e.g. 12.00]
 - WoW Build [e.g. 9.0.1 (25600)]

**Additional context**

**Comment by devil81** [comment]
Can you please help me ? I realy love this addon and tbh i dont wana disable the extra bars but it is very annoying evert time i mouseover the 2 bars i have enable to get this error pop-up . 

im using Elvui-WindTools Version: 2.28 and Elvui 12.58 and i also try the last DEV version ( today ) . 



This is the error i get : 

Message: ...AddOns\ElvUI_WindTools\Modules\Item\ExtraItemBar.lua:871: attempt to perform arithmetic on field 'alphaMax' (a nil value)
Time: Fri Dec 24 18:31:16 2021
Count: 35
Stack: ...AddOns\ElvUI_WindTools\Modules\Item\ExtraItemBar.lua:871: attempt to perform arithmetic on field 'alphaMax' (a nil value)

Locals:

**Comment by fang2hou** [comment]
can you give me a screenshot of your style setting of bars? (something like transparent alpha, etc.)

**Comment by fang2hou** [comment]
fixed in 286fd427ab1c862d7d640a742473ec7905e6b7c9
