### ISSUE TITLE
[Bug] Automatic invitaion function is not working.

### ISSUE THREAD

**Issue by Black-Beer** [fang2hou/ElvUI_WindTools#191]
**Describe the bug**
Automatic invitaion function is not working.

**To Reproduce**
Precondition:
Elvui, windtools only turned on. 
(If Elvui is only turned on, the issue does not occur.)

**Steps to reproduce the behavior:**

1. Go to 'Make a party for the global boss'
![image](https://user-images.githubusercontent.com/70205796/155888603-52243251-3bd9-454f-8525-a58a81aa5801.png)

2. Clink on Make a party 

**Expected behavior**

Automatically make a party and checked Auto invite function 
![auto_invite](https://user-images.githubusercontent.com/70205796/155888673-a7d43c00-bbed-4335-b426-438fc93a71b4.png)

**Issues**

Show the general raid table creation window.
![image](https://user-images.githubusercontent.com/70205796/155888722-eb45f1e8-2fa7-48df-be66-7ec03ce36da8.png)

Automatic invitation is not on/off even after the party is made.
![image](https://user-images.githubusercontent.com/70205796/155888908-bc5c73d3-0575-43c6-af2b-cf98a0535036.png)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: [e.g. 2.29]
 - ElvUI Version [e.g. 12.66]
 - WoW Build [e.g. 9.2.0 (42488)]

**Additional context**

**Comment by Black-Beer** [comment]
I don't know if this will help, but I'm attaching it. Bugsack error message.

[ADDON_ACTION_BLOCKED] 애드온 'ElvUI'|1이;가; 보호된 함수 'GetPlaystyleString()' 호출을 시도했습니다.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@FrameXML\LFGList.lua"]:1013: in function `LFGListEntryCreation_OnPlayStyleSelected'
[string "@FrameXML\LFGList.lua"]:647: in function `LFGListEntryCreation_Show'
[string "@FrameXML\LFGList.lua"]:2062: in function <FrameXML\LFGList.lua:2059>

**Comment by fang2hou** [comment]
maybe some api changed in recent game update, i will fix it after i return to wow.

**Comment by fang2hou** [comment]
@Black-Beer Have you tried the latest beta version?

**Comment by fang2hou** [comment]
It seems the problem fixed with latest change of objective tracker, if you meet this question again, please reopen it.
