### ISSUE TITLE
[Bug] Cosmic Healing Potion is not listed as Potion (Shadowlands)

### ISSUE THREAD

**Issue by Buckwyster** [fang2hou/ElvUI_WindTools#192]
The new healing potion (Cosmic Healing Potion) is not listed in as part of PotionSL group.

For extraitembar.lua, local potionsShadowlands array should be updated with item id 187802 to add this new 9.2 potion to the Potion SL group.

It is possible to manually add Potion to custom list as a temporary workaround.

**Comment by fang2hou** [comment]
added in d8b256d4ffb33094700ab740a4f88d4fb499a2cd
