### ISSUE TITLE
[Feature Request] Option to hide Blizzard default loot panel

### ISSUE THREAD

**Issue by Skullcan** [fang2hou/ElvUI_WindTools#195]
Hi, first of all, thanks for the amazing addon!

As of now I have to use an extra addon to hide the default loot panel at the end of the dungeons.
It would be great if the Windtools offered an option to hide!

Reason is, it is bugged since SL PTR and Blizzard won't fix T_T
Sometimes it shows loot from dungeons / raids you've completed before.

There's an addon to do this atm and it's code is super simple, so maybe add it as an option in Windtools?

```
local f = CreateFrame("Frame")
f:RegisterEvent("PLAYER_LOGIN")
f:SetScript("OnEvent", function()
    BossBanner:UnregisterEvent("ENCOUNTER_LOOT_RECEIVED")
end)
```

This is the code of the addon that hides this panel. 

Thanks again.

**Comment by fang2hou** [comment]
added in 8e2704325831b5fb8b02be3d0cff6891b1b10116
