### ISSUE TITLE
[Bug] 鼠标提示模块的“添加图标”功能会覆盖其它插件添加的图标样式

### ISSUE THREAD

**Issue by gjfLeo** [fang2hou/ElvUI_WindTools#196]
**描述问题**
鼠标提示模块的“添加图标”功能会覆盖其它插件添加的图标样式。

**错误复现**
例如使用 AllTheThings 插件时，鼠标提示添加了一些含图标的内容。当启用 WindTools 的“添加图标”功能时，AllTheThings 插件添加的所有图标的样式也会被覆盖为和 WindTools 添加的物品图标相同。
其它类似场景也会出现（例如插件在鼠标提示中添加 `|T4067362:0|t`，实际生效时就会变为 WindTools 物品图标的样式）。

**预期功能**
添加物品图标时不应覆盖其它图标的样式。

**截图**
两张图分别为开启“添加图标”功能和关闭“添加图标”功能时的鼠标提示。
<img width="260" alt="Snipaste_2022-03-30_01-17-30" src="https://user-images.githubusercontent.com/27762219/160669198-fe04764d-2578-4482-96de-a595dd27ddce.png">
<img width="266" alt="Snipaste_2022-03-30_01-15-52" src="https://user-images.githubusercontent.com/27762219/160669277-525d9964-35ee-42f8-836f-4d13fb1c0cb7.png">

**插件信息 (请填写基本信息, 你可以在 [信息] 中找到):**
 - 插件版本: 2.29
 - ElvUI 版本 12.7
 - 游戏版本 9.2.0 (42852)

**Comment by fang2hou** [comment]
Bug 其实算不上，之前有点偷懒了，把图标美化直接扔到了添加图标的代码中。

在 14df35efc7bb549a7c15f7d93e81a462f64d1efb 中进行了如下改动：
1. 移除在添加标题图标时进行的后续行图标美化
2. 将图标美化作为鼠标提示的美化皮肤的一部分提供
