### ISSUE TITLE
[Bug] Raider.io Role Icon broken after update to 2.30

### ISSUE THREAD

**Issue by rockschtar** [fang2hou/ElvUI_WindTools#197]
**Describe the bug**
Raider.io Role Icon is broken after update to 2.30

**To Reproduce**
1. Install ElvUI
2. Install ElvUI Windtools 2.30
3. Install Raider.IO Addon
4. Hover with mouse over unitframe to see tooltip

**Expected behavior**
The role icon should be shown next to RIO-Score (See Screenshots)

**Screenshots**
With ElvUI Windtools 2.29
![before](https://user-images.githubusercontent.com/87191/161313352-e1cf3f3f-4f0b-419a-ae3d-211e8c2d08dc.png)

With ElvUI Windtools 2.30
![image](https://user-images.githubusercontent.com/87191/161313423-90efa1df-b355-4570-bb93-d5b535ef450d.png)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.30
 - ElvUI Version 12.73
 - WoW Build latest

**Additional context**
Tried to disable any role icons in WindTools settings but doesn't help. If I downgrade to WindTools 2.29 the icons are correct.

**Comment by fang2hou** [comment]
temporarily, disable windtools - skins - blizzard - tooltips, it will be fixed soon
