### ISSUE TITLE
[Bug] WeakAuras Options throwing Lua error

### ISSUE THREAD

**Issue by InfusOnWoW** [fang2hou/ElvUI_WindTools#198]
**Describe the bug**
Causes a lua error with latest WeakAuras Alpha

**To Reproduce**
1. Download WeakAuras alpha
2. Enable WeakAuras Options skinning
3. Open WeakAuras Options via /wa

**Expected behavior**
WeakAuras Options open

**Screenshots**

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.29
 - ElvUI Version 12.73
 - WoW Build 9.2
 - WeakAuras: Alpha Version

**Additional context**
WeakAuras Alpha contains a significant rework of the Options window.

**Comment by InfusOnWoW** [comment]
1x ..._WindTools\Modules\Skins\Addons\WeakAurasOptions-@project-version@.lua:640: attempt to index field 'WeakAurasTooltipImportButton' (a nil value)
[string "@ElvUI_WindTools\Modules\Skins\Addons\WeakAurasOptions-@project-version@.lua"]:640: in function <..._WindTools\Modules\Skins\Addons\WeakAurasOptions.lua:475>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `ShowOptions'
[string "@WeakAurasOptions\WeakAurasOptions-@project-version@.lua"]:625: in function `ToggleOptions'
[string "@WeakAuras\WeakAuras-@project-version@.lua"]:106: in function `OpenOptions'
[string "WEAKAURASTOGGLE"]:1: in function <[string "WEAKAURASTOGGLE"]:1>

**Comment by fang2hou** [comment]
sorry, i cannot confirm the bug with weakaura 3.7.16-27-g0ef58ce

**Comment by fang2hou** [comment]
The issue will be closed since the windtools works great in recent weakauras alpha version.
If you meet this bug again, feel free to reopen this issue.✌️
