### ISSUE TITLE
[Bug]Dash wouldn't gone if I enabled quest tracker feature of Windtools.

### ISSUE THREAD

**Issue by hobulian** [fang2hou/ElvUI_WindTools#199]
#184 Still happen

https://imgur.com/a/N7s8ev3

dashes are showing on completed sub-objects

Unchecking removing dash feature causes this. cuzs it makes dash to be always shown.

**Comment by fang2hou** [comment]
fixed in af7e28b1c6d2128bb5ded57acdeb9be8f470ea12
