### ISSUE TITLE
[Bug] Cannot see other region's name at friendlist.

### ISSUE THREAD

**Issue by hobulian** [fang2hou/ElvUI_WindTools#200]
Literally. If I am in korean server and my friend plays in US then, I cannot see his region info at friendlist but only "-"

So

at 306~307 Line of FriendList.lua 
have to be like
if server and server ~= E.myrealm then				
				buttonText = F.CreateColorString(C_BattleNet_GetFriendAccountInfo(button.id).gameAccountInfo.richPresence, self.db.areaColor)

**Comment by fang2hou** [comment]
fixed in 03197952730385f055d9a823deec6ab12abafdde and 897eeeaee0282e1813375f1e138363e072f71965
