### ISSUE TITLE
Again. Dash problem on objective tracker

### ISSUE THREAD

**Issue by hobulian** [fang2hou/ElvUI_WindTools#201]
![image](https://user-images.githubusercontent.com/26172440/165196963-e26c0026-1398-4b67-b49f-701102e86fe4.png)
Dash showns on empty line. happened on zereth mortis world quest.
https://www.wowhead.com/quest=65230/%EA%B8%B0%EA%B3%84%EC%8B%9D%EB%AC%BC%ED%95%99

**Comment by fang2hou** [comment]
Now I have no character which can go to Zereth Mortis, I will focus this problem after I go to Zereth Mortis.
