### ISSUE TITLE
[BUG]信息文字大量Lua错误

### ISSUE THREAD

**Issue by YuuChoi** [fang2hou/ElvUI_WindTools#203]
如图，小地图下方信息文字面板无法正常显示，且产生大量Lua错误
![04-27_22-37-32_2022](https://user-images.githubusercontent.com/73652784/165544459-18888b65-2e7a-48d9-8693-85055174855b.png)
![04-27_22-37-27_2022](https://user-images.githubusercontent.com/73652784/165544465-3c608e5f-6dbe-4a6d-b951-6ce33dbf1912.png)

**Comment by YuuChoi** [comment]
另，若仅载如ElvUI本体则一切正常

**Comment by fang2hou** [comment]
ElvUI 版本, 工具箱版本号是多少?
试过重新建立一个配置吗?

**Comment by YuuChoi** [comment]
受教了。
ElvUI 12.76，工具箱2.32。建立新配置后解决。
最后发现是字体的问题。原本用的是Continuum字体，但现在如下图所示，Continuum预览为我的默认字体。应该是字体文件缺失。
![04-28_07-10-10_2022](https://user-images.githubusercontent.com/73652784/165646138-c2b1180d-9266-486f-bb42-998592500cac.png)

**Comment by fang2hou** [comment]
这些字体因为之前 ElvUI 改动, 路径发生了变化, 游戏对于路径不对的字体都会使用默认字体.
新版本中进行了重新的指定, 所以又恢复正常了.
