### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by LadyDragon1160** [fang2hou/ElvUI_WindTools#205]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: [e.g. 2.00]
 - ElvUI Version [e.g. 12.00]
 - WoW Build [e.g. 9.0.1 (25600)]

**Additional context**
[
![Windtools Lua Error](https://user-images.githubusercontent.com/93698328/167278343-9f5d3ed0-d1a3-4a0c-9580-a14d5bb80c12.jpg)
](url)

**Comment by fang2hou** [comment]
please add the necessary information follow the template
