### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Fraktyl** [fang2hou/ElvUI_WindTools#206]
**Describe the bug**
WindTools and TSM are not playing nice.  When TSM is set to use it's vendor frame opening a vendor will show the TSM list and the default Blizzard frame.

I do not have the "Extend Merchant Pages" option checked in WindTools.  Disabling WindTools allows only one window to be displayed.

**To Reproduce**
1. Install TSM
2. Open Vendor
3. Both Windows shown

**Expected behavior**
Only one window should show.  Either the TSM one if it is set to open, or the Blizzard frame if set to open.

**Screenshots**
![Screenshot 2022-05-08 200208](https://user-images.githubusercontent.com/478132/167321333-d4ab10db-ca8c-491e-9697-83861660cc1b.jpg)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.34
 - ElvUI Version 12.79
 - WoW Build 9.2.0 (43345)

**Additional context**

**Comment by fang2hou** [comment]
Disable move frames. It's TSM's problem, if any addon make the merchantframe moveable, it cannot be hided.

**Comment by fang2hou** [comment]
I will write some codes to ignore this frame if TSM loaded and player checked the option in move frames.

**Comment by fang2hou** [comment]
try 2.35-alpha-1, you can download it from curse, wago.io or github release

**Comment by Fraktyl** [comment]
2.35-alpha-1 fixes the issue.  Thanks!
