### ISSUE TITLE
[Feature Request] Auto-Accept queueing

### ISSUE THREAD

**Issue by paroxp** [fang2hou/ElvUI_WindTools#207]
**Describe the feature**
Whilst being in a party, it would be great if we could auto-accept any queue requests from the leader - LFG, LFR, Battle Grounds, etc.

**Expected behavior**
Whilst in a party, and doing a quest, a party leader constantly signing us up for a M+, would not require me to continously click "Yes".

**Comment by fang2hou** [comment]
The feature will not be added. Because of most classes can queue as different roles, auto queue may take troubles that entering a instance with the role not expected.

**Comment by paroxp** [comment]
> The feature will not be added. Because of most classes can queue as different roles, auto queue may take troubles that entering a instance with the role not expected.

That's true, though it could be pre-emptivily selected and managed by the `Dungeons & Raids` window (see screenshot). In fact, I'm sure Leatrix Plus had similar functionality.

I won't be pushing you though, your call :)

![image](https://user-images.githubusercontent.com/2418945/168288803-dbb46f6c-8f48-4842-abbf-d48642dae70f.png)
