### ISSUE TITLE
[Feature Request] Auto-Accept summon

### ISSUE THREAD

**Issue by paroxp** [fang2hou/ElvUI_WindTools#208]
**Describe the feature**
Whilst being out of combat, it would be great if we could auto-accept any summon.

**Expected behavior**
If I'm meeting up with friends for a M+ or a Raid, but have to walk away from keyboard, it would be great if I could auto-accept summon.

**Comment by fang2hou** [comment]
added in f6b87b4655d7269a9b692a8f7d91bbed5147c862
