### ISSUE TITLE
[Feature Request] Auto-Accept resurrection

### ISSUE THREAD

**Issue by paroxp** [fang2hou/ElvUI_WindTools#209]
**Describe the feature**
It would be great if we could auto-accept a resurrection.

**Expected behavior**
When we wipe a boss on raid, and the healer is mass-resurrecting, it'd be good if I could walk away from keyboard and still accept the resurrection.

**Additional comments**
I assume, an additional option could be to auto-accept a battle resurrection.

**Comment by fang2hou** [comment]
add in f24ed15e80f2dfd2385943d5e1c0afbd1053f9f6
