### ISSUE TITLE
[Bug] Quick post - character buttons overlaping over icons

### ISSUE THREAD

**Issue by paroxp** [fang2hou/ElvUI_WindTools#210]
**Describe the bug**
The character buttons, for quick selection of who do I want to post to, as well as the category buttons are overlapping the icons allowing me to quickly send categorised stuff.

**To Reproduce**
1. Go to Mailbox
2. Click on `Send Mail` tab
3. See overlapping buttons

**Expected behavior**
The character buttons to have enough margin not to overlap.

**Screenshots**
![image](https://user-images.githubusercontent.com/2418945/168292675-6bcc58bc-851a-4d83-a990-994f20ce995e.png)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.34
 - ElvUI Version 12.79
 - WoW Build 9.2.0.43345

**Comment by fang2hou** [comment]
Just disable `Postal` or Contacts in `ElvUI_WindTools`.
They have almost same functionality, choose one of them to use.
