### ISSUE TITLE
[Bug] After Update WA to 4.0

### ISSUE THREAD

**Issue by hobulian** [fang2hou/ElvUI_WindTools#211]
After Weakauras 4.0 update when you open WA option window..

1x ..._WindTools\Modules\Skins\Addons\WeakAurasOptions-4.0.0.lua:648: attempt to index field 'WeakAurasTooltipImportButton' (a nil value)
[string "@ElvUI_WindTools\Modules\Skins\Addons\WeakAurasOptions-4.0.0.lua"]:648: in function <..._WindTools\Modules\Skins\Addons\WeakAurasOptions.lua:483>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `ShowOptions'
[string "@WeakAurasOptions\WeakAurasOptions-4.0.0.lua"]:625: in function `ToggleOptions'
[string "@WeakAuras\WeakAuras-4.0.0.lua"]:106: in function `OpenOptions'
[string "@WeakAuras\WeakAuras-4.0.0.lua"]:153: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5185: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4849: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4885: in function <FrameXML\ChatFrame.lua:4881>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
self = <table> {
 Blizzard_Channels = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\Channels.lua:6
 WeakAuras_ShowOptions = <function> defined @ElvUI_WindTools\Modules\Skins\Addons\WeakAurasOptions.lua:483
 ElvUI_AFK = <function> defined @ElvUI_WindTools\Modules\Skins\ElvUI\AFK.lua:7
 modules = <table> {
 }
 CancelTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:147
 GuildInviteFrame = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\Guild.lua:6
 ElvUI_UnitFrames_Configure_Threat = <function> defined @ElvUI_WindTools\Modules\Skins\ElvUI\UnitFrames.lua:23
 SkinCriteriaAlert = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\Alerts.lua:63
 RaidUtility_ShowButton_OnClick = <function> defined @ElvUI_WindTools\Modules\Skins\ElvUI\RaidUtility.lua:9
 Blizzard_LossOfControlFrame_SetUpDisplay = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\LossOfControl.lua:6
 Blizzard_WeeklyRewards = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\WeeklyRewards.lua:6
 Blizzard_PlayerChoice = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\PlayerChoice.lua:35
 SkinItemButton = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\ObjectiveTracker.lua:24
 ADDON_LOADED = <function> defined @ElvUI_WindTools\Modules\Skins\Core.lua:273
 WeakAurasIconButton = <function> defined @ElvUI_WindTools\Modules\Skins\Addons\WeakAurasOptions.lua:441
 ElvUI_CastBars = <function> defined @ElvUI_WindTools\Modules\Skins\ElvUI\CastBars.lua:59
 ElvUI_SkinOptionsUI = <function> defined @ElvUI_WindTools\Modules\Skins\ElvUI\Option.lua:7
 SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:274
 enteredLoad = <table> {
 }
 DressUpFrame = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\DressingRoom.lua:6
 TomCats_HeaderCollapseButton_SetNormalAtlas = <function> defined @ElvUI_WindTools\Modules\Skins\Addons\TomCats.lua:59
 BigWigs_Plugins = <function> defined @ElvUI_WindTools\Modules\Skins\Addons\BigWigs.lua:22
 Blizzard_AnimaDiversionUI = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\AnimaDiversion.lua:6
 AAP_SkinOrderList = <function> defined @ElvUI_WindTools\Modules\Skins\Addons\AzerothAutoPilot.lua:11
 UnregisterAllEvents = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 ElvUI_UnitFrames_Construct_AuraBars = <function> defined @ElvUI_WindTools\Modules\Skins\ElvUI\UnitFrames.lua:76
 SkinWorldQuestCompleteAlert = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\Alerts.lua:174
 WeakAuras = <function> defined @ElvUI_WindTools\Modules\Skins\Addons\WeakAuras.lua:177
 Blizzard_Calendar = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\Calendar.lua:6
 ElvUI_ClassBars = <function> defined @ElvUI_WindTools\Modules\Skins\ElvUI\ClassBars.lua:12
 ElvUI_SkinDataBar = <function> defined @ElvUI_WindTools\Modules\Skins\ElvUI\DataBars.lua:8
 SkinLegendaryItemAlert = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\Alerts.lua:246
 Blizzard_DebugTools = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\DebugTools.lua:7
 name = "ElvUI_WindTools_Skins"
 StaticPopup = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\StaticPopup.lua:6
 Blizzard_CovenantSanctum = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\CovenantSanctum.lua:6
 SkinFindGroupButton = <function> defined @ElvUI_WindTools\Modules\Skins\Blizzard\ObjectiveTracker.lua

**Comment by fang2hou** [comment]
fixed in 17ee5fa35cceb90e188e0dad3d80dbdc38e36da6
