### ISSUE TITLE
[Bug] Another LUA error regarding alpha from #213

### ISSUE THREAD

**Issue by KurtzPT** [fang2hou/ElvUI_WindTools#214]
A totally different error now, using the alpha from #213 :

```
Message: ...ddOns\ElvUI_WindTools\Modules\Skins\Widgets\Core.lua:136: bad argument #1 to 'pairs' (table expected, got nil)
Time: Tue May 24 17:32:23 2022
Count: 2
Stack: ...ddOns\ElvUI_WindTools\Modules\Skins\Widgets\Core.lua:136: bad argument #1 to 'pairs' (table expected, got nil)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI_WindTools\Modules\Skins\Widgets\Core.lua"]:136: in function `LazyLoad'
[string "@Interface\AddOns\ElvUI_WindTools\Modules\Skins\Widgets\Core.lua"]:146: in function `?'
[string "@Interface\AddOns\AllTheThings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\AllTheThings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\AllTheThings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...vUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>
```
This one happened after I used the teleport from Night of Fae covenant area to the mushroom in "The Ring"

**Comment by KurtzPT** [comment]
Also happens whenever I use the hearthstone.

**Comment by fang2hou** [comment]
try alpha-2

**Comment by Szvani** [comment]
+1  LUA error 

> Message: ...e\AddOns\ElvUI_WindTools\Modules\Misc\MoveFrames.lua:337: attempt to index field 'db' (a nil value)
Time: Wed May 25 07:10:17 2022
Count: 1
Stack: ...e\AddOns\ElvUI_WindTools\Modules\Misc\MoveFrames.lua:337: attempt to index field 'db' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI_WindTools\Modules\Misc\MoveFrames.lua"]:337: in function <...e\AddOns\ElvUI_WindTools\Modules\Misc\MoveFrames.lua:332>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetPoint'
[string "@Interface\FrameXML\UIParent.lua"]:3116: in function `UpdateUIPanelPositions'
[string "@Interface\FrameXML\UIParent.lua"]:2737: in function <Interface\FrameXML\UIParent.lua:2726>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3833: in function <Interface\FrameXML\UIParent.lua:3831>
[string "=[C]"]: ?
[string "=[C]"]: in function `securecall'
[string "@Interface\FrameXML\UIParent.lua"]:3013: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2862: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2730: in function <Interface\FrameXML\UIParent.lua:2726>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3582: in function <Interface\FrameXML\UIParent.lua:3561>
[string "=[C]"]: in function `ShowUIPanel'
[string "@Interface\AddOns\Blizzard_TalentUI\Blizzard_TalentUI.lua"]:117: in function <...rface\AddOns\Blizzard_TalentUI\Blizzard_TalentUI.lua:114>
[string "=[C]"]: in function `PlayerTalentFrame_Toggle'
[string "@Interface\FrameXML\UIParent.lua"]:917: in function `ToggleTalentFrame'
[string "TOGGLETALENTS"]:1: in function <[string "TOGGLETALENTS"]:1>

**Comment by KurtzPT** [comment]
Alpha-2 fixed the issue I reported 👍
