### ISSUE TITLE
unable to move vendor frame

### ISSUE THREAD

**Issue by nerf10** [fang2hou/ElvUI_WindTools#215]
Hi, since version 2.35, i can't move the vendor frames. I can move other frames like LFG, Map, AH...

I tried only having ElvUI and Windtools enabled but the issue persists.

I use **Misc** > **Move Frames**. I already tried **Clear History** without success. 
I reverted to version 2.34 and i can move Vendor frames but not with version 2.35 and 2.36 (or even 2.37 alpha 1).

Vendor frame is any NPC that displays a list of items for sale or repair.

example
![image](https://user-images.githubusercontent.com/63195275/170105760-9c2c7280-a532-451a-bcc0-a393d0d2456a.png)

Excellent addon, thank you for sharing it.

**Comment by fang2hou** [comment]
because you are using tsm, for compatible with tsm, the move frames module not worked.
you can uncheck the option in move frames to force enable the moving.

**Comment by nerf10** [comment]
You are correct, after disabling the option **TSM Compatible**, i can now move the frame.

I guess that this is confusing since I am using TSM and the option says that : Fixes the merchant frame showing when you using TSM.

Either way, thank you for telling me how to fix it :)

Keep up the great work.
