### ISSUE TITLE
LUA Error still present.

### ISSUE THREAD

**Issue by Szvani** [fang2hou/ElvUI_WindTools#216]
This problem is very confusing and has not been fixed.

> Message: ...e\AddOns\ElvUI_WindTools\Modules\Misc\MoveFrames.lua:337: attempt to index field 'db' (a nil value)
Time: Fri May 27 22:23:32 2022
Count: 1
Stack: ...e\AddOns\ElvUI_WindTools\Modules\Misc\MoveFrames.lua:337: attempt to index field 'db' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI_WindTools\Modules\Misc\MoveFrames.lua"]:337: in function <...e\AddOns\ElvUI_WindTools\Modules\Misc\MoveFrames.lua:332>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetPoint'
[string "@Interface\FrameXML\UIParent.lua"]:3116: in function `UpdateUIPanelPositions'
[string "@Interface\FrameXML\UIParent.lua"]:2737: in function <Interface\FrameXML\UIParent.lua:2726>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3833: in function <Interface\FrameXML\UIParent.lua:3831>
[string "=[C]"]: ?
[string "=[C]"]: in function `securecall'
[string "@Interface\FrameXML\UIParent.lua"]:3013: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2862: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2730: in function <Interface\FrameXML\UIParent.lua:2726>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3582: in function <Interface\FrameXML\UIParent.lua:3561>
[string "=[C]"]: in function `ShowUIPanel'
[string "@Interface\AddOns\Blizzard_TalentUI\Blizzard_TalentUI.lua"]:117: in function <...rface\AddOns\Blizzard_TalentUI\Blizzard_TalentUI.lua:114>
[string "=[C]"]: in function `PlayerTalentFrame_Toggle'
[string "@Interface\FrameXML\UIParent.lua"]:917: in function `ToggleTalentFrame'
[string "@Interface\FrameXML\MainMenuBarMicroButtons.lua"]:960: in function <Interface\FrameXML\MainMenuBarMicroButtons.lua:958>
[string "=[C]"]: ?

**Comment by fang2hou** [comment]
Did you test it with `/wrdebug on`?

**Comment by Szvani** [comment]
> Did you test it with `/wtdebug on`?

I just tested and turned off all other addons so it works perfectly the error is gone.

**Comment by fang2hou** [comment]
> > Did you test it with `/wtdebug on`?
> 
> I just tested and turned off all other addons so it works perfectly the error is gone.

That means you need to figure out the addon that affect the move frames feature. If you can reproduce the bug, it means the bug can be fixed.

**Comment by Szvani** [comment]
> > > Did you test it with `/wtdebug on`?
> > 
> > 
> > I just tested and turned off all other addons so it works perfectly the error is gone.
> 
> That means you need to figure out the addon that affect the move frames feature. If you can reproduce the bug, it means the bug can be fixed.

I turned off all the addons one by one. There was no problem. But now I have turned everything back on and for some reason the LUA error has completely disappeared.
