### ISSUE TITLE
[Bug] After 9.2.5, In friend list when there is friend playing Diablo Immortal

### ISSUE THREAD

**Issue by hobulian** [fang2hou/ElvUI_WindTools#219]
59x ElvUI_WindTools\Modules\Social\FriendList.lua:345: attempt to index field '?' (a nil value)
[string "@ElvUI_WindTools\Modules\Social\FriendList.lua"]:345: in function <ElvUI_WindTools\Modules\Social\FriendList.lua:193>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `FriendsFrame_UpdateFriendButton'
[string "@FrameXML\FriendsFrame.lua"]:1261: in function `FriendsFrame_UpdateFriends'
[string "@FrameXML\FriendsFrame.lua"]:629: in function `FriendsList_Update'
[string "@FrameXML\FriendsFrame.lua"]:307: in function <FrameXML\FriendsFrame.lua:306>
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:3017: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2862: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2730: in function <FrameXML\UIParent.lua:2726>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3582: in function <FrameXML\UIParent.lua:3561>
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML\FriendsFrame.lua"]:1068: in function `ToggleFriendsFrame'
[string "TOGGLESOCIAL"]:1: in function <[string "TOGGLESOCIAL"]:1>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:235
 EnableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 SecureHookScript = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:410
 defaultModuleLibraries = <table> {
 }
 RawHookScript = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:395
 GetName = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
 name = "ElvUI_WindTools_FriendList"
 Initialize = <function> defined @ElvUI_WindTools\Modules\Social\FriendList.lua:389
 IsEnabled = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:350
 UpdateFriendButton = <function> defined @ElvUI_WindTools\Modules\Social\FriendList.lua:193
 HookScript = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:366
 IsHooked = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:493
 IsModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:217
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:387
 SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 initialized = true
 baseName = "ElvUI_WindTools"
 ProfileUpdate = <function> defined @ElvUI_WindTools\Modules\Social\FriendList.lua:400
 hooks = <table> {
 }
 SetDefaultModulePrototype = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 SecureHook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:336
 IterateModules = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:437
 UnhookAll = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:477
 RawHook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:313
 Unhook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:418
 moduleName = "FriendList"
 defaultModuleState = true
 Disable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:314
}
button = FriendsListFrameScrollFrameButton8 {
 0 = <userdata>
 OnEnter = <function> defined @FrameXML\FriendsFrame.lua:1905
 index = 8
 buttonType = 2
 travelPassButton = FriendsListFrameScrollFrameButton8TravelPassButton {
 }
 status = FriendsListFrameScrollFrameButton8Status {
 }
 background = FriendsListFrameScrollFrameButton8Background {
 }
 OnClick = <function> defined @FrameXML\FriendsFrame.lua:2086
 OnLoad = <function> defined @FrameXML\FriendsFrame.lua:1893
 id = 7
 OnLeave = <function> defined @FrameXML\FriendsFrame.lua:2081
 name = FriendsListFrameScrollFrameButton8Name {
 }
 highlight = <unnamed> {
 }
 summonButton = FriendsListFrameScrollFrameButton8SummonButton {
 }
 info = FriendsListFrameScrollFrameButton8Info {
 }
 Favorite = <unnamed> {
 }
 gameIcon = FriendsListFrameScrollFrameButton8GameIcon {
 }
}
game = "ANBS"
realID = "|Kq104|k"
name = nil
server = nil
class = nil
area = nil
level = nil
note = ""
faction = nil
status = "AFK"
isInCurrentRegion = nil
regionID = nil
buttonTitle = "|Kq104|k"
buttonText = nil
realIDString = "|Kq104|k"
nameString = nil
classColor = nil
iconGroup = "ANBS"
(*temporary) = nil
(*temporary) = "Modern"
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil

**Comment by hobulian** [comment]
Related to Diablo Immotal maybe

**Comment by fang2hou** [comment]
added in c11c502a9ace6e9e51015b21233380ea33d51268
