### ISSUE TITLE
[Bug] Constant Lua errors after death (with release window up)

### ISSUE THREAD

**Issue by Toludin** [fang2hou/ElvUI_WindTools#220]
**Describe the bug**
Constant Lua errors after death (while the Release Spirit window is up)

**To Reproduce**
1. Die (in game)
2. Note error generated (see below for stacktrace)

**Expected behavior**
No errors generated

**Screenshots**

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.40
 - ElvUI Version 12.80
 - WoW Build 9.2.5

**Additional context**
Started with 9.2.5 patch

359x ...Ons\ElvUI_WindTools\Modules\Skins\Widgets\Button.lua:70: Usage: SecureHookScript(object, method, [handler]): 'handler' - Handler specified does not exist at self[handler]
[string "=[C]"]: ?
[string "@ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0-9.lua"]:139: in function <...ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:118>
[string "@ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0-9.lua"]:411: in function `SecureHookScript'
[string "@ElvUI_WindTools\Modules\Skins\Widgets\Button.lua"]:70: in function <...Ons\ElvUI_WindTools\Modules\Skins\Widgets\Button.lua:67>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetScript'
[string "@FrameXML\StaticPopup.lua"]:1245: in function <FrameXML\StaticPopup.lua:1242>
[string "=[C]"]: in function `UpdateRecapButton'
[string "@FrameXML\StaticPopup.lua"]:1260: in function `OnShow'
[string "@FrameXML\StaticPopup.lua"]:5092: in function `StaticPopup_OnShow'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\StaticPopup.lua"]:4888: in function <FrameXML\StaticPopup.lua:4439>
[string "=[C]"]: ?
[string "=[C]"]: in function `StaticPopup_Show'
[string "@FrameXML\UIParent.lua"]:1462: in function <FrameXML\UIParent.lua:1337>

Locals:
Skipped (In Encounter)

---

5x ...Ons\ElvUI_WindTools\Modules\Skins\Widgets\Button.lua:73: Usage: SecureHookScript(object, method, [handler]): 'handler' - Handler specified does not exist at self[handler]
[string "=[C]"]: ?
[string "@ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0-9.lua"]:139: in function <...ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:118>
[string "@ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0-9.lua"]:411: in function `SecureHookScript'
[string "@ElvUI_WindTools\Modules\Skins\Widgets\Button.lua"]:73: in function <...Ons\ElvUI_WindTools\Modules\Skins\Widgets\Button.lua:67>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetScript'
[string "@FrameXML\StaticPopup.lua"]:1246: in function <FrameXML\StaticPopup.lua:1242>
[string "=[C]"]: in function `UpdateRecapButton'
[string "@FrameXML\StaticPopup.lua"]:1260: in function `OnShow'
[string "@FrameXML\StaticPopup.lua"]:5092: in function `StaticPopup_OnShow'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\StaticPopup.lua"]:4888: in function <FrameXML\StaticPopup.lua:4439>
[string "=[C]"]: ?
[string "=[C]"]: in function `StaticPopup_Show'
[string "@FrameXML\UIParent.lua"]:1462: in function <FrameXML\UIParent.lua:1337>

Locals:
Skipped (In Encounter)

**Comment by fang2hou** [comment]
fix in 3f19c00ff07b680f95aae85dda6c238c8efa9399
