### ISSUE TITLE
[Bug] TLDR Missions second dropdown menus are not skinned

### ISSUE THREAD

**Issue by Mistrick** [fang2hou/ElvUI_WindTools#221]
**Describe the bug**
Second dropdown menus are not skinned.

**To Reproduce**
1. Go to 'Mission table'
2. Click on 'Sanctum Feature' or 'Crafting materials'
3. Move cursor on any item in first dropdown menu.
4. Second dropdown menu is not skinned.

**Expected behavior**
Skinned all parts of TLDR Missions

**Screenshots**
![image](https://user-images.githubusercontent.com/4307674/172763941-cb5c49af-c71a-478c-a532-2c7e036c2d7a.png)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.43
 - ElvUI Version 12.80
 - WoW Build 9.2.5 44061

**Comment by fang2hou** [comment]
actually it is elvui bug, i already told them.
