### ISSUE TITLE
聊天条按钮和背景设置失效

### ISSUE THREAD

**Issue by letsbug** [fang2hou/ElvUI_WindTools#222]
**描述问题**
社交->聊天条->设置按钮宽、高、间隙，条背景间距，保存，重载，失效

**错误复现**
如上描述

![CleanShot 2022-06-11 at 15 56 30](https://user-images.githubusercontent.com/8198443/173179065-304d9668-4e2c-40f6-a49a-1197e1060d7f.png)
这个小黑点应该就是聊天条背景框体，当我重新进入到设置界面，随意设置一个和按钮与背景有关的选项后，这个黑点就会隐藏，或者展开，恢复正常，再次重载插件又会失效

**插件信息:**
 - 插件版本: 2.43
 - ElvUI 版本: 12.80
 - 游戏版本: 9.2.5

![CleanShot 2022-06-11 at 15 54 19](https://user-images.githubusercontent.com/8198443/173179008-f26a734e-7e22-43f2-b23e-8325cb8f9ce5.png)

**更多信息**
如果你有更多信息, 在这里填写.

**Comment by fang2hou** [comment]
请先用 `/wtdebug on` 开启 debug 模式后再试试.

**Comment by letsbug** [comment]
重新试了下，好像是频道的问题，开启了某个频道的按钮，就必须填写值。否则就会出现这个问题，并且聊条框提示如下：

04:41 Wind 工具箱 [WARNING] [ChatBar] 没有找到社区频道, 请重新设定.

**Comment by fang2hou** [comment]
嗯, 这在设计上是不允许的.
如果一直不设定应该会一直弹出错误.

**Comment by letsbug** [comment]
也算是BUG，不设定的话会影响实际渲染结果

**Comment by fang2hou** [comment]
嗯, 我会稍微做个小修正这里
