### ISSUE TITLE
Error with WA's Expand button(Dunno in Eng)

### ISSUE THREAD

**Issue by hobulian** [fang2hou/ElvUI_WindTools#224]
Screenshot
https://ibb.co/b55kKj7

Bugsack Error
11x ..._WindTools\Modules\Skins\Addons\WeakAurasOptions-4.0.2.lua:128: attempt to call method 'ESProxy' (a nil value)
[string "@ElvUI_WindTools\Modules\Skins\Addons\WeakAurasOptions-4.0.2.lua"]:128: in function <..._WindTools\Modules\Skins\Addons\WeakAurasOptions.lua:118>
[string "=[C]"]: in function `Show'
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:457: in function `AddChild'
[string "@Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:1467: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1121>
[string "@Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:1652: in function `FeedGroup'
[string "@Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:1932: in function `Open'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:1024: in function `FillOptions'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:1021: in function <...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1019>
[string "=[C]"]: ?
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Ace3\AceGUI-3.0-41\widgets\AceGUIContainer-TabGroup.lua"]:156: in function `SelectTab'
[string "@Ace3\AceGUI-3.0-41\widgets\AceGUIContainer-TabGroup.lua"]:67: in function <...Ace3\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:64>

Locals:
frame = <unnamed> {
 0 = <userdata>
 obj = <table> {
 }
 height = 107
 backdrop = <unnamed> {
 }
 width = 442
}
self = <table> {
 AceGUIWidgetVersion = 35
 disablebutton = false
 OnRelease = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:197
 label = <unnamed> {
 }
 parent = <table> {
 }
 SetText = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:240
 SetMaxLetters = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:248
 SetNumLines = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:232
 extraButtons = <table> {
 }
 SetDisabled = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:201
 userdata = <table> {
 }
 OnAcquire = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:187
 button = WeakAurasMultiLineEditBox1Button {
 }
 SetCursorPosition = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:282
 base = <table> {
 }
 scrollFrame = WeakAurasMultiLineEditBox1ScrollFrame {
 }
 widgetNum = 1
 type = "WeakAurasMultiLineEditBox"
 scrollBG = <unnamed> {
 }
 DisableButton = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:252
 numlines = 4
 labelHeight = 10
 HighlightText = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:274
 editBox = WeakAurasMultiLineEditBox1Edit {
 }
 GetText = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:244
 GetCursorPosition = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:278
 events = <table> {
 }
 ClearFocus = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:262
 scrollBar = WeakAurasMultiLineEditBox1ScrollFrameScrollBar {
 }
 frame = <unnamed> {
 }
 SetLabel = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:218
 SetFocus = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:267
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = WeakAurasMultiLineEditBox1ExpandButton1 {
 }
 0 = WeakAurasMultiLineEditBox1Button {
 }
}
(for control) = 1
_ = 1
button = WeakAurasMultiLineEditBox1ExpandButton1 {
 0 = <userdata>
 Text = WeakAurasMultiLineEditBox1ExpandButton1Text {
 }
 Right = <unnamed> {
 }
 Middle = <unnamed> {
 }
 Left = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 AceGUIWidgetVersion = 35
 disablebutton = false
 OnRelease = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:197
 label = <unnamed> {
 }
 parent = <table> {
 }
 SetText = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:240
 SetMaxLetters = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:248
 SetNumLines = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:232
 extraButtons = <table> {
 }
 SetDisabled = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:201
 userdata = <table> {
 }
 OnAcquire = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:187
 button = WeakAurasMultiLineEditBox1Button {
 }
 SetCursorPosition = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:282
 base = <table> {
 }
 scrollFrame = Weak

**Comment by fang2hou** [comment]
oops, this is refactor error
