### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by datyin** [fang2hou/ElvUI_WindTools#230]
**Describe the bug**
4x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI_WindTools' tried to call the protected function 'GetPlaystyleString()'.

**To Reproduce**
Open group finder, mouse over groups (fast) error hapends. Possibly bugs out because of high ping

**Screenshots**
![image](https://user-images.githubusercontent.com/6266797/179403808-02e45880-ad1a-4462-aec6-a4fd82d10157.png)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.46
 - ElvUI Version 12.81
 - WoW Build 9.2.5 (90205)

**Comment by fang2hou** [comment]
fixed in 9999720679b094a5dccbf05fac877f3712011312
