### ISSUE TITLE
[Bug] WA Shadows not working since 2.47

### ISSUE THREAD

**Issue by Beet4** [fang2hou/ElvUI_WindTools#231]
**Describe the bug**
Even though checkbox for WeakAuras Shadows are ticked, no WeakAuras have any shadows anymore since the update with setting to disable them.

**To Reproduce**
1. Enable WeakAura Shadows in WindTools settings
2. Reload

**Expected behavior**
Shadows on WeakAuras.

**Screenshots**
![image](https://user-images.githubusercontent.com/38279393/182974561-b34928e6-6d61-4bf0-93dd-be159cc11f0b.png)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.47
 - ElvUI Version 12.81
 - WoW Build 9.2.5 44908

**Additional context**
I've tried to enable only ElvUI, WindTools and Weakauras. The problem persists.

**Comment by fang2hou** [comment]
fixed in cbb0ffc5f7cf781527ecd0f08d44dd6a88e58600
