### ISSUE TITLE
[Bug] Small font on middle top of the ui.

### ISSUE THREAD

**Issue by DimitrisT5** [fang2hou/ElvUI_WindTools#234]
**Describe the bug**
The text in the top middle of the screen displaying messages like ''Can only be used outside'' (red) and quest progression updates (yellow) is too small.

**To Reproduce**
1. Install elvui 12.84
2. Install windtools 2.48

**Expected behavior**
Test should be bigger like in the plain elvui installation without windtools

**Screenshots**
https://ibb.co/nk0JHvh

**Information (you can find these in [WindTools-Information]):**
Wow version 9.2.7
Rest is stated above.

**Additional context**
![Screenshot_1](https://user-images.githubusercontent.com/101137061/189531530-02219e2c-d469-4f54-bca0-5c51d36df301.png)

**Comment by fang2hou** [comment]
It actually handled by WindTools Skins, you can find the option in ElvUI Options - WindTools - Skins - Font
