### ISSUE TITLE
[Bug] Incompatibility with Broker Everything

### ISSUE THREAD

**Issue by thematrixincendies** [fang2hou/ElvUI_WindTools#236]
**Describe the bug**
The Game Bar seems to break when [Broker Everything](https://www.curseforge.com/wow/addons/broker-everything) is enabled and configured in a specific way.

**To Reproduce**
When I create a new char where the Game Bar is enabled and Broker Everything is enabled, too, the Game Bar works. Either adding something from Broker Everything to a data bar or configuring it in a specific way breaks the Game Bar. **I think this is caused by the "System" Module of Broker Everything.**

**Expected behavior**
Game Bar still works with Broker Everything.

**Screenshots**
The Game Bar is shown, but no symbols are loaded you can just see the clock and empty bars next to it.

**Information (you can find these in [WindTools-Information]):**
Happened with every recent version of ElvUI and Windtools, right now reproducable for me with:
 - Windtools 2.51
 - ElvUI 12.91
 - WoW Build 9.2.7 45745
 - Broker Everything 4.4.0-release

There is a LUA error thrown:
```lua
5x ...faceElvUI_WindTools\Modules\Misc\GameBar.lua:735: attempt to call field 'onUpdate' (a nil value)
[string "@ElvUI_WindTools\Modules\Misc\GameBar.lua"]:735: in function `ConstructTimeArea'
[string "@ElvUI_WindTools\Modules\Misc\GameBar.lua"]:1324: in function `Initialize'
[string "@ElvUI_WindTools\Modules\Misc\GameBar.lua"]:1357: in function `ProfileUpdate'
[string "@ElvUI_WindTools\Options\Misc.lua"]:842: in function <ElvUI_WindTools\Options\Misc.lua:840>
[string "=[C]"]: ?
[string "@ElvUI_OptionsUI\Libraries\Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
[string "@ElvUI_OptionsUI\Libraries\Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:880: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:701>
[string "=[C]"]: ?
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Ace3\AceGUI-3.0-41\widgets\AceGUIWidget-CheckBox.lua"]:68: in function <...ns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57>
```

**Additional context**

**Comment by fang2hou** [comment]
Considering of the cost of development, WindTools not support Broker Everything.
