### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by jisamcom** [fang2hou/ElvUI_WindTools#237]
**Describe the bug**
got friend list error when open friend list window

**To Reproduce**
1. click o to open friend list
2. if there's any friend playing call of duty modern warfare 2 ( 2022 )
3. See error

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.52
 - ElvUI Version : 12.91
 - WoW Build 9.2.7

`131x ElvUI_WindTools\Modules\Social\FriendList.lua:412: attempt to index field '?' (a nil value)
[string "@ElvUI_WindTools\Modules\Social\FriendList.lua"]:412: in function <ElvUI_WindTools\Modules\Social\FriendList.lua:266>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `FriendsFrame_UpdateFriendButton'
[string "@FrameXML\FriendsFrame.lua"]:1261: in function `FriendsFrame_UpdateFriends'
[string "@FrameXML\FriendsFrame.lua"]:629: in function `FriendsList_Update'
[string "@FrameXML\FriendsFrame.lua"]:307: in function <FrameXML\FriendsFrame.lua:306>
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:3017: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2862: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2730: in function <FrameXML\UIParent.lua:2726>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3582: in function `ShowUIPanel'
[string "@FrameXML\FriendsFrame.lua"]:1068: in function `ToggleFriendsFrame'
[string "TOGGLESOCIAL"]:1: in function <[string "TOGGLESOCIAL"]:1>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 EnableModule = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 SecureHookScript = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:410
 defaultModuleLibraries = <table> {
 }
 RawHookScript = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:395
 GetName = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 name = "ElvUI_WindTools_FriendList"
 Initialize = <function> defined @ElvUI_WindTools\Modules\Social\FriendList.lua:460
 IsEnabled = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 UpdateFriendButton = <function> defined @ElvUI_WindTools\Modules\Social\FriendList.lua:266
 HookScript = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:366
 IsHooked = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:493
 IsModule = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:217
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:387
 initialized = true
 SetEnabledState = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 Log = <function> defined @ElvUI_WindTools\Core\Functions\Developer.lua:124
 baseName = "ElvUI_WindTools"
 ProfileUpdate = <function> defined @ElvUI_WindTools\Modules\Social\FriendList.lua:471
 hooks = <table> {
 }
 SetDefaultModulePrototype = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 SecureHook = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:336
 IterateModules = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:437
 UnhookAll = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:477
 RawHook = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:313
 Unhook = <function> defined @ElvUI\Libraries\Core\Ace\AceHook-3.0\AceHook-3.0.lua:418
 moduleName = "FriendList"
 defaultModuleState = true
 Disable = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
}
button = FriendsListFrameScrollFrameButton11 {
 0 = <userdata>
 OnEnter = <function> defined @FrameXML\FriendsFrame.lua:1905
 index = 11
 buttonType = 2
 travelPassButton = FriendsListFrameScrollFrameButton11TravelPassButton {
 }
 status = FriendsListFrameScrollFrameButton11Status {
 }
 background = FriendsListFrameScrollFrameButton11Background {
 }
 OnClick = <function> defined @FrameXML\FriendsFrame.lua:2086
 OnLoad = <function> defined @FrameXML\FriendsFrame.lua:1893
 id = 11
 OnLeave = <function> defined @FrameXML\FriendsFrame.lua:2081
 name = FriendsListFrameScrollFrameButton11Name {
 }
 highlight = <unnamed> {
 }
 summonButton = FriendsListFrameScrollFrameButton11SummonButton {
 }
 info = FriendsListFrameScrollFrameButton11Info {
 }
 Favorite = <unnamed> {
 }
 gameIcon = FriendsListFrameScrollFrameButton11GameIcon {
 }
}
game = "AUKS"
realID = "|Kq58|`

**Comment by fang2hou** [comment]
The logic has been rewritten in 10.0 (both Blizzard original friend icon and WindTools module), if you met the problem again, mention me.
