### ISSUE TITLE
[Bug]Weakauras Options loading on login with Windtools enabled

### ISSUE THREAD

**Issue by Xzsyn** [fang2hou/ElvUI_WindTools#240]
Basically, as the title says, WA Options loads on login. Some WA stratas also are wrong after entering the game and need to be fixed manually after every login. Both issues disappear after disabling WIndtools.

It seems that the skins module attempts to skin Weakauras and Weakauras Options even if disabled. It doesn't actually skin them, though. I disabled both the addons skins module as well as the full Skins modules, and nothing changed. Resetting the addon yielded the same result. Tried a clean install of ElvUI and Windtools as well, but the issue re-appeared as soon as I enabled Weakauras, even though I disabled the skins module before enabling WA.

 - Addon Version: [2.58]
 - ElvUI Version [12.98]
 - WoW Build [10.0.0 (45366) x64]

**Comment by fang2hou** [comment]
cannot reproduce the bug.
make sure you only enable elvui, elvui_windtools & weakauras these **THREE** addons.

**Comment by fang2hou** [comment]
you can also provide the details of your weakauras version, and the wa strings.
it works perfectly with my all auras.

**Comment by Xzsyn** [comment]
Yes, I did test with only those three addons enabled, and the problem still appeared. The biggest issue comes from WA Options loading on login, which comes from Windtools as it stopped happening as soon as I disabled it. It's not a huge deal but could be annoying if DC'ing in a raid and having to re-log quickly.

For the WA string:

> !WA:2!TR1AWTX11zcdlRyy3ikkzwjkjlyAzgszvsrsrQhjs0aKGIq8bGwcsABjBS7I9cSReWURU7cscg7PomoQQ1XnPm(zRBSctIBQDM6w0oPpsBSTCFK0MuFkB6ufN2kfM0mUPt60QP)OT)X9(yx8IG0Is2sTEmNHa7E3Z9S375EoFNxWZ41zj0vR7U1UQltDk1PCMBFbzPeNubBy2RrAd8r861BuVKhBwxcdDBSr60iLEv1sRGr6NyXOPLYHWrnW2yjn7ZjOPNYkoFWf4FfFaKuAB1lftcNczhVcs5JUGZd5KUOSbwbHd6SmmRnyATzMrcR4pMHrABnZfKYARAGJyARzOB5tMtV688VdPKczU(rpvwjmYF)ztN2)eQA2O5XOueYJLZejKcBK10H8r1MbTM5TnsmjcBriytEo9zZZFexa4XJhVNJpqKKjTq23mEA(fEWsjylHUfSSLW2(cQPRz7toj5llvFZAJ1sLIW1gAc7C5PNxbjNnzs6QapqOHI2)ydf0MUKKYIL6ywltu60HvS8TOvwz0KiD7rjuRnD(49gy0yXhnwaHybZsEjYMmHBbYIIreYegnAOHgsGnImxykOlLbz5BUS6olbF4CoR(lPPBJW6sPhNVZNkVKEcICnQb5bY9gAKyHeMZcLojBaOTg1u6ia22r4ewNWdV5tIj8FuYrQTK3lXNF)0HO7q5r7viuOrcM2qsP)GwebD9czYsob9fKSrtupSpFcjslzzrVs2wknzzZUKOPLulLpbReKX8opztkWo8S81rwnL85cApEhHpYu7j8yZtivrJRhKxtpPboJe9oFZjPRXVSByt9dBpOUHo6Cijl6IfPNYwDTlOqK5ukItpbWwikVSMLsdD1d9fmJKMozUqFqO1c9dhggGCzdvosDj(jNPz5PKszeUV5Sh5EvYKn3Eoju)dDtWU8cTcT1rwCAZTOABBADG2AJsyRAgTvGY26e(zjlsFqd(Gn3KCISw2gzmVZqPNCSWXdkH7(aJIS7VOCU5ghouFHhB4gBzofJ4CYvHT8HBc26zQnp)E2wsMOvAN1ISChzXSwO4sYwgy5HnuqI4S6mTKGetjdyN(M1vwux7qZqlWoG7cAc(iWiMVyYS6mT8MBXNFYFPnihk(P6G(pO)g5QHnYEc7dYs11epMrm002zXOMPk3Xr6t2k3gSvB(4TSKzSY0Vl2RTLIVmmImSUFBCwKpKUc3uWYClJns4yXJgriMqaYfJfTVaXcDa(sfUdIoNkkXjHMNLktOCueAeUtyBWTd3TpZ1tTPNefJBTqfwF1AGFUPGEz6rKtD6HVRUq4LmsdvocXI3ICkqKUivZ1ROzLGSQrXXg2m5ThSdUZAHd1q9W2xGOStbGPquKDKkslLQTLmJCKk09tTaDvBISLLSTtJuNJEl9SeRcFuQXtE6atIu1sqEkSF6qluYqJPPc7LoiCa6N4ziMfeaNB4soY4jWsM0nTqVdfy4OefMS4eizTmMKJi5mAySbw1S2sm0zFSWOJ1)yejPJmUwSd3MtMytRW4xWHcnsFePBXzgLaqRBRcgMDhMIeLukb64buuIOBD8jqsNmarOzD8HrkAsh3rZW649QHj7I4miDztghG2HB1NSfkdrii0oXvwhWgOO4e8k4gfs46fZRGuAtvjVctPPyRAb9K)ei1(Bovx77Khvc(y(MTWrc0Pxyp5hn0qH6nw)cbgoeeWheSP8e0LeOqmDmrZnPLs3aJCCcXgnev6yjc7gA7m3b49iM3MJlWGmeZ4rYs2L3)9BUHYhoSUocxjTbsKGWX2R(WDa(GBHSPDWxGnYCsvckIpylnqGdontPE7GFIwpth31SMAIVtFe19RgnB4q(GU7NR1Xv046uo6x3qHqhGtaNeoOx4Nrf(WW6GAH1d1Tg42U5IhtRbYyUPcN5hO8OkGoxdSh4HG6)2EjhAAtePzLOsD1D7Jtf0qhEjNDSdiFarv4mnbhzUC9hC)2Xdp0aq95GD5HjJgAPiWfiRT9xUSJcL(1iB1DWHntpLuolkidhOyurOzZnsv393RQengaewZYwlHft(se1urmr8Emrhqf44RegYzQtMPKk4vM5WBAV87d489H9srWz0sMdNMCEHP9mh7XmFvJuxop1nThq2ddqG9av(Z7NGFB()uvuCMZxcmoXjpkHDZDSl)0DvV0rB2fAVf(e0s6qTTksNnsfSH)oPCJa62xCc8XOJgV3idfry0JXi4bkmlxE5oLYyzj46LsuR4Dv(9PQ4E5cCGG44Z9BY)u594n2(U5cZGERII8dOcFCpq8nWHGbrq6vazrO7VgKqfuCawbcCkv)EC5bgJgAKy((cnCKrCUbhnWqb6l8iIYJoqGHdq(oQq4qJgtKFEqxPQqsvi1nSiFzlPReNgfutYwKiHtJ2rTW((XFkr7AfF0Af)URt8Xf34oevQv8)CDI7OwXBSwXnwR4Num2oe)rRt0XAJBNPAUrgwDSibhkqVdgOV(chl84HygDPvjwBgGjCkck7EV8rzPbNhV9DBoDR2PKiMvRHzQLLHUUVIMT)8W0rVXD3ANDXqmHUGPyaTeR0MNoDIbJC0UcQ0jK7vOwOe0QaVztW93pSvVZoPewtI4BaoGWKsPZIiIYaXgyWrcF4bI1OHzJh8G4eQs6PqKyNHZEKb65TEMN5vRPMAgONVXTF73tn14DGE(oBBBKl84DwtsociSDoykhUdppCa4SWtWzemVdl(r22pcJfFZnTP7HDX)Y(3Vi5cVWxSS56mVZk0NWyH7Zz(K34f2(25Z7lTXn6VkZdoRCOXJmyiHkEXFRN9zFL3(TF7b6zrmMVcUWfUyn01(Y8IHpxH5(pp2yISP8tMzMZYU4F45EUxTkZfoBWHdC4qv8QFJN)55V636)6)2pB6)0h(Hp7kSNds0Oh0z6Ei75F4g2q13QWtw2RQuXZp9bEGhzfEfWt7ohQQsL8vqiYHhluL8(F7Z)55h)VzdnCpReVFk31orqT1TYxp)RF9V(fxH5GNiGWqr6DWccTl(V)FudBI)G1VEhH2)4)unVdCqiCeHcC4To)3JZHFOLf)e)7FSJvqMabRhEyr4b9CMpcCe4tr8rnppODQ5xJ(8vWJfC6LXTe8lu0teCM3jVout3LIW9YRach85eHNqeEsr4PeHNweEghOl4zBc(vVYbQGFTREqPoCbLEqpuiLSWVEr4OhHHuvakIftup5pvIHW3)HN8KJmkgY9YuOOP9YIxGDkSCUKHFrVWVKx4X8cF6YC)cpo1Zl8lxIhx4ZOcFw4xX1pdmxvCXqdlHDu)U9H7YS(VnY6FEQNh3ehORS553qdyywlAOvKulOBVhJVdDNT8JwpFxs2EKnjDVs3IePbzx6WdwqfdwiOccgCkYrK1U8ZkeYU8RGsBl1sPjPXEG)72FbA9VtxQOoQPsnYUO6(MJuMM7RFDxZTdIt2LO7AuMUBuJPqy2LCTy(O0pBV7Ioulv79tq1lR0p6mHL7QZtC09MnRaK71R0pQdu8xOcu)L3z5sHXVQ9scFPvJhs4lF9X5i8cxTEgHFJRNUfHVY1sxIWV5vUZq4fx1UbVoGnc)wCir4LHF7vlei87a5xr4QJDzNkX1ihT)UKp)9QoQZSvf1zOteyOwgEcSAGQe9(hG68bOoVpa1PDSrw70A6iCKXInu4rcz2GIMfTQh0ioJZBLqCDE9fiw22q75lHGgVReWlnTNBPQfwr10)bz1sH3eMIftPeAYubrdlnDf0PLKYOdDq)TVB2FScLumEkmjE4w5lZMB8UAV1KnUlk9T5sEl(BTv)nomV48O0wOY43QHzConyro5opvZsR0YcwQskgtDF8(lT1AOG5M3zvfQsYYy0KAKijJNrA61z6Vkuzg3wldY5opM1wmjPXmviZeAErA3lOD5jXe0A6gmaTzgv3ZHzDf7acvEZ6csP(sOorUdMteQxfI7KI(smBC5xDzmuItRTViltl5GrIflYWbtAOBpRokl2W0q2Clvz6jCUGOy194fDmCGskMkdmFwkRO9OCBMBVQssmzZKjoTlFcS2au13MUZfbPQBoht3l)yYRRNQQortNleOBwfidOd1gKwCFsguMnT8IL0OusjYfpzAddSQRJL6tr8TO2B490X(os4bUpLQQB4WatmkHgTViEHD9PRX8UxEkvYr28AjIBRsYQq1iTso8jiAkAjZrsk)WdeROVUBA2PmWk0oCm7eoxWD99qu)BeVCeNMlJuUO(QyEU4RqZHhONx7Z(0uFhZNuBAKctt8rVvA5OVslS(zAHeq0Guah4Lm7RiaZQQvznAZ6PEJTqToDBuWqWWm7JUHrm7AvXnxGP5vmINHK9MuksmmrvDTZEqID2pMfH25kpcnz(YGAEjGPv0RUDtmZyffLDRi1IBN(wKDtCAL8KSnWnEOd6y)r47l4YxkpZlqj0FVSw4Td4cWpqLYHlsJLBXItJIuFcMGBsuhsPtVYHeEz0RdsCDpOhi(AHdTtM1YzUnZntLoXTRIzg03CfEgXpHzTS7QqVX7I8rDBWEWaJflI5gydwoUg8AxI)wkOF9jQYlViIY5yd7yeaT5M2pzWGJezKqW2XwzLP0mpJWIDiBoh(PBBwB)yTz8F0Ssk0wo7pwmZ6kztuaIFb2GUMvW5xOahOvzi4ig6iNDFj)2cMNJsouO(JXxQtsS0LtJel7D4IpvKLuyWnVaNrop1JZTolipGKfiRcDFAh8uEq3KyQD7fkdHTjAC3VO4sdxoJBJmD0ADRtfwCjDP8YnD)oDr)yvRAYIOrRfQ)nObFtHFYzrHF6jF00JCKy566WPZna05TWIwpqd8WDwdjCNlcNTX9SBAmphYjMmE)1(IW0oX18X9W784gC(f1uANhRCqN(ow(Gf67y1gM33rAF4QwJh3mZR7Y34rIpvAFhPoAlTXJv8ZRi878p4cNgpU3L04Xp6Y34XmMBUy)fR43Iu16i5hI1QsNopY9oqpn6jFQXI0R(mhvDWm20EpwwJhjzXERvP8TocMLpl2l4MfldlSQzXwPuQqfkNRSkusYJLxGYpJQBERULLKM5QmRKLuMSuH6QRjyvpZ1spsQwkSBKLSkjLvsoSFsNuyj5YssQ9XfPP9wTsedphf51XiQ0CxpVhwMRUTGIKOAp5Lr72(Kzto(OM9spYOz1wFoYXZhQ80xlK2Wx4AB6R0exx2u1wM0xlSw)YR(0xPjUwXATkPVE8JVIPi(cR(0xPjUw27DfsFTW75jV8tFLM4A5YXLM(Ab((vU8tFLM4A5R73BtFLM4ALLr5Yj9v6VWeEZJCAZXlv1(gD1b88UvFJEpbu4RwLgaDEp3iZuN4un3lt78ZPg8(IqWP3RWmLag05s6(Z75yRxR9nuwfo5BcADo3oFftPHwcZk7Kfzd70jlA5pPC7X8Um(jUABiZ76Qe8kCUC(jynfKQv86eTIPuuNbDcvR7DC9vYfXvtfolaj8eVFXfr1RW5vJlIvtfoVsCruwfoR)6KVbQxHkeUxt8n8(n8MJ9)1IlDLXBUjx8gAiPzMix7tFcHGr33()a8MpaV59L4nTd)(WFa8hY7sc8hT66nIBHkFN6nsz09)36nc8hZ7hc8NSf4B4bEfcA7RcV2Y1M7ZTSTM4cvak)6IWFJ6vEzn)ZG)8c4QRyFiGV52GVf8xc)vW3g(oEjh6)PWFn8gqMZ7PgcKiqdPM4FG4XP(pgTdYMNsBpi5Wr7m7eWFlRe(W3nh83fKwZVIfz5MH)E48ULG3bjLxgE47jcVzzvxh((8IQ)xa9v3K34d))(

In Rings_Target > Target_Border_Inner appears on top of Target_Portrait on login with Windtools enabled. Issue doesn't appear as soon as disabled.

**Comment by fang2hou** [comment]
It works perfectly in my game. maybe you can provide some screenshots of your problem.

**Comment by fang2hou** [comment]
because I have no memory of writing the code to open weakauras, I even don't know how to do it actually.

**Comment by fang2hou** [comment]
considering of the complexity of this issue, please go discord.

**Comment by Xzsyn** [comment]
Sure, will do it tomorrow. Re-trying a clean install with Cvars and WTF. If the problem persists, I'll contact you on Discord. Thanks for your time.

**Comment by fang2hou** [comment]
The reason of this bug should be WeakAuras_Options is an optional dependency of WindTools.

And actually load WeakAuras Options do not spend so many resources.
There is a normal misunderstanding fact is addon memory affect the game a lot. Actually, compared with memory usage, the cpu usage is more relative to the resources.

You can check CPU usage with ElvUI datatext (system information).

Here is the normal state when you open WeakAuras Options GUI and do some import/export.
![image](https://user-images.githubusercontent.com/6694722/199278369-9e4f17e4-1ca2-40bd-b1ec-8ff2da7020db.png)

But if you reload the UI, and never open the WA Options, the usage is very small.
![image](https://user-images.githubusercontent.com/6694722/199278649-355b942b-ba29-447c-821d-e3c65e59d8fd.png)

The memory usage looks high because WeakAuras Options regesitered many widgets for providing amazing configuations. That widgets will be load to memory when you login, but the functions and widgets only in memory, and actually not cost your cpu resource. Once you open the WeakAuras Options, it will generate a GUI window, and the resource will be cost since this time. Besides, WindTools also skin the options in this generation process.

When you load WindTools, blizzard will look up dependencies and optional dependencies, and load them before this addon. WindTools need make sure the order is WeakAuras Options -> WindTools. And if WindTools loads before the options, the skin will be replaced by WerakAuras defaults.

WeakAuras team hate the skins, so WindTools skin is very tricky and hack the registered widgets, that's why the order is so important.

**Comment by fang2hou** [comment]
and 10 minutes after, options still has low CPU usage.
![image](https://user-images.githubusercontent.com/6694722/199282021-701d3701-750a-43c4-8053-89127466e0c5.png)

**Comment by fang2hou** [comment]
https://github.com/fang2hou/ElvUI_WindTools/blob/60a797453f2bd4b2aaf5d0bc5c56da6b84c7e0cb/ElvUI_WindTools.toc#L14
