### ISSUE TITLE
Unable to click Extra Item Bar items.

### ISSUE THREAD

**Issue by Lejes9X** [fang2hou/ElvUI_WindTools#241]
Even with the recent update to WindTools, I have been unable to click on the items on the Extra Item Bars. Tried with just WindTools and Elvui and it was still a no go.

The openables and consumables are usable in my bars but not on the bars.

**Comment by fang2hou** [comment]
It is a bug from Blizzard, and there is a temporary fix for it added in 2.55.
Please read the changelog before using this addon.

Change the option in ElvUI Options - WindTools - Information - Help - Button Fix, and then reload the ui.

**Comment by Viper3881** [comment]
I can confirm that it used to work on the other 37 classes I leveled before the pre-patch and yes, I only used Elvui and Windtools to test this specific NPC that worked before and doesn't now. It happens to ALL NPC's like this. I love everything about the Windtools addon and for me this seems like the one that doesn't work right.

https://imgur.com/DTJBOhk
