### ISSUE TITLE
Smart Chat

### ISSUE THREAD

**Issue by Viper3881** [fang2hou/ElvUI_WindTools#243]
**Describe the bug**
"Smart Chat"

I can confirm that it used to work on the other 37 classes I leveled before the pre-patch and yes, I only used Elvui and Windtools to test this specific NPC that worked before and doesn't now. It happens to ALL NPC's like this. I love everything about the Windtools add-on and for me this seems like the one that doesn't work right.

I have nothing in the ignore list. Even tried a fresh install of WT and Default Elvui.

https://imgur.com/DTJBOhk

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.59
 - ElvUI Version 12.99
 - WoW Build 10.0

![DTJBOhk](https://user-images.githubusercontent.com/113194527/199809887-2af30aff-89f1-4045-9c4d-120c50408600.png)

**Comment by fang2hou** [comment]
fixed in d7e6be50c74dfe0e5ecd8705171241363252c89c
