### ISSUE TITLE
Nothing happens when clicking on icons on the gamebar or on the item bars

### ISSUE THREAD

**Issue by bguende** [fang2hou/ElvUI_WindTools#244]
As described, I can see the tooltips of icons on the gamebar, but nothing happens, not even an error, when I click on the icons. None of them, except time, which shows calendar and stopwatch.
Same thing for item bars.
I use french client.

**Comment by RodiakWolfshain** [comment]
I can second this issue. Used german client.

**Comment by fang2hou** [comment]
@bguende @RodiakWolfshain Just read the changelogs, it is blizzard's fault.
