### ISSUE TITLE
[Bug] game freezes every 5 seconds

### ISSUE THREAD

**Issue by jisamcom** [fang2hou/ElvUI_WindTools#245]
**Describe the bug**

**To Reproduce**
1. in dungeon, i have no idea what causes freeze, but once it started, game freezes every 5 seconds.
2. especially, fights with Feasting Skycremer in atal'dazar / pack before Priestess Alun'za 

**Information (you can find these in [WindTools-Information]):**
 - Addon Version:  2.60
 - ElvUI Version: 12.99
 - WoW Build 10.0.0 [46455]

if i turn off windtools, no freezing....

here is my profile. just in case you wanna test it. ( i don't use every feature of windtools ) 

`AzkXAwC0pKjXJJmJgmZT3ESqjBtV3EY4TLVTVGmv2i3sJ6Gfosh08JvUM6RiKJKqwZRoOCUdREoGJZWOIaWOIwULSbQURS2WLEf1EIU8JR6j9FxkQ1JoqtRkkvo0ivouCleRJJeh60hsRJHTiDaTYDsKLBNVeZ0kfEaqml0J40XldpLUaEr9SlI6iULNSRJdE1V1XpTuJCnWIkUGJKk87XvxCE0JFgkMuBewPVSJSXNmTBTOkQVSx71geBm8hoXVRDkwY6JwjiyQOu4Fw8vgNSxkAHJOscK9YHgZvIYFw8vgtYDN0aG5R1JAfi8YXgavYaGvtbqyeC8YXgavYVgIt6Z7ybA1I0OyKlTfC4aXwWsYFhKQuBc1GgS8FwXSGMax0KKqMw0L5oA7Y0AiKZ3fC4aXwWtYgLsa7wVsD1VSUgB0XAvYHqrUmIOlbQ+VomVWU4aFjGRFFu7FIAM0jTm4l3ACF9r56DAzDcOwEGRi74W+E6h0fi8YXgavpZxVqbm2XsOwJM2Sbu5FgZMYaoZkgnsJJ5BJB9xLOIELTTpc0ZJ6rhUtlcNChoJm0gH3Ek7gYkElXapppGtBDc1UUJvHIjN1w7AgoQHvBcPL4DUsrA7AHNDDoNyLc0Lz7LVwtGoOAg7pGhbWdmjMwb1wJDQDZEY3xDUsrO2gdH4vGF4Gr2FJhHNor3uxyQSaZxmSBAnnzU9nybDJZEXOKMsaXDkMCw0UTHAvKYME1lZSAHSke8HwMngNw8JqohzuhdVEOdAyyOFeMLwMXsPCnVTTc65Cnu4Fw8vgNQzDAw=={}A2ODEwB5VVhPkPkK0H4CA4aSMmEBjZikYMVSZEghsWQpacpS1JZJSjVnkpJGSVLKoAXqlFASowpVsySpaFih1C1JikybpKpdSqnGFRTmDaJhhHBMRcsk8kyiphGSrhGUtimKbwSVcUrBOaHSOgXQ6kJq9lD1eoWeQt+F4qck+TJJJU8mKXFQgSwkeqiCJgrCRQW1UUF8VJAaKZQ6KUgrJSnqJUHVTEJ0U1B2CtxZkAwVVEclqbKUUFxaSnyapFJXFaWtQkn1VSk0VpJCZyWp8GwF1gol6cpQ8aJQ2Yv+KgCDVemw1GJVPVZpsiKXKZtV0WeFRivVaZLVhJLXkphN1W0hu4HfoOESjgslllN5Tmq66Lqktiuq20sp4wmKpiqZJxcxUvpyESM4t2E/nw2VPWpKIoDCNxBLhXXu/MTsUVMSIzg3LMwmfuLTdWThUKtUEGguJlFXVHFYJ14Dxk/0z1Gk0slFNNDfGyXRK2BcxN3UuCeDMhE+n9qyGhmIIBro742SmCZM4kYFpgWh14J3aA9jiPD51JbVwaCaTmL7Ym8GJzFGTbkzOGeYRHUh4CIWfStErN7sIDHDRGe6ogAlsX2xN4OT+KGbzPETtRIyBucMk0nsOiFeZwb0DpOfGNVpXMQI1iC5GJRKccsbhOVnMFMWLu4MP4NyOa6wGzbwMyifJeFmSvxMooH+3viJMHdzXMQFXULvG/ATMYJ+Mrdbu+RnMonOIou+uXCoVSoIND8xgnOTXgkJtZuGuI5MUxKLrrUtiL71TskkRl1oLqICOhtcC6GeT3Vrnw8uooH+3iiJTwiSi6jz4Y1YNbtEhgbDRNCREY8Dt8RvEi94t20VdzwIKXhFHww+bo4jeCVRKyFjcJaYxPZqBESRw0MWcVeTSa+EhNpNlEyirgtzy/WtmOMiAihSRSr5iZPS2eDaMmEmFxEC/wjq6JvjJ4KOjHgcuCV+k3jBu22ruONBSMEr+mDwcXMcwSuJBvp7oyRe6KHjIn4GJ3FkcBIdg5NJ1PnwRqyaXSJDg2GiVkLG4BSVSew64XJ9Kxv7UUAFkpJooL83SqJT456HXt3Kgofe2lEyiZECKupC1pkQaC7irzMhQCVkDMoiiAb6e+Mn/r6VycGCkhjBWlvV3Bw/8bY3MLXjJyowN6cthHJ2U0HAT9RFXwVGBiUidMpAdioIiLGrxITGalWwBokk/joTAh1uTgyMYTBD/H0rk4MFFn0VGBmUiWM7pzQE/ExiDHR+CuuCi6hve+MiGujvjZ+olZAxOLeXRGUSDfT3Rkl0Nrf2XMRa2yH00PETDfT3Rkm80EPHRWwGJ/EzOIkjg5PoGJxMJpNJTAh9qkJzEScYKdCpIBDToEJJhF8su6nmFu7g6EzrQffWru+DwUksHBydaa0g4CIa6O+NkuhaTZqLaKC/N0riYev0JniDzt2ppiRig5t1JHjhU/CGgJECnQoCSiYxeuSubogajAaB5iKGMMFblbs5wYtqMkpi7PZeC174FLyDEgKLDCQl0UB/b5RELJQzLXjhU/AO0teAVhBQErHBWCtggjeEFblrSuLaTfAGdh1MdQXvxq4YJTHc91jbs72nJK4W6rnpvToFb+4meGPdlLdJ8Ia1q1hSEtduneYEL3wK3vBWgJIYpnRqwQufgncpB1rw4lW5GyWTqAu7qj0X0UB/b5RE3HuCMb7BpAWv8PbQCYEJ3rDWaW6AghetNQSCtwoYJRH3nmCMbzBpwSu8PXRCYII3rHWaG6DgRWsNgeBdMZCSySSqCwElEX6x7KaaW7iDozOtKZnEGqgc4joyzUV00FvohYCLaKC/N0qig95CLwSYD29EnA1mQ5nEWGp1K0PgrTUX0UB/b/zEX2dCQJSza1UFJzGCk3oqc0S9q2cymcQLnXERL4yKTvWVV/k43O1WKIkejgqEmdY9GiVxsl+PYXAyfiZRVxTQXES99wRj+Ik9TRBoLmJfK1MSY6wrg2rXuqpIBYGmJEYP7WFSEp1FnXenJLaQOZj7oDphuPIwKYmFs6gnG9rButBDlE9zlERne98KJXG3ivKKkvjVuFGNmpL41bhRjbp6tdW2VGSOkhhjXRlUu9b8RBVF5rSCgJIYPXJXN0QNRoNgQeg1JTEySwVGTAiMkpgKPEKBLuwmJfHXI/atUBIbjO4hvD10QmCakkk00N8bJVGB66y1TaiEjIEIooqMi3gbTGrqNC6izoc3YtXsEhkaDBNBR0Y8DtwSv0m84N22VdzxIKTgFX0w+Lg5juCVRK2EjMFZYhJ9f/NcRJ0Pb8Sq2SUyNBgmgo6MGAZBanOuU/BWm4FYIWolZAxOUZlMovl5rbiIU2fLdpqSGCmgwrqgJF7fWst2mpL4e9SUxIRpkWxHSezataYk3r3zEBaPIa4joyTevTNEZ4c3MK8pibd1ynaaktg3FQSynZZ1JgSURFikgoCSWDQwrymJBvp7oyTevTO8gXlNSZw6O7yBeU1JdK2m2VRe5YOS2D7DYYw52Y6SqLNT3XBY1AUlUWdnrcVYAV1SEvtZoSTWQOUQ15FpSmLfVBDIdlr2rUwOFpRM4vdKSKjdxEVUoKgzzHKH0/CkEjpKYqT0pSR+r4SE2k1VRSoINCUxIfSpCk1JTBVZWIMezVESvwKTAiMl0UOYlMQL5wYaZLizubIYSqICurCblMTf7pvDHRaUxLFWfpINKpTEsZ1TGgJKYoxZxT/EWEy7SVMSXaspFDwhJbGnCYKwBj2aoySm68koiZG5uzdISqKuv75OFakgCAVpTqdK1Z6SmO0rCoyxrSdK4mS/HheEXlMS25tLTUm8cG6gQYoxAGMAJfH7vpWwdhVLSmLXNxUEsWGtjZJY+H6YO9yhukZJTNeTYUV5T0nsaW4ga2dhXVASo1aekvj0atwzrAtK4oXe200FgaYk6uu6KBQYw/ruChglMVLXQVlnQqApiS1kTqVREjWs/Vdg0pTEFjKn0sSYLuxSEu/uYKRsqcgoiVFfBymJ8ItlN9XclutbMUdJvHBuoEFig5t1REk0cGEN0lw1w9qB9pTEC6OoBiqVaUpiC5lTacNaG7hGSWygog6h5ua0goCSePcGwLymJBro742SmHVCp9pTEtO1AuYoidneQFISb3sDUztK4m6+oCTGQOensC4oiSPUWhWUxEg5B91SkTlNSYylNp2URF2Y9xLCCiXR5gZyub5GSYxp92G7iZII3WQudntPSZycaa3AKAbCiJKor4F2ClISC0vZmd4oiR7CigLjEOiGdrAuKIl3b9c3zVESn04ZmDQlMVuYipJ49/bewGiakqizU91wWNQFJbHvrmxukYHUlEQPta56HkKQDnpKYrtUz75JSRxr5SdKJjFGgSkh9JqSeKGHjov4GYggjgxEEB0DEUyiOQddmGndo3ERdT68Eatml8jQYJgIOjLiceCW+E3iBe+2reKOByEFr+iDwcfNcQSvJGolZAxOYZlEZxGcW3i7u0cGkpIYmevclVd6NhQrClAyiRpe1Z6LqKN2ufpzEWN2pQtzq91oqbmIAwofyzkzYIWLwcngnCkLd55xz1JcBiWiDAawMXYohg+LYRIHFD4W4UQMWOFicDI4Z8rCnWfc0swGBiWiDAawMXYohg+LYTKZTGIstenkIsIvlt1Uc1uub8UcF9FAf2/8xN16MsdF1PnwRqyaXSJDg2Gi3qHL2NaTOUoi6MiIx4Fb4jeJF7zbtoo7HoQUvKIPBh83xxG8kqiVkDE4RWUSL/TQPWsf7uDoTGtKYqr0xkXU+fBGrJpdIkODYSLoyIjHgVviN4kXvNu2ijsehBS8og8GHzfHEbySqJWQMTjLTGKq9HYIPXRcRAP9vVESb60TRofQQxdbjbtX455cxM9AxPa4G0QljgxEbN8gbFyiYyBie2lDiUm8vrU+hB46fuKtdcLoEHroAuii9lzEz+AkjgxEbJ8RNi7RMRDBZBIVeEIuos6HN2LV7BIZGgwTQUdGPA7cEr9JvODdtlXc8SCk4BV9MPi4OY7glUSthIzBeTKJF3ronrUPN3cNZI/GTwQwROudkliYuwayR+NnMokXRr+Ti5jtDWRYgx7NcRGLebHaG0h+os7OWodeCCiJKi2SdSYEmpJooL83SqK21FwMSjMzXAxOLmK2N5CYToGRWD7L5VK5RNSWQUdGPIoTHz9USGIxL1Z7A7n6e+NnMihxEbO9gcR0CozE8yydpbNE1JZBR0YULXac+DgD46s71ojFvFjtDeTq742fyWRQmhGOi8HJRcz2BhLTKTASz7NcLpXKRG0ZdGTEeFFEES0MsYnFvFjtDeTq742fyaDERcz2BhLTKTASz7NcLp1lorYMOjLicXA1xA9V/WO1VOv2ozjx8UOFJBbzYrU3kKu/N34mgzIXMdsbSEynwEg8y+VyqVQmasugIyPGiyKKaGGIvT2+2qsfX11iE4t5sdobyNXfGz+TyaA0IywXg5OLmO0NJKZTYCSWz/JZKpWJ2jLoyIjxoogiWhhiE4t5sdobyNXfGz+TQYmLmO0NJKZTYCSWy+VSqVQmasugIyMexYmPHyoksZgXq72BXP298TOZTCaTSQI=`

**Comment by fang2hou** [comment]
I cannot reproduce the problem.
Please make sure the testing with only elvui and windtools enabled.
you can use `/wtdebug on` to start a test.
