### ISSUE TITLE
Raid Marking Bar nor Game Bar buttons not working?

### ISSUE THREAD

**Issue by Rawrjay** [fang2hou/ElvUI_WindTools#246]
Both the Game Bar buttons as well as Raid/World Marker buttons aren't working. I've tried messing with some of the code and it's got something to do with how the API handles the clicking of buttons on addons, but I don't know enough to get it working again.

Just posting here since I'm not noticing anyone else talk about it.

Other addons are seeing the same issues though, buttons being clicked are broken, something with Blizzard changing the API I assume.

**Comment by fang2hou** [comment]
Please read the recent changelogs, already remind this multiple times in changelogs.

**Comment by Rawrjay** [comment]
> Please read the recent changelogs, already remind this multiple times in changelogs.

There is nothing in the Changelogs about this, anywhere.

**Comment by fang2hou** [comment]
check in-game 2.59 changelog, important.

https://github.com/fang2hou/ElvUI_WindTools/blob/619468c48476a4d0972aa04492b3282fe60960a1/Core/Changelog/Previous/2.59.lua#L13

**Comment by Rawrjay** [comment]
> check in-game 2.59 changelog, important.
> 
> https://github.com/fang2hou/ElvUI_WindTools/blob/619468c48476a4d0972aa04492b3282fe60960a1/Core/Changelog/Previous/2.59.lua#L13

Okay, so on an old build you added an option to fix Game Bar clicks, but world markers still don't work on the Raid Marker Bar, aka the Shift + Click to add world marker doesn't work. Even with the "fix" enabled.

**Comment by fang2hou** [comment]
> > check in-game 2.59 changelog, important.
> > https://github.com/fang2hou/ElvUI_WindTools/blob/619468c48476a4d0972aa04492b3282fe60960a1/Core/Changelog/Previous/2.59.lua#L13
> 
> Okay, so on an old build you added an option to fix Game Bar clicks, but world markers still don't work on the Raid Marker Bar, aka the Shift + Click to add world marker doesn't work. Even with the "fix" enabled.

Because you are not in party, Blizzard do not allow you to set world marker when you solo
