### ISSUE TITLE
[Bug] Minimap icon bar

### ISSUE THREAD

**Issue by bguende** [fang2hou/ElvUI_WindTools#247]
**Describe the bug**
When I hover the first or last icon on the minimap button bar, there is no tooltip.
When I click on the first or last icon of the minimap button bar, both first and last button disapear.

**Screenshots**
![image](https://user-images.githubusercontent.com/69540453/200694339-d9ef3a71-78fe-478a-aafe-30470e4b1046.png)
![image](https://user-images.githubusercontent.com/69540453/200694368-b3f97af2-4544-4f78-bc91-5f92822599d9.png)
![image](https://user-images.githubusercontent.com/69540453/200694384-5208245b-7865-47e8-bf34-898bc4e8c315.png)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.61
 - ElvUI Version 12.99
 - WoW Build 10.0

**Comment by fang2hou** [comment]
can you test it only with elvui, windtools, weakaura, bagsack?

**Comment by bguende** [comment]
There is no error with those addons only. 
But if I activate a 3rd icon, the bug happens sometimes again. Tested with:
- AstralKeys - bug
- Altoholic - bug
- All the things - bug
- Mythic dungeon tools - no bug
- Loggerhead - no bug
The only addons that cause a bug starts with an A, maybe it's a lead?
Note that the issue seems to happen only when I put the bar over the minimap. If I move the bar outside of the minimap, the icons behave correctly.

**Comment by bguende** [comment]
The bug seems to have disapeared in version 2.62.
I had no occurence of the bug since the update today.

**Comment by fang2hou** [comment]
Did you meet this problem in ElvUI 13.01 + ElvUI_WindTools 3.01?

**Comment by bguende** [comment]
Yes, the problem is still there
