### ISSUE TITLE
[Bug] Game bar buttons don't work

### ISSUE THREAD

**Issue by sweetjukes** [fang2hou/ElvUI_WindTools#249]
**Describe the bug**
Game bar buttons don't work

**To Reproduce**
1. Click any button on the Game Bar
2. They just don't work, but gives no error

**Expected behavior**
Buttons should work

**Screenshots**
![image](https://user-images.githubusercontent.com/27233569/201124694-bd6e06f5-af00-44dc-be17-5fa5578e7852.png)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.61
 - ElvUI Version 13.00
 - WoW Build 10.0.0 (46549)

**Additional context**
Tried with just running ElvUI and Windtools.

**Comment by fang2hou** [comment]
read in-game changelog.

**Comment by sweetjukes** [comment]
Are you saying it's just not the right version for the live game?
