### ISSUE TITLE
[Bug]Game Bar

### ISSUE THREAD

**Issue by Gennoken** [fang2hou/ElvUI_WindTools#250]
**Describe the bug**
Nothing happen when clicking icons on the Game Bar, aside from Time, witch point to calendar.

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 2.61
 - ElvUI Version: 13.00
 - WoW Build: 10.0.0

**Comment by fang2hou** [comment]
First, please try [`3.01`](https://github.com/fang2hou/ElvUI_WindTools/releases/tag/3.01).
If you have same problem in 3.01, reopen this issue.
