### ISSUE TITLE
[Bug] mailbox switch between inbox and send mail 

### ISSUE THREAD

**Issue by Anyxiah** [fang2hou/ElvUI_WindTools#251]
In the mailbox, I cannot switch between inbox and send mail.
When I click the Send Mail tab nothing happens.
When Windtools is disabled it works again.

Maybe it's Postal, but Postal without Windtools works fine.
I also send the bug to the Postal developer.

thanks for your work!!!

2x Interface/FrameXML/MailFrame.lua:145: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: MailFrameInset:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface/FrameXML/MailFrame.lua"]:145: in function `MailFrameTab_OnClick'
[string "@Interface/AddOns/Postal/Modules/BlackBook.lua"]:189: in function <Interface/AddOns/Postal/Modules/BlackBook.lua:188>
[string "=(tail call)"]: ?
[string "*MailFrame.xml:879_OnClick"]:1: in function <[string "*MailFrame.xml:879_OnClick"]:1>

Locals:
(*temporary) = MailFrameInset {
 0 = <userdata>
 NineSlice = Frame {
 }
 layoutType = "InsetFrameTemplate"
 Bg = Texture {
 }
}
(*temporary) = "TOPLEFT"
(*temporary) = 4
(*temporary) = -80

**Comment by fang2hou** [comment]
1. make sure you are using latest version 3.00 or above.
2. Follow the issue template and provides some necessary information.
