### ISSUE TITLE
Item settings/bar not working after elvui update to 13.01

### ISSUE THREAD

**Issue by picklerick84** [fang2hou/ElvUI_WindTools#252]
**Describe the bug**
Item settings are not viewable in settings

**To Reproduce**
1. Go to elvui settings
2. Click on windtools
3. Try to view item settings for extra item bars, etc

**Expected behavior**
You can't view/change any options

**Screenshots**
![image](https://user-images.githubusercontent.com/66019145/201454775-07ddea97-8d20-4142-a31c-329dcd42c210.png)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 3.00
 - ElvUI Version 13.01
 - WoW Build 10.0.0.46597

**Additional context**

**Comment by picklerick84** [comment]
I also get several errors in bugsack now:
15x FrameXML\Bindings.xml:1 Interface/AddOns/ElvUI_WindTools/Options/Item.lua:1 (null)

15x FrameXML\Bindings.xml:1 Interface/AddOns/ElvUI_WindTools/Modules/Item/AlreadyKnown.lua:1 (null)

15x Interface/AddOns/ElvUI_WindTools/Options/Item.lua:1 (null)

15x Interface/AddOns/ElvUI_WindTools/Modules/Item/AlreadyKnown.lua:1 (null)

15x WindTools [ERROR]
...ddOns/ElvUI_WindTools/Modules/Skins/ElvUI/Option.lua:34: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:210: in function <Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Interface/AddOns/ElvUI_WindTools/Modules/Skins/ElvUI/Option.lua"]:34: in function <...ddOns/ElvUI_WindTools/Modules/Skins/ElvUI/Option.lua:28>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_WindTools/Modules/Skins/Core.lua"]:505: in function <...erface/AddOns/ElvUI_WindTools/Modules/Skins/Core.lua:498>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_WindTools/Core/Core.lua"]:110: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI_WindTools/Initialize.lua"]:65: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/LibElvUIPlugin-1.0-40/LibElvUIPlugin-1.0.lua"]:299: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:295>
[string "=[C]"]: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:197: in function <Interface/AddOns/ElvUI/Core/init.lua:196>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

15x Interface/AddOns/ElvUI_WindTools/Options/Item.lua:6: Usage: GetModule(name, silent): 'name' - Cannot find module 'AlreadyKnown'.
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:208: in function `GetModule'
[string "@Interface/AddOns/ElvUI_WindTools/Options/Item.lua"]:6: in main chunk

Locals:
(*temporary) = "Usage: GetModule(name, silent): 'name' - Cannot find module 'AlreadyKnown'."

15x ...AddOns/ElvUI_WindTools/Modules/Item/AlreadyKnown.lua:2: attempt to index field 'ItemSearch' (a nil value)
[string "@Interface/AddOns/ElvUI_WindTools/Modules/Item/AlreadyKnown.lua"]:2: in main chunk

Locals:
W = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:363
 EnableModule = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua:147
 IterateEmbeds = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:438
 SecureHookScript = <function> defined @Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua:409
 ConstructCompatibilityFrame = <function> defined @Interface/AddOns/ElvUI_WindTools/Core/Compatibility.lua:17
 RawHookScript = <function> defined @Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua:394
 Printf = <function> defined @Interface/AddOns/Ace3/AceConsole-3.0/AceConsole-3.0.lua:65
 AddCommand = <function> defined @Interface/AddOns/ElvUI_WindTools/Core/Commands.lua:22
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 defaultModuleState = true
 IsEnabled = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 ScheduleTimer = <function> defined @Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua:94
 DisableModule = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:346
 RegisterModule = <function> defined @Interface/AddOns/ElvUI_WindTools/Core/Core.lua:93
 RegisteredModules = <table> {
 }
 RegisterMessage = <function> defined @Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 UnregisterMessage = <function> defined @Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 hooks = <table> {
 }
 CompatibleFont = false
 SetEnabledState = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua:273
 enabledState = true
 RegisterEvent = <function> defined @Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 Utilities = <table> {
 }
 IterateModules = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:433
 Version = "3.00"
 RawHook = <function> defined @Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua:312
 Media = <table> {
 }
 Enable = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:290
 UnregisterAllEvents = <function> defined @Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:169
 PlainTitle = "WindTools"
 Locale = "enUS"
 GetModule = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:206
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua:172
 UnregisterChatCommand = <function> defined @Interface/AddOns/Ace3/AceConsole-3.0/AceConsole-3.0.lua:107
 ScheduleRepeatingTimer = <function> defined @Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua:160
 SupportElvUIVersion = 13
 GetName = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
 ChineseLocale = false
 name = "ElvUI_WindTools"
 Initialize = <function> defined @Interface/AddOns/ElvUI_WindTools/Initialize.lua:44
 Fang2houUIPrivate = <function> defined @Interface/AddOns/ElvUI_WindTools/Settings/Fang2houUI/Private.lua:5
 orderedModules = <table> {
 }
 Disable = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:310
 CheckInstalledVersion = <function> defined @Interface/AddOns/ElvUI_WindTools/Core/Core.lua:136
 UpdateScripts = <function> defined @Interface/AddOns/ElvUI_WindTools/Core/Update.lua:24
 ForPreReleaseUser = <function> defined @Interface/AddOns/ElvUI_WindTools/Core/Update.lua:21
 CheckCompatibility = <function> defined @Interface/AddOns/ElvUI_WindTools/Core/Compatibility.lua:262
 HookScript = <function> defined @Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua:365
 Print = <function> defined @Interface/AddOns/Ace3/AceConsole-3.0/AceConsole-3.0.lua:50
 PrintDebugEnviromentTip = <function> defined @Interface/AddOns/ElvUI_Win

**Comment by fang2hou** [comment]
elvui make a very big update in 13.01, just wait for the fix version of ElvUI_WindTools.

**Comment by fang2hou** [comment]
fixed in [`3.01`](https://github.com/fang2hou/ElvUI_WindTools/releases/tag/3.01)
