### ISSUE TITLE
Export feature not working at all [Bug]

### ISSUE THREAD

**Issue by Artixwow** [fang2hou/ElvUI_WindTools#253]
**Describe the bug**
nothing happens when i click on any of the export options .

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: [e.g. 3.00]
 - ElvUI Version [e.g. 13.01]
 - WoW Build [e.g. 10.0.0 (46597)]

**Comment by fang2hou** [comment]
elvui make a very big update in 13.01, just wait for the fix version of ElvUI_WindTools.

**Comment by fang2hou** [comment]
fixed in [`3.01`](https://github.com/fang2hou/ElvUI_WindTools/releases/tag/3.01)

**Comment by fang2hou** [comment]
#254

**Comment by Artixwow** [comment]
tnx alot <3
