### ISSUE TITLE
[Feature Request] Add Shadow & Light Merchant Window Style 

### ISSUE THREAD

**Issue by mohcow** [fang2hou/ElvUI_WindTools#255]
Is there a way you could add the [Elvui Shadow & Light](https://github.com/Shadow-and-Light/shadow-and-light) style for the merchant window to windtools.? [example](https://i.imgur.com/R9Sb4e8.png)

it look really clean and takes less space then the original.

**Comment by fang2hou** [comment]
I don't like it, so I do not take time on it.
But if someone create a pull request, I can merge the code.

**Comment by mohcow** [comment]
sadly I'm not good enough with lua to do that :( I guess i have to hope that somebody else likes it as well and implements it. Thanks for answering though.
