### ISSUE TITLE
[Bug] MoveFrames Unable to Move Numerous Common Frames

### ISSUE THREAD

**Issue by Nazgul084** [fang2hou/ElvUI_WindTools#258]
**Describe the bug**
Numerous frames, like the Map, EncounterJournal (Adventure Guide), Talents, and Collections, are no longer able to be repositioned, following update to 3.03 Stable Release that fixed the MailFrame.  Most frames were able to be repositioned in 3.03 Beta 1.

**To Reproduce**
1. Install 3.03 Stable.
2. Open the Map.
3. Attempt to reposition the map.

**Expected behavior**
All frames repositionable.

**Screenshots**
Super easy to understand, shouldn't require a screenshot.

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 3.03
 - ElvUI Version 13.03
 - WoW Build 10.0.2

**Additional context**
Tested with /wtdebug on to verify.

**Comment by fang2hou** [comment]
what's you setting in misc - move frames?

**Comment by Nazgul084** [comment]
Move and History enabled. I've tried with and without ElvUI and TSM set (normally they are set).

**Comment by fang2hou** [comment]
fixed in 94ad764d3ae3ccded9b2b87d3e565ae7822316c2. you can download 3.04-beta-1 to test it.

**Comment by Nazgul084** [comment]
Interesting code changes. Appears fixed!
