### ISSUE TITLE
[Bug] Open guild bank open make game unresponsive/crash

### ISSUE THREAD

**Issue by Urmus-dev** [fang2hou/ElvUI_WindTools#261]
**Describe the bug**
Opening guild bank open make game unresponsive/crash

**To Reproduce**
Enable Already known tab in Item category
Open guild bank
Game become unresponsive and eventually, crash

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 3.04
 - ElvUI Version 13.04
 - WoW Build 10.0.2

**Comment by fang2hou** [comment]
you are using elvui guild bank?
did you have test it with `/wtdebug on`?

**Comment by Urmus-dev** [comment]
I tried with and without - same issue
wtdebug gives no message since the game hangs right when I open the guild bank

**Comment by fang2hou** [comment]
Did you tried other characters with different guild?

**Comment by Urmus-dev** [comment]
It seems that there is no issue if I open the guild bank from my mule alt, where I have all rights.

**Comment by fang2hou** [comment]
can you help me test 3.05-beta-3?
already known has been refactored with new logics.

**Comment by Urmus-dev** [comment]
It works with all options activated and the game does not crash!
However, a message appears now (with and without the option activated) telling that I don't have the permission to do that (and I have no rights in this guild bank). I don't know if it's because of Windtools or not since I updated other addons, incl ElvUI, I can't do further testing right now.
Anyway, it's not an issue, so all good for me!

**Comment by fang2hou** [comment]
@Urmus-dev
Thanks for your quick report, if the alert come from WindTools, please let me know.
