### ISSUE TITLE
[Bug] WindTools - Extra (Keybindings) -> "Logout" & "Leave Party if soloing" is not working

### ISSUE THREAD

**Issue by Tbzz** [fang2hou/ElvUI_WindTools#264]
**These are the functions that have keybinds under: Options -> Addons -> Keybindings -> WindTools - Extra**

**Logout**
- No longer works as of 10.0.0. Maybe it's related to being a protected function, but I don't really know.
- https://wowpedia.fandom.com/wiki/World_of_Warcraft_API#System
- https://wowpedia.fandom.com/wiki/Secure_code

**Leave Part if soloing**
- This never worked since it's introduction. I was the one who [originally suggested](https://github.com/fang2hou/ElvUI_WindTools/issues/188) this functionality.
- For this to work, you need a delay between "/inv 1" & leaving the group for this to work. I don't know an optimal delay value, but anything more than 3 seconds and your group status will be removed automatically. Something between 0.5 and 2 seconds would probably work.
- I'm currently using the macro below as a working replacement. This method of delay causes the game to freeze for a very short time. However, if there is no other method of delay that can replace this, I would still be very happy to have the functionality updated with this.
```
/inv 1
/run local t = time() + 0.1 while time() < t do end
/script C_PartyInfo.LeaveParty()
```
Increasing the number in the macro increases delay / freeze time.
- The "/pr 1" line in the [original suggestion](https://github.com/fang2hou/ElvUI_WindTools/issues/188) is not required.

**Screenshots**
- [Screenshot of relevant settings](https://imgur.com/a/URkbv5X)
- [This message](https://imgur.com/a/wN3zqeS) will show up 8-10 seconds after a successful use of "Leave Party if soloing"

**Information**
 - Addon Version: 3.05
 - ElvUI Version: 13.06
 - WoW Build: 10.0.2 (46741)

**Comment by fang2hou** [comment]
I will check it, thanks for your clear description.

**Comment by fang2hou** [comment]
maybe that is another reason to cause the function not work, try `3.06-beta-3`
