### ISSUE TITLE
[Bug] 团队标记条 Lua 错误

### ISSUE THREAD

**Issue by ZhiqiangJerryQiu** [fang2hou/ElvUI_WindTools#267]
**描述问题**
BugSack 发现的不影响游戏加载的报错信息。

**错误复现**
错误复现步骤:
1. 打开游戏

**插件信息 (请填写基本信息, 你可以在 [信息] 中找到):**
 - 插件版本: 3.06
 - ElvUI 版本 13.06
 - 游戏版本 10.0.2.46801

**更多信息**
Error Log：
9x ...ddOns/ElvUI_WindTools/Modules/Combat/RaidMarkers.lua:446: attempt to perform arithmetic on field '__toScale' (a nil value)
[string "@ElvUI_WindTools/Modules/Combat/RaidMarkers.lua"]:446: in function <...ddOns/ElvUI_WindTools/Modules/Combat/RaidMarkers.lua:441>
[string "=[C]"]: ?

Locals:
self = Button {
 CalculateAction = <function> defined @FrameXML/SecureTemplates.lua:609
 PixelSnapDisabled = true
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 animGroup = AnimationGroup {
 }
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 tex = Texture {
 }
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 backdrop = Frame {
 }
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 0 = <userdata>
}
progress = Infinite
currentScale = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field '__toScale' (a nil value)"
RM = <table> {
 UpdateBar = <function> defined @ElvUI_WindTools/Modules/Combat/RaidMarkers.lua:36
 Enable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:290
 UnregisterAllEvents = <function> defined @APR-Core/lib/HereBeDragons/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 EnableModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 defaultModuleLibraries = <table> {
 }
 modifierString = "Shift"
 SetDefaultModulePrototype = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 barAnchor = Frame {
 }
 name = "ElvUI_WindTools_RaidMarkers"
 Initialize = <function> defined @ElvUI_WindTools/Modules/Combat/RaidMarkers.lua:504
 IsEnabled = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 DisableModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:346
 Log = <function> defined @ElvUI_WindTools/Core/Functions/Developer.lua:124
 UpdateButtons = <function> defined @ElvUI_WindTools/Modules/Combat/RaidMarkers.lua:96
 RegisterMessage = <function> defined @APR-Core/lib/HereBeDragons/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @APR-Core/lib/HereBeDragons/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 bar = Frame {
 }
 IsModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:213
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:383
 baseName = "ElvUI_WindTools"
 ProfileUpdate = <function> defined @ElvUI_WindTools/Modules/Combat/RaidMarkers.lua:491
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 CreateButtons = <function> defined @ElvUI_WindTools/Modules/Combat/RaidMarkers.lua:239
 enabledState = true
 CreateBar = <function> defined @ElvUI_WindTools/Modules/Combat/RaidMarkers.lua:197
 RegisterEvent = <function> defined @APR-Core/lib/HereBeDragons/CallbackHandler-1

**Comment by fang2hou** [comment]
满级后我再进行一下排查, 可以尝试重置一下这个模块的设定.
