### ISSUE TITLE
[Bug] Group Info Tooltip keeps getting disabled

### ISSUE THREAD

**Issue by Beet4** [fang2hou/ElvUI_WindTools#268]
**Describe the bug**
When enabling the Group Info Tooltip it works fine and seems to show the correct information in the LFG tool. But after a reload or game restart the function is disabled again.

**To Reproduce**
1. Go to Tooltips in Windtools
2. Click on Enable Group Info
3. Verify functionality in LFG window
4. Reload
5. Go back to tooltips in Windtools and Group Info is disabled and no longer working.

**Expected behavior**
Group Info should keep being enabled when reloading and restarting the game.

**Screenshots**
Enable function
![image](https://user-images.githubusercontent.com/38279393/205245881-3e342d3e-7535-47ab-ae87-1d084506eb25.png)

Works as expected
![image](https://user-images.githubusercontent.com/38279393/205245924-67d7280b-5188-492d-abfa-336569dc9a67.png)

Reload, disabled again
![image](https://user-images.githubusercontent.com/38279393/205245579-ad535400-427f-4fcb-a056-ddb69a3eb1c0.png)

No longer working
![image](https://user-images.githubusercontent.com/38279393/205246397-9276a347-6934-4ea7-8594-b92208f8625c.png)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 3.08
 - ElvUI Version 13.08
 - WoW Build 10.0.2 (build 46879)

**Additional context**
When using /wtdebug on it seems to work fine. Compatibility issue with another addon? Perhaps Premade Groups Filter?

Bonus question: Why is it no longer possible to use the LFG List functions in Windtools -> Misc when having Premade Groups Filter? WindTools does its functions mucher nicer than PGF while PGF is nice to have to filter groups. :) Would be awesome if we could still use both together like before.

**Comment by fang2hou** [comment]
That is not bug actually, because you are using PGF.
Because I have no way to know you enable the party info in PFG or not, the tooltip info will be disabled when PGF loaded.
BTW, if PGF loaded, some other LFG QoL features in Misc will also be disabled by default.
