### ISSUE TITLE
地图与任务日志中某些任务的文字重叠问题

### ISSUE THREAD

**Issue by kinsluck** [fang2hou/ElvUI_WindTools#27]
**Description**
某些任务在『地图与任务日志中』会出现字体重叠问题，目前已知的有副本任务以及『驯服艾泽拉斯』中的宠物对战任务

**Version Number**
1.2.0

**Screenshot**
![snipaste_2018-08-13_18-00-58](https://user-images.githubusercontent.com/17947570/44025834-c83afa00-9f23-11e8-8782-b264f0f7532b.png)

**Comment by fang2hou** [comment]
功能重做中，只是目前新版本就要开了，可能重做要等一段时间。
如果受不了的话可以直接禁用这个功能，然后用单体比如 Quester。（我就在用）
