### ISSUE TITLE
[Bug]WindTools [ERROR]

### ISSUE THREAD

**Issue by Imna1975** [fang2hou/ElvUI_WindTools#272]
2x WindTools [ERROR]
...UI_WindTools/Modules/Skins/Blizzard/AdventureMap.lua:19: attempt to index field 'TopEdge' (a nil value)
[string "@ElvUI_WindTools/Modules/Skins/Blizzard/AdventureMap.lua"]:19: in function <...UI_WindTools/Modules/Skins/Blizzard/AdventureMap.lua:7>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Modules/Skins/Core.lua"]:335: in function `CallLoadedAddon'
[string "@ElvUI_WindTools/Modules/Skins/Core.lua"]:352: in function `?'
[string "@!KalielsTracker/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...ker/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@!KalielsTracker/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...ker/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@!KalielsTracker/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Decursive/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Decursive/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:729: in function `Garrison_LoadUI'
[string "@FrameXML/UIParent.lua"]:2062: in function <FrameXML/UIParent.lua:1362>

**Comment by fang2hou** [comment]
Did you disabled ElvUI skin of adventure map?

**Comment by fang2hou** [comment]
added a small check in skins. b3b615e2
