### ISSUE TITLE
[Bug] Chat Link features hide the quality of the new DF crafted items

### ISSUE THREAD

**Issue by Shirofune** [fang2hou/ElvUI_WindTools#275]
**Describe the bug**
When enabling the Chat Link features of WindTools (Social -> Chat Link) the quality of the new DF crafted items dissappears.

There's no option to enable the quality back

**To Reproduce**
1. Enable WindTools
2. Enable Chat Link Features
3. Link an item with quality to the chat

**Expected behavior**
The link should show the quality and give the user an option to enable or disable it.

**Screenshots**
Options:
![image](https://user-images.githubusercontent.com/15874551/205670021-1acb03e1-cbdb-477a-ba0c-44ddc4a90bdc.png)

Bug (top one is without WindTools, bottom is with):
![image](https://user-images.githubusercontent.com/15874551/205670073-4a9fed7d-7243-466f-86f8-89c4546cd03d.png)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 3.10
 - ElvUI Version 13.10
 - WoW Build 10.0.2 (46924)

**Comment by fang2hou** [comment]
Disable the translate feature will fix that, I will try to find a way to add back the quality icon.

**Comment by fang2hou** [comment]
fixed in 5619996627faf5df2f8e29abb65f5f7cc161dee5
