### ISSUE TITLE
(Bug)? - with all bars free of binding and able to add remove freely items or skills, i can not do this with the extra buttons  and have to remove the bars and put items on other bars to have the items at the place i want them [Bug] - with last version 

### ISSUE THREAD

**Issue by Anceane** [fang2hou/ElvUI_WindTools#278]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: [e.g. 2.00]
 - ElvUI Version [e.g. 12.00]
 - WoW Build [e.g. 9.0.1 (25600)]

**Additional context**

**Comment by fang2hou** [comment]
Try reset the module once.
You can find the button in Advanced - Reset - Item - Extra Item Bar

**Comment by fang2hou** [comment]
fixed in fae779d9fd6ff52c94ac3cb2ed6aacd596f33f53
