### ISSUE TITLE
Event Start time for NA Siege on Dragonbane Keep off by an hour?

### ISSUE THREAD

**Issue by CodeW0lf** [fang2hou/ElvUI_WindTools#283]
I'm noticing that Siege on Dragonbane Keep looks to be early by an hour for NA servers.

https://github.com/fang2hou/ElvUI_WindTools/blob/ab2db5721c3fb87a192d7a1d90bfbc52e0bb2574/Modules/Maps/EventTracker.lua#L298

I believe the proper start timestamp keeping this format would be `1670770800`

I checked this value on two different NA realms in different time zones and it appears to be correct.

**Comment by fang2hou** [comment]
I am using wowhead to make timer in na and eu.

did you try to change the timestamp to 1670770800 and test it in-game?

**Comment by CodeW0lf** [comment]
I did check it across a couple of servers in different time zones, comparing to an existing weakaura that has proven accurate. I could be unique in some weird way XD

**Comment by fang2hou** [comment]
3.13-fix-1 already fix the timer.
