### ISSUE TITLE
[Feature Request] Full emote template control

### ISSUE THREAD

**Issue by duckies** [fang2hou/ElvUI_WindTools#285]
Hello, would you be willing to remove this prefix from the announcement chat messages when they're an emote, or make this a toggle?

```
if channel == "EMOTE" then
   text = ": " .. text
end
```

I'd like to be able to have messages such as `Duckys interrupted [spell]` on the emote channel instead of `Duckys: interrupted [spell]`.

**Comment by fang2hou** [comment]
sure

**Comment by fang2hou** [comment]
Because there are some important changes in ElvUI, this feature will be added in the next version. (3.15 in plan)
