### ISSUE TITLE
Feature Request: Mute Jewelcrafting sound

### ISSUE THREAD

**Issue by Chorthee** [fang2hou/ElvUI_WindTools#288]
Could you please add the Jewelcrafting sound to the availble Mute sounds on the Misc Page.  That one annoys me so much.  It's like nails on a chalkboard.

**Comment by fang2hou** [comment]
can you provide the sound ids?
it is very hard to find the specific ids for these sounds.

**Comment by Chorthee** [comment]
Sure, I just found it.  Here is the info:
````

Thanks for getting back to me.    On Sunday, December 18, 2022 at 09:01:55 PM EST, Zhou Fang ***@***.***> wrote:  
 
 


can you provide the sound ids?
it is very hard to find the specific ids for these sounds.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Chorthee** [comment]
I found it.  Here is the info:

569325 - jewelcrafting sound id
