### ISSUE TITLE
Lua error...

### ISSUE THREAD

**Issue by Milky063** [fang2hou/ElvUI_WindTools#292]
**Describe the bug**
2x ...ddOns/ElvUI_WindTools/Modules/Announcement/Quest.lua:25: attempt to index local 'questInfo' (a nil value)
[string "@ElvUI_WindTools/Modules/Announcement/Quest.lua"]:25: in function <...ddOns/ElvUI_WindTools/Modules/Announcement/Quest.lua:20>
[string "@ElvUI_WindTools/Modules/Announcement/Quest.lua"]:104: in function `Quest'
[string "@ElvUI_WindTools/Modules/Announcement/Events.lua"]:68: in function `?'
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
quests = <table> {
 29135 = <table> {
 }
 65842 = <table> {
 }
 67142 = <table> {
 }
 66243 = <table> {
 }
}
(for index) = 20
(for limit) = 64
(for step) = 1
questIndex = 20
questInfo = nil
(*temporary) = nil
(*temporary) = 20
(*temporary) = nil
(*temporary) = 0
(*temporary) = nil
(*temporary) = 1
(*temporary) = "0/12  "
(*temporary) = 1
(*temporary) = 6
(*temporary) = "0"
(*temporary) = "12"
(*temporary) = " "
(*temporary) = <table> {
 link = "|cffffff00|Hquest:67142:2287|h[Wyrm Food]|h|r"
 questID = 67142
 suggestedGroup = 0
 1 = <table> {
 }
 title = "Wyrm Food"
 level = 70
 frequency = 2
}
(*temporary) = <table> {
 numNeeded = "12"
 item = " "
 numItems = "0"
}
(*temporary) = "attempt to index local 'questInfo' (a nil value)"
C_QuestLog_GetNumQuestLogEntries = <function> defined =[C]:-1
C_QuestLog_GetInfo = <function> defined =[C]:-1
C_QuestLog_GetQuestTagInfo = <function> defined =[C]:-1
GetQuestLink = <function> defined =[C]:-1
GetNumQuestLeaderBoards = <function> defined =[C]:-1
GetQuestLogLeaderBoard = <function> defined =[C]:-1
strfind = <function> defined =[C]:-1

**To Reproduce**
log on then off. still happen

**Expected behavior**
Expect it not to give me a error...

**Screenshots**

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: ElvUI_WindTools-3.15.zip
 - ElvUI Version 13.14
 - WoW Build 10.0.2.47213

**Additional context**

**Comment by fang2hou** [comment]
2db8f261dbc2997a1bc37434be72b97ef58ebe04
