### ISSUE TITLE
[Bug] Repeated error while in Arena, solo queue

### ISSUE THREAD

**Issue by wigoor** [fang2hou/ElvUI_WindTools#296]
**Describe the bug**
Repeated error every time player casts a spell in Arena (solo queue).

247x Usage: local position = C_Map.GetPlayerMapPosition(uiMapID, unitToken)
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Modules/Maps/EventTracker.lua"]:650: in function `handler'
[string "@ElvUI_WindTools/Modules/Maps/EventTracker.lua"]:779: in function `?'
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = "Usage: local position = C_Map.GetPlayerMapPosition(uiMapID, unitToken)"

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 3.17
 - ElvUI Version 13.15
 - WoW Build 10.0.2 (47213)

**Comment by fang2hou** [comment]
fixed in 3.17-fix-2
