### ISSUE TITLE
[Feature] Add profession skill up items for item bars

### ISSUE THREAD

**Issue by Urmus-dev** [fang2hou/ElvUI_WindTools#298]
This is a proposition to add as a feature a group for profession speciality points in the item bar tags (like https://www.wowhead.com/item=198975)

**Comment by Tednik** [comment]
Here is a complete list of the profession knowledge items


192131, -- Valdrakken Weapon Chain
192132, -- Draconium Blade Sharpener
192443, -- Element-Infused Rocket Helmet
193891, -- Experimental Substance
193897, -- Reawakened Catalyst
193898, -- Umbral Bone Needle
193899, -- Primalweave Spindle
193900, -- Prismatic Focusing Shard
193901, -- Primal Dust
193902, -- Eroded Titan Gizmo
193903, -- Watcher Power Core
193904, -- Phoenix Feather Quill
193905, -- Iskaaran Trading Ledger
193907, -- Chipped Tyrstone
193909, -- Ancient Gem Fragments
193910, -- Molted Dragon Scales
193913, -- Preserved Animal Parts
194039, -- Heated Ore Sample
194040, -- Slateskin Hide
194041, -- Driftbloom Sprout
194042, -- Explorer's Banner of Herbology
194043, -- Explorer's Banner of Herbology
194044, -- Explorer's Banner of Herbology
194045, -- Explorer's Banner of Geology
194046, -- Explorer's Banner of Geology
194047, -- Explorer's Banner of Geology
194054, -- Dredged Seedling
194055, -- Primordial Soil
194061, -- Suffocating Spores
194062, -- Unyielding Stone Chunk
194063, -- Glowing Fragment
194064, -- Intricate Geode
194078, -- Perfect Draconium Scale
194079, -- Pure Serevite Nugget
194080, -- Peculiar Bud
194081, -- Mutated Root
194697, -- Draconic Treatise on Alchemy
194698, -- Draconic Treatise on Tailoring
194699, -- Draconic Treatise on Inscription
194700, -- Draconic Treatise on Leatherworking
194702, -- Draconic Treatise on Enchanting
194703, -- Draconic Treatise on Jewelcrafting
194704, -- Draconic Treatise on Herbalism
194708, -- Draconic Treatise on Mining
198156, -- Wyrmhole Generator
198454, -- Draconic Treatise on Blacksmithing
198510, -- Draconic Treatise on Engineering
198518, -- Professor Instructaur's Top Secret Guide to Blacksmithing
198519, -- Professor Instructaur's Top Secret Guide to Alchemy
198520, -- Professor Instructaur's Top Secret Guide to Enchanting
198521, -- Professor Instructaur's Top Secret Guide to Engineering
198522, -- Professor Instructaur's Top Secret Guide to Herbalism
198523, -- Professor Instructaur's Top Secret Guide to Inscription
198524, -- Professor Instructaur's Top Secret Guide to Jewelcrafting
198525, -- Professor Instructaur's Top Secret Guide to Leatherworking
198526, -- Professor Instructaur's Top Secret Guide to Mining
198527, -- Professor Instructaur's Top Secret Guide to Skinning
198528, -- Professor Instructaur's Top Secret Guide to Tailoring
198599, -- Experimental Decay Sample
198606, -- Blacksmith's Writ
198607, -- Scribe's Glyphs
198608, -- Alchemy Notes
198609, -- Tailoring Examples
198610, -- Enchanter's Script
198611, -- Engineering Details
198612, -- Jeweler's Cuts
198613, -- Leatherworking Designs
198656, -- Painter's Pretty Jewel
198658, -- Decay-Infused Tanning Oil
198659, -- Forgetful Apprentice's Tome
198660, -- Fragmented Key
198662, -- Intriguing Bolt of Blue Cloth
198663, -- Frostforged Potion
198664, -- Crystalline Overgrowth
198667, -- Spare Djaradin Tools
198669, -- How to Train Your Whelpling
198670, -- Lofty Malygite
198675, -- Lava-Infused Seed
198680, -- Decaying Brackenhide Blanket
198682, -- Alexstraszite Cluster
198683, -- Treated Hides
198684, -- Miniature Bronze Dragonflight Banner
198685, -- Well Insulated Mug
198686, -- Frosted Parchment
198687, -- Closely Guarded Shiny
198689, -- Stormbound Horn
198690, -- Decayed Scales
198692, -- Noteworthy Scrap of Carpet
198693, -- Dusty Darkmoon Card
198694, -- Enriched Earthen Shard
198696, -- Wind-Blessed Hide
198697, -- Contraband Concoction
198699, -- Mysterious Banner
198702, -- Itinerant Singed Fabric
198703, -- Sign Language Reference Sheet
198704, -- Pulsing Earth Rune
198710, -- Canteen of Suspicious Water
198711, -- Poacher's Pack
198712, -- Firewater Powder Sample
198789, -- Intact Coil Capacitor
198798, -- Flashfrozen Scroll
198799, -- Forgotten Arcane Tome
198800, -- Fractured Titanic Sphere
198836, -- Arclight Vital Correctors
198837, -- Curious Hide Scraps
198841, -- Large Sample of Curious Hide
198963, -- Decaying Phlegm
198964, -- Elementious Splinter
198965, -- Primeval Earth Fragment
198966, -- Molten Globule
198967, -- Primordial Aether
198968, -- Primalist Charm
198969, -- Keeper's Mark
198970, -- Infinitely Attachable Pair o' Docks
198971, -- Curious Djaradin Rune
198972, -- Draconic Glamour
198973, -- Incandescent Curio
198974, -- Elegantly Engraved Embellishment
198975, -- Ossified Hide
198976, -- Exceedingly Soft Skin
198977, -- Ohn'arhan Weave
198978, -- Stupidly Effective Stitchery
199115, -- Herbalism Field Notes
199122, -- Mining Field Notes
199128, -- Skinning Field Notes
200677, -- Dreambloom Petal
200678, -- Dreambloom
200972, -- Dusty Blacksmith's Diagrams
200973, -- Dusty Scribe's Runic Drawings
200974, -- Dusty Alchemist's Research
200975, -- Dusty Tailor's Diagrams
200976, -- Dusty Enchanter's Research
200977, -- Dusty Engineer's Scribblings
200978, -- Dusty Jeweler's Illustrations
200979, -- Dusty Leatherworker's Diagrams
200980, -- Dusty Herbalist's Notes
200981, -- Dusty Miner's Notes
200982, -- Dusty Skinner's Notes
201003, -- Furry Gloop
201004, -- Ancient Spear Shards
201005, -- Curious Ingots
201006, -- Draconic Flux
201007, -- Ancient Monument
201008, -- Molten Ingot
201009, -- Falconer Gauntlet Drawings
201010, -- Qalashi Weapon Diagram
201011, -- Spelltouched Tongs
201012, -- Enchanted Debris
201013, -- Faintly Enchanted Remains
201014, -- Boomthyr Rocket
201015, -- Counterfeit Darkmoon Deck
201016, -- Harmonic Crystal Harmonizer
201017, -- Igneous Gem
201018, -- Well-Danced Drum
201019, -- Ancient Dragonweave Bolt
201020, -- Silky Surprise
201023, -- Draconic Treatise on Skinning
201268, -- Rare Blacksmith's Diagrams
201269, -- Rare Scribe's Runic Drawings
201270, -- Rare Alchemist's Research
201271, -- Rare Tailor's Diagrams
201272, -- Rare Enchanter's Research
201273, -- Rare Engineer's Scribblings
201274, -- Rare Jeweler's Illustrations
201275, -- Rare Leatherworker's Diagrams
201276, -- Rare Herbalist's Notes
201277, -- Rare Miner's Notes
201278, -- Rare Skinner's Notes
201279, -- Ancient Blacksmith's Diagrams
201280, -- Ancient Scribe's Runic Drawings
201281, -- Ancient Alchemist's Research
201282, -- Ancient Tailor's Diagrams
201283, -- Ancient Enchanter's Research
201284, -- Ancient Engineer's Scribblings
201285, -- Ancient Jeweler's Illustrations
201286, -- Ancient Leatherworker's Diagrams
201287, -- Ancient Herbalist's Notes
201288, -- Ancient Miner's Notes
201289, -- Ancient Skinner's Notes
201300, -- Iridescent Ore Fragments
201301, -- Iridescent Ore
201356, -- Glimmer of Fire
201357, -- Glimmer of Frost
201358, -- Glimmer of Air
201359, -- Glimmer of Earth
201360, -- Glimmer of Order
201700, -- Notebook of Crafting Knowledge
201705, -- Notebook of Crafting Knowledge
201706, -- Notebook of Crafting Knowledge
201708, -- Notebook of Crafting Knowledge
201709, -- Notebook of Crafting Knowledge
201710, -- Notebook of Crafting Knowledge
201711, -- Notebook of Crafting Knowledge
201712, -- Notebook of Crafting Knowledge
201713, -- Notebook of Crafting Knowledge
201715, -- Notebook of Crafting Knowledge
201716, -- Notebook of Crafting Knowledge
201717, -- Notebook of Crafting Knowledge
202011, -- Elementally-Charged Stone
202014, -- Infused Pollen
202016, -- Saturated Bone

**Comment by fang2hou** [comment]
god, huge thanks!

**Comment by Merathilis** [comment]
great job on collect the data.. many thanks <3
