### ISSUE TITLE
关于发布版本

### ISSUE THREAD

**Issue by fang2hou** [fang2hou/ElvUI_WindTools#30]
新版本的迭代不一定要我来完成。
现在只要发布一个Release，tag有beta或者alpha，将会自动被twitch标注为测试版本。
如果不带的话会作为正式版本发布。

最近游戏里面实在太忙了，代码看不过来。
@someblu

**Comment by fang2hou** [comment]
https://authors.curseforge.com/docs/packaging

**Comment by someblu** [comment]
好的，前两天旅游去了，现在才看到。。。

**Comment by someblu** [comment]
为什么有的时候在github上发布了新的release但是twitch上却迟迟没有更新，curseforge 上有没有手动fetch的操作按钮。比如我下午发布的1.3.5，已经过了三个小时了。。。

**Comment by someblu** [comment]
嗯，五个小时后可算在twitch上看见了。。应该是维护了
