### ISSUE TITLE
[Bug] LUA Error

### ISSUE THREAD

**Issue by sissiwup** [fang2hou/ElvUI_WindTools#300]
Message: attempt to concatenate a table value
Time: Tue Jan 17 22:08:32 2023
Count: 1
Stack: attempt to concatenate a table value
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_WindTools/Modules/Datatexts/Range.lua"]:63: in function `colorUpdate'
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:370: in function `AssignPanelToDataText'
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:506: in function <...ce/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua:415>
[string "=[C]"]: in function `UpdatePanelInfo'
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:524: in function <...ce/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua:511>
[string "=[C]"]: in function `LoadDataTexts'
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:750: in function `?'
[string "@Interface/AddOns/Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:

**Comment by fang2hou** [comment]
What's your ElvUI version & WindTools version?
Please follow the template of issue.
