### ISSUE TITLE
[Possible Bug] Broken "Expansion Landing Page" icon

### ISSUE THREAD

**Issue by Luckyone961** [fang2hou/ElvUI_WindTools#301]
**Describe the bug**
Modules > Maps > Minimap Buttons > Expansion Landing Page doesn't seem to be working correctly.
The icon is very small and stuck in the middle of the bar between addon icons.

**To Reproduce**
1. Go to Modules > Maps > Minimap Buttons
2. Click on Expansion Landing Page (Enable it) and then reload
3. Set Buttons Per Row to (6) Button Size to (23) Button Spacing to (3)
4. Set Orientation to (Horizontal) and Inverse Direction (Disable it)

**Expected behavior**
The landing page icon should look like the other 5 icons in the screenshots below.
All testing was done on a Druid, level 70, in Dragonflight (Valdrakken) zone.

**Screenshots**
![Screenshot 1](https://i.imgur.com/x8mJ2br.png "Screenshot 1")
![Screenshot 2](https://i.imgur.com/ok6lS5J.png "Screenshot 2")
![Screenshot 3](https://i.imgur.com/30XOl03.png "Screenshot 3")

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 3.20
 - ElvUI Version: 13.21
 - WoW Build: 10.0.2 (47631)

**Comment by fang2hou** [comment]
I set the minimap bar follow your steps, but it works properly.
![image](https://user-images.githubusercontent.com/6694722/213842283-f6a751a5-be56-4079-b22f-d2c210014dcb.png)

**Comment by Luckyone961** [comment]
Interesting, I wonder if one of my ElvUI settings is somehow messing with it - I'll double check and mess with it later today

**Comment by Luckyone961** [comment]
You are right, it seems to be working if I set the button scale to 1 and x+y offsets to 0 in ElvUI map options. However, with only ElvUI and WindTools enabled the button doesn't seem to be clickable so I can not open the landing page
![Screenshot 1](https://i.imgur.com/EDhoicp.png "Screenshot 1")

**Comment by fang2hou** [comment]
1. Try move the bar away from the minimap.
2. The clickable area sometimes not same with the icon, try move the cursor above the icon, and if the icon being lighter the landing page should be openable.

**Comment by Luckyone961** [comment]
If I use "Inverse Direction" in the WindTools options so the landing page icon moves to the left of the bar it works perfectly and this way I don't have to move the bar - I can live with that. Appreciate the replies!
