### ISSUE TITLE
[Bug] LUA Errors with Windtools+ElvUI running.

### ISSUE THREAD

**Issue by instant0** [fang2hou/ElvUI_WindTools#302]
**Describe the bug**
I do not know what the bug is, but with elvui and windtools default installed (tested with 3.19, .20 and 21 of elvui and windtools 19fix4+20) I will get two LUA error messages that refer to Elvui Core Initialize functions (i.e. addon startup). 
You can still play and parts of ELVUI Will work, such as actionbuttons and user interface elements, 
But some other addons will have failed, and Windtools will not be running at all.
This started yesterday after I updated elvui/windtools.  Never had a problem before.
Even when going down to earlier versionf of ElvUI + Windtools the problem remained.. 

**To Reproduce**
Install Elvui 3.20 and Windtools 3.19fix4

**Expected behavior**
Working as before.

**Additional context**
Workaround was to rename ElvUI_WindTools to XXElvUI_Windtools (and the .toc file), to ensure that Windtools was the last addon loaded (assuming it is done alphabetically, which I believe).

**Comment by fang2hou** [comment]
Please use the latest version of ElvUI WindTools.
