### ISSUE TITLE
[Bug] ElvUI Data Text Panels - Some Backdrops and Borders Missing on Load

### ISSUE THREAD

**Issue by wowizzy** [fang2hou/ElvUI_WindTools#303]
**Describe the bug**

With ElvUI and WindTools enabled - on load the backdrop and borders of some data text panels are missing. Opening the ElvUI config and checking either the backdrop or border checkbox off and back on for each of the missing panels re-enables them. A reload causes them to disappear again.

With only ElvUI enabled - no other add-ons - works correctly.
With ElvUI and all other addons EXCEPT WindTools - works correctly.
With ONLY ElvUI and WindTools enabled - panels are missing.

**To Reproduce**

Log into the game. Some (not all) panels are invisible.

**Screenshots**

![WoWScrnShot_012223_135131](https://user-images.githubusercontent.com/123328017/213937229-2764ca15-b84b-4da4-bac9-b2421f1e3dfc.jpg)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 3.20
 - ElvUI Version 13.21
 - WoW Build 10.0.2 (47631)

The following LUA error is logged in BugSack. With WindTools disabled, there are no errors, so I assume this means it's related.

40x attempt to concatenate a table value
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Modules/Datatexts/Range.lua"]:63: in function `colorUpdate'
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:349: in function `AssignPanelToDataText'
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:506: in function <...ceElvUI/Core/Modules/DataTexts/DataTexts.lua:415>
[string "=[C]"]: in function `UpdatePanelInfo'
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:524: in function `LoadDataTexts'
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:750: in function `?'
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:114: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

**Comment by fang2hou** [comment]
already fixed in beta version.

**Comment by wowizzy** [comment]
You are a rock star! Thanks!
