### ISSUE TITLE
[Bug] New WindTools - Keystone window: I can't tell how to hide or move the window

### ISSUE THREAD

**Issue by JeremyMorton** [fang2hou/ElvUI_WindTools#304]
**Describe the bug**
There's a new "WindTools - Keystone" window on the screen that lists the keystones of me and my party. It's in an inconvenient place, covering up several different UI elements, but I can't find any settings for it in the Options, so I haven't been able to figure out how to hide or move the window.

**To Reproduce**
1. Upgrade to WindTools 3.21-beta-4
2. See the WindTools - Keystone window in the lower right part of the screen that doesn't seem draggable or hidable, even when toggling the ElvUI anchors.

**Expected behavior**
A setting for showing or hiding the window, and the window having an ElvUI window anchor so that it can be moved (and maybe scaling of text, as well).

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 3.21-beta-4
 - ElvUI Version 13.21
 - WoW Build 10.0.2 (47631)

**Comment by fang2hou** [comment]
Misc - LFG List.
Check changelog first.

**Comment by JeremyMorton** [comment]
Thanks, I was just blind. 🥲

**Comment by fang2hou** [comment]
3.21-beta-5 already fixed that you can try it.
