### ISSUE TITLE
bug error 

### ISSUE THREAD

**Issue by Imna1975** [fang2hou/ElvUI_WindTools#312]
**Describe the bug**
8x ...s/ElvUI_WindTools/Modules/Quest/ObjectiveTracker.lua:207: bad argument #1 to 'strfind' (string expected, got nil)
[string "=[C]"]: in function `strfind'
[string "@ElvUI_WindTools/Modules/Quest/ObjectiveTracker.lua"]:207: in function `HandleInfoText'
[string "@ElvUI_WindTools/Modules/Quest/ObjectiveTracker.lua"]:250: in function <...s/ElvUI_WindTools/Modules/Quest/ObjectiveTracker.lua:237>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `AddObjective'
[string "@Blizzard_ObjectiveTracker/Blizzard_BonusObjectiveTracker.lua"]:730: in function <..._ObjectiveTracker/Blizzard_BonusObjectiveTracker.lua:709>
[string "@Blizzard_ObjectiveTracker/Blizzard_BonusObjectiveTracker.lua"]:839: in function <..._ObjectiveTracker/Blizzard_BonusObjectiveTracker.lua:735>
[string "@Blizzard_ObjectiveTracker/Blizzard_BonusObjectiveTracker.lua"]:928: in function <..._ObjectiveTracker/Blizzard_BonusObjectiveTracker.lua:922>
[string "@Blizzard_ObjectiveTracker/Blizzard_BonusObjectiveTracker.lua"]:963: in function `Update'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTracker.lua"]:1441: in function <...zzard_ObjectiveTracker/Blizzard_ObjectiveTracker.lua:1373>
[string "=[C]"]: ?
[string "=[C]"]: in function `ObjectiveTracker_Update'
[string "@Blizzard_ObjectiveTracker/Blizzard_BonusObjectiveTracker.lua"]:1305: in function <..._ObjectiveTracker/Blizzard_BonusObjectiveTracker.lua:1305>

Locals:
(*temporary) = nil
(*temporary) = "^%- "
(*temporary) = "string expected, got nil"

**Information (you can find these in [WindTools-Information]):**
 - Addon Version:  [3.23-beta-5]
 - ElvUI Version  13.23
 - WoW Build 10.0.5.47939

**Additional context**

**Comment by fang2hou** [comment]
fixed in recent commits.
