### ISSUE TITLE
[Bug] error 

### ISSUE THREAD

**Issue by Imna1975** [fang2hou/ElvUI_WindTools#319]
1x ...eElvUI_WindTools/Modules/Social/ChatText.lua:1282: invalid option in `format'
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Modules/Social/ChatText.lua"]:1282: in function `ChatFrame_MessageEventHandler'
[string "@ElvUI/Core/Modules/Chat/Chat.lua"]:2265: in function `ChatFrame_OnEvent'
[string "@ElvUI/Core/Modules/Chat/Chat.lua"]:2269: in function `FloatingChatFrame_OnEvent'
[string "@ElvUI/Core/Modules/Chat/Chat.lua"]:2274: in function <ElvUI/Core/Modules/Chat/Chat.lua:2273>

Locals:
(*temporary) = "Die Anwesenheit von %n hat einen Geist in der Nähe dazu inspiriert, sich auch in den Kampf zu stürzen."
(*temporary) = "Gefallener Geist"
(*temporary) = "Gefallener Geist"

**Comment by fang2hou** [comment]
It cannot be fixed because that part is actually from elvui, just wait for them update chat module, and then I will sync their changes.
