### ISSUE TITLE
[Bug] Tomcat's Tours addon skin error.

### ISSUE THREAD

**Issue by free4one** [fang2hou/ElvUI_WindTools#320]
**Describe the bug**
Skin related error after Tomcat's Tours addon is updated.

**To Reproduce**
Occurs when the skin is applied after accessing the game.

**Expected behavior**

**Screenshots**

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 3.27
 - ElvUI Version 13.29
 - WoW Build10.07
 - TomCat's Tours Version: 2.4.61

**Additional context**
1x WindTools [ERROR]
...Ons/ElvUI_WindTools/Modules/Skins/Addons/TomCats.lua:31: attempt to index field 'TomCats_Config' (a nil value)
[string "@ElvUI_WindTools/Modules/Skins/Addons/TomCats.lua"]:31: in function `TomCats_Config'
[string "@ElvUI_WindTools/Modules/Skins/Addons/TomCats.lua"]:104: in function <...Ons/ElvUI_WindTools/Modules/Skins/Addons/TomCats.lua:99>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Modules/Skins/Core.lua"]:335: in function `CallLoadedAddon'
[string "@ElvUI_WindTools/Modules/Skins/Core.lua"]:513: in function <ElvUI_WindTools/Modules/Skins/Core.lua:498>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Core/Core.lua"]:111: in function `InitializeModules'
[string "@ElvUI_WindTools/Initialize.lua"]:65: in function `?'
[string "@ElvUI_Libraries/Core/LibElvUIPlugin-1.0-41/LibElvUIPlugin-1.0.lua"]:302: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:298>
[string "=[C]"]: ?
[string "=[C]"]: in function `Initialize'
[string "@ElvUI/Core/init.lua"]:227: in function <ElvUI/Core/init.lua:226>
...
[string "@FrameXML/UIParent.lua"]:542: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:751: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

**Comment by fang2hou** [comment]
confirmed, it will be fixed in 3.29

**Comment by fang2hou** [comment]
fixed in dcd375ce3857b7d3131f3972533261fa2bc273af
