### ISSUE TITLE
[Bug] Disable Talking Heads breaks all audio dialogue

### ISSUE THREAD

**Issue by Phiir42** [fang2hou/ElvUI_WindTools#322]
**Describe the bug**
The "Disable Talking Head" option under Misc mutes dialogue associated with a talking head in addition to repressing the UI. The first time that this occurs in a game session, it will break dialogue audio for all NPCs until the game is restarted. This applies to things like clicking on NPCs, boss dialogue in dungeons and raids, Raszageth's audio cues for the Thundering affix, etc.

**To Reproduce**
1. Select "Disable Talking Head" in Misc.
2. Go to something that triggers a Talking Head, e.g. a world quest.
3. All NPC dialogue audio will now be broken, can be verified by clicking on an NPC. None of the typical audio lines will play.

**Expected behavior**
"Disable Talking Head" should repress the Talking Head UI without affecting all the other dialogue audio in the game.

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: v3.27
 - ElvUI Version: v13.29
 - WoW Build: 10.0.7 (build 48999)

**Additional context**
Verified that this occurs on a fresh installation of WoW with all cvars reset, WTF, Cache, and Interface deleted, with only ElvUI and Windtools installed.

**Comment by fang2hou** [comment]
Thanks for the issue, it will be fixed in the next version.
