### ISSUE TITLE
Friendlist Icon Issue

### ISSUE THREAD

**Issue by RAtwood90** [fang2hou/ElvUI_WindTools#323]
![Windtools (1)](https://user-images.githubusercontent.com/73589071/235987714-aff8094d-1475-48bf-9c86-b79c9f711f99.jpg)
![Windtools (3)](https://user-images.githubusercontent.com/73589071/235987729-ffcfc639-ba31-43fb-839d-cf0a04b1ab09.jpg)
![Windtools](https://user-images.githubusercontent.com/73589071/235987748-a8e57782-2e0c-4004-b5db-b34817c1f4bf.jpg)

I notice some Friendlist Icon Issues may u have an Idea or have to take a look on it.

Also tested it with only ElvUI and Windtools enabled.

**Comment by fang2hou** [comment]
currently cannot fix this because blizzard do not provide any information of other game client.
this issue will be fixed after data mining.
