### ISSUE TITLE
Chat Feature Enhancment Issue

### ISSUE THREAD

**Issue by RAtwood90** [fang2hou/ElvUI_WindTools#324]
![WoWScrnShot_050223_201037](https://user-images.githubusercontent.com/73589071/235988341-b0c39088-4adb-48e6-8df3-bde3b905c623.jpg)
![WoWScrnShot_050223_201048](https://user-images.githubusercontent.com/73589071/235988366-e6cdfbf7-0c95-4d52-ab5d-a46f2e97adbf.jpg)
![WoWScrnShot_050223_201048](https://user-images.githubusercontent.com/73589071/235988678-f81f846e-ccef-4346-9831-95a3a0629c76.jpg)

There is an Issue with the Horizontal Space only on Achievement Line.

It's not Anchor to the left Side cause the Free Space (Yellow Cross) is for Brackets (see the Grey Line).

I didn't checked in the Box for "Remove Brackets" so Brackets should be there.

Anyway then you check "Remove Brackets" it should be more Anchor to the left. At the begin of the Chat Line.

As you can see on BNet Online Chat Information (which one is working well)

**Comment by fang2hou** [comment]
the achievement enhancement strings uses the message template provided by windtools rather than blizzrard's one.
(windtools strongly recommend no brackets style)
but of course, i will add brackets if you are not check the removeBrackets in next version.

**Comment by fang2hou** [comment]
added in 417b093f
