### ISSUE TITLE
[Bug] Issue with Weakaura Options

### ISSUE THREAD

**Issue by Theni224** [fang2hou/ElvUI_WindTools#325]
**Describe the bug**
When you open the weakaura options with /wa in-game and have skinning enabled in windtools, you get a lua error.

**Additional context**

`1x ..._WindTools/Modules/Skins/Addons/WeakAurasOptions.lua:487: attempt to call method 'SetBackdrop' (a nil value)
[string "@ElvUI_WindTools/Modules/Skins/Addons/WeakAurasOptions.lua"]:487: in function <..._WindTools/Modules/Skins/Addons/WeakAurasOptions.lua:480>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `ShowOptions'
[string "@WeakAurasOptions/WeakAurasOptions.lua"]:612: in function `ToggleOptions'
[string "@WeakAuras/WeakAuras.lua"]:155: in function `OpenOptions'
[string "@WeakAuras/WeakAuras.lua"]:197: in function `?'
[string "@FrameXML/ChatFrame.lua"]:5236: in function <FrameXML/ChatFrame.lua:5182>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4894: in function `ChatEdit_SendText'
[string "@FrameXML/ChatFrame.lua"]:4930: in function <FrameXML/ChatFrame.lua:4926>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:141_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:141_OnEnterPressed"]:1>

Locals:
self = <table> {
 CreateLowerShadow = <function> defined @ElvUI_WindTools/Modules/Skins/Core.lua:99
 TalkingHead = <function> defined @ElvUI_WindTools/Modules/Skins/Blizzard/TalkingHead.lua:6
 UpdateShadowColor = <function> defined @ElvUI_WindTools/Modules/Skins/Core.lua:118
 HandleMerchantItem = <function> defined @ElvUI_WindTools/Modules/Skins/Blizzard/Merchant.lua:8
 ElvUI_AFK = <function> defined @ElvUI_WindTools/Modules/Skins/ElvUI/AFK.lua:7
 modules = <table> {
 }
 CancelTimer = <function> defined @ElvUI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:147
 GuildInviteFrame = <function> defined @ElvUI_WindTools/Modules/Skins/Blizzard/Guild.lua:6
 MirrorTimers = <function> defined @ElvUI_WindTools/Modules/Skins/Blizzard/MirrorTimers.lua:7
 RaiderIO = <function> defined @ElvUI_WindTools/Modules/Skins/Addons/RaiderIO.lua:106
 SkinCriteriaAlert = <function> defined @ElvUI_WindTools/Modules/Skins/Blizzard/Alerts.lua:63
 RaidUtility_ShowButton_OnClick = <function> defined @ElvUI_WindTools/Modules/Skins/ElvUI/RaidUtility.lua:9
 Blizzard_LossOfControlFrame_SetUpDisplay = <function> defined @ElvUI_WindTools/Modules/Skins/Blizzard/LossOfControl.lua:6
 ElvUI_TotemTracker_Initialize = <function> defined @ElvUI_WindTools/Modules/Skins/ElvUI/TotemTracker.lua:8
 Blizzard_WeeklyRewards = <function> defined @ElvUI_WindTools/Modules/Skins/Blizzard/WeeklyRewards.lua:6
 OmniCD_Party_ExtraBars = <function> defined @ElvUI_WindTools/Modules/Skins/Addons/OmniCD.lua:40
 Blizzard_PlayerChoice = <function> defined @ElvUI_WindTools/Modules/Skins/Blizzard/PlayerChoice.lua:26
 SkinItemButton = <function> defined @ElvUI_WindTools/Modules/Skins/Blizzard/ObjectiveTracker.lua:24
 UpdateFriendButton = <function> defined @ElvUI_WindTools/Modules/Skins/Blizzard/Friends.lua:9
 ADDON_LOADED = <function> defined @ElvUI_WindTools/Modules/Skins/Core.lua:345
 WeakAurasIconButton = <function> defined @ElvUI_WindTools/Modules/Skins/Addons/WeakAurasOptions.lua:438
 ElvUI_CastBars = <function> defined @ElvUI_WindTools/Modules/Skins/ElvUI/CastBars.lua:59
 SettingsPanel = <function> defined @ElvUI_WindTools/Modules/Skins/Blizzard/SettingsPanel.lua:8
 TutorialFrame = <function> defined @ElvUI_WindTools/Modules/Skins/Blizzard/Tutorial.lua:6
 ElvUI_TotemTracker = <function> defined @ElvUI_WindTools/Modules/Skins/ElvUI/TotemTracker.lua:18
 SetEnabledState = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:273
 enteredLoad = <table> {
 }
 DressUpFrame = <function> defined @ElvUI_WindTools/Modules/Skins/Blizzard/DressingRoom.lua:6
 TomCats_HeaderCollapseButton_SetNormalAtlas = <function> defined @ElvUI_WindTools/Modules/Skins/Addons/TomCats.lua:67
 BigWigs_Plugins = <function> defined @ElvUI_WindTools/Modules/Skins/Addons/BigWigs.lua:264
 Blizzard_AnimaDiversionUI = <function> defined @ElvUI_WindTools/Modules/Skins/Blizzard/AnimaDiversion.lua:6
 UnregisterAllEvents = <function> defined @Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 Blizzard_ItemInteractionUI = <function> defined @ElvUI_WindTools/Modules/Skins/Blizzard/ItemInteraction.lua:6
 Blizzard_ProfessionsCustomerOrders = <function> defined @ElvUI_WindTools/Modules/Skins/Blizzard/ProfessionsCustomerOrders.lua:8
 ElvUI_UnitFrames_Construct_AuraBars = <function> defined @ElvUI_WindTools/Modules/Skins/ElvUI/UnitFrames.lua:84
 SkinWorldQuestCompleteAlert = <function> defined @ElvUI_WindTools/Modules/Skins/Blizzard/Alerts.lua:174
 Wea`

**Comment by fang2hou** [comment]
fixed in eda36e8a
