### ISSUE TITLE
[Bug] Tooltip wrong on Crests

### ISSUE THREAD

**Issue by Jaidy88** [fang2hou/ElvUI_WindTools#328]
**Describe the bug**
The tooltip of my inventory about the Shadowflame Crests, is unfortunately no longer readable. 

**To Reproduce**
1.  Load Elvui + Windtools
2. Error exists von the Crests Items
3. see error
4.Deavtivate Windtools will stop this issue its not a bag addon problem

**Screenshots**
[https://gyazo.com/60dfbb6931eb43250074d791b1225687](url)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 10.05.23 3.31
 - ElvUI Version 13.32
 -

**Comment by fang2hou** [comment]
You cannot use these two together.
