### ISSUE TITLE
[Bug] ERROR

### ISSUE THREAD

**Issue by Imna1975** [fang2hou/ElvUI_WindTools#331]
2x WindTools [ERROR]
...ElvUI_WindTools/Modules/Skins/Addons/Auctionator.lua:447: Usage: hooksecurefunc([table,] "function", hookfunc)
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Modules/Skins/Addons/Auctionator.lua"]:447: in function <...ElvUI_WindTools/Modules/Skins/Addons/Auctionator.lua:422>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Modules/Skins/Core.lua"]:335: in function `CallLoadedAddon'
[string "@ElvUI_WindTools/Modules/Skins/Core.lua"]:513: in function <ElvUI_WindTools/Modules/Skins/Core.lua:498>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Core/Core.lua"]:111: in function `InitializeModules'
[string "@ElvUI_WindTools/Initialize.lua"]:69: in function `?'
[string "@ElvUI_Libraries/Core/LibElvUIPlugin-1.0-42/LibElvUIPlugin-1.0.lua"]:303: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:299>
[string "=[C]"]: in function `Initialize'
[string "@ElvUI/Core/init.lua"]:265: in function <ElvUI/Core/init.lua:264>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
(*temporary) = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined =[C]:-1
 ERR_OUT_OF_CHI = "Nicht genügend Chi"
 DH_HAVOC_CORE_ABILITY_2 = "Starker Nahkampfangriff. Verbraucht Jähzorn. Kritische Treffer erstatten einen Teil des Jähzorns zurück."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 SettingsSliderOptionsMixin = <table> {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Namen von Einheiten einfärben."
 ElvUI_Bar5Button11Count = ElvUI_Bar5Button11Count {
 }
 HUD_EDIT_MODE_SETTING_ACTION_BAR_HIDE_BAR_ART = "Leistenverzierung verbergen"
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 774
 SPELL_FAILED_CUSTOM_ERROR_71 = "Dieser Partygast möchte mit Euch tanzen."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 417
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Für diese Community können keine weiteren Einladungslinks generiert werden."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "Mit von Euch angelegten Taschen könnt Ihr nicht handeln."
 PVP_RANK_6_1 = "Fußknecht"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "Standardmäßig links von der rechten Aktionsleiste 1 platziert"
 ElvUI_Bar6Button9Shine = ElvUI_Bar6Button9Shine {
 }
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 371
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 PROFESSIONS_COLUMN_REAGENTS_NONE = "Keine"
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Vordefinierte Tastaturbelegungen für Aktionen reagieren bei gedrückter statt bei losgelassener Taste."
 BINDING_NAME_NAMEPLATES = "Namensplaketten von gegnerischen Einheiten anzeigen"
 CHAT_HEADER_SUFFIX = ": "
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 COVENANT_MISSIONS_HEALTH = "Gesundheit"
 MAIL_LETTER_TOOLTIP = "Klicken, um eine dauerhafte
Kopie dieses Briefs anzufertigen."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML/UnitFrame.lua:898
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 MultiBar6Button4Flash = MultiBar6Button4Flash {
 }
 DUNGEON_FLOOR_UPPERBLACKROCKSPIRE3 = "Schwarzfausthalle"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 ClassNameplateBarPaladinFrameRune5 = ClassNameplateBarPaladinFrameRune5 {
 }
 FCFDockOverflowButton_OnClick = <function> defined @FrameXML/FloatingChatFrame.lua:2388
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 MoneyFrame_OnEvent = <function> defined @FrameXML/MoneyFrame.lua:202
 BN_UNABLE_TO_RESOLVE_NAME = "'%s' kann nicht angeflüstert werden. Möglicherweise sind die Blizzard-Dienste nicht verfügbar."
 AutoCompleteEditBox_OnKeyDown = <function> defined @FrameXML/AutoComplete.lua:368
 ElvUI_Bar5Button12Shine7 = ElvUI_Bar5Button12Shine7 {
 }
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 36
 INT_SPELL_DURATION_HOURS = "%d |4Stunde:Stunden;"
 ToggleEncounterJournal = <function> defined @FrameXML/UIParent.lua:1137
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Verängstigt"
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 ROGUE_COMBAT_CORE_ABILITY_4 = "Nahkampfangriff. Verbraucht Combopunkte."
 JoinSkirmish = <function> defined =[C]:-1
 MultiBarRightButton7Shine9 = MultiBarRightButton7Shine9 {
 }
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 ElvUI_Bar6Button6 = ElvUI_Bar6Button6 {
 }
 AUCTIONATOR_L_DEFAULT_LIST_HEADER = "Standard Einkaufsliste"
 DMG_LCD = "SCHA"
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 RaidUtility_CloseButton = RaidUtility_CloseButton {
 }
 Is64BitClient = <function> defined =[C]:-1
 SecureCmdItemParse = <function> defined @FrameXML/ChatFrame.lua:1165
 SLASH_STOPATTACK1 = "/angriffstop"
 MultiCastActionButton4HotKey = MultiCastActionButton4HotKey {
 }
 MultiBar5B

**Comment by fang2hou** [comment]
fixed in 88aa2011
