### ISSUE TITLE
[Bug] Localization Mistake German Mass Taunt

### ISSUE THREAD

**Issue by Faydz** [fang2hou/ElvUI_WindTools#335]
**Describe the bug**

Localization Mistake German Mass Taunt

**To Reproduce**

WindTools
Ankündigungen (Announcement)
Spotte (Taunt)
Spotte Alle (Taunt all)
Text
"Ich habe alle Feine gespottet"

**Expected behavior**

Should be:
"Ich habe alle Feinde gespottet"

there is a d missing

**Comment by fang2hou** [comment]
fixed!
thanks for you report
