### ISSUE TITLE
Feature Request: Researchers Under Fire in Event Tracker

### ISSUE THREAD

**Issue by fubaWoW** [fang2hou/ElvUI_WindTools#336]
hi there,

maybe you can add the Researchers Under Fire Event to your Event Tracker?
would be very nice!

thanks :)

did a working Pull Request here:
https://github.com/fang2hou/ElvUI_WindTools/pull/342

**Comment by fang2hou** [comment]
looks good, i will try to add it in 3.34.
❤️

**Comment by fubaWoW** [comment]
> looks good, i will try to add it in 3.34.
> ❤️
yeah but the "questID" is wrong and also all other questID's i've tested can not be checked by the default ``C_QuestLog.IsQuestFlaggedCompleted`` function.

tried a few hours to figure out Blizzard do this on the "Researchers Under Fire" Tooltip but really no clue at all...

**Comment by fubaWoW** [comment]
Well...
I've now figured out how it work and i did a Pull-Request with the new Timers *yey* 👌
Maybe you can take a look into it, especially for the Localization!

**Comment by fang2hou** [comment]
Thanks!
