### ISSUE TITLE
[Bug] Tom Cat Skin Issue

### ISSUE THREAD

**Issue by Fizgig1973** [fang2hou/ElvUI_WindTools#337]
**Describe the bug**
Skin related error after Tomcat's Tours addon is updated.

**To Reproduce**
Occurs when the skin is applied after accessing the game.

**Expected behavior**

**Screenshots**

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 3.32
 - ElvUI Version 13.35
 - WoW Build 10.1

**Additional context**

1x ElvUI_WindTools/Modules/Skins/Addons/Load_Addons.xml:22 Error loading ElvUI_WindTools/TomCats.lua

1x Interface\FrameXML\Bindings.xml:1 ElvUI_WindTools/Modules/Skins/Addons/Load_Addons.xml:22 Error loading ElvUI_WindTools/TomCats.lua

**Comment by fang2hou** [comment]
it seems you delete the tomcats.lua, please reinstall windtools with the addon manager like curse, wago addon, etc.
