### ISSUE TITLE
[Bug] Windtools does not show up.

### ISSUE THREAD

**Issue by NeeFoo** [fang2hou/ElvUI_WindTools#343]
Windtools does not show up in ElvUI and i cannot access its settings.
I can see it enabled in the addons list.

Both ElvUI and Windtools are updated to the latest versions.

**Comment by fang2hou** [comment]
only enable elvui & windtools to re-check.
some other elvui plugins may broken the whole elvui module system

**Comment by NeeFoo** [comment]
BenikUI caused the issue.

**Comment by fang2hou** [comment]
Yeah, just wait for benik update his addon.
