### ISSUE TITLE
[Bug] PlayerChoice.lua errors while having the shadow skin option off

### ISSUE THREAD

**Issue by midnightgirlj** [fang2hou/ElvUI_WindTools#344]
**Describe the bug**
Under Skins in Windtools, there's an option to turn on/off (enable/disable) Shadow for the UI. I have turned this off because it makes the UI look blurry to me even when the size is set to 0. Since turning this off, I have consistent lua errors anytime a "player choice" panel comes up.... so Torghast abilities (when I first had the errors), picking a perk from Cobalt Assembly or Time Rifts, picking a faction at Forbidden Reach, etc. It's been happening consistently with shadows disabled and a player choice panel. I get exactly the same error with debug mode (/wtdebug on) too.

**To Reproduce**
Skins in Windtools and turn "shadow" to off (unclick enable) and reload

Anything that will create a player choice panel, like Time Rift orbs or the table to pick a faction on Forbidden Reach or Cobalt Assembly ability choices and you will get a the following lua error below

3. See error:
UI_WindTools/Modules/Skins/Blizzard/PlayerChoice.lua:13: attempt to index field 'shadow' (a nil value)
[string "@ElvUI_WindTools/Modules/Skins/Blizzard/PlayerChoice.lua"]:13: in function <...UI_WindTools/Modules/Skins/Blizzard/PlayerChoice.lua:7>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetupOptions'
[string "@Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua"]:140: in function `TryShow'
[string "@FrameXML/UIParent.lua"]:2285: in function <FrameXML/UIParent.lua:1420>
[string "=[C]"]: ?

Locals:
frame = PlayerChoiceFrame {
 IsLayoutFrame = <function> defined @SharedXML/LayoutFrame.lua:36
 OnSelectionMade = <function> defined @Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua:221
 optionFrameTemplate = "PlayerChoiceGenericPowerChoiceOptionTemplate"
 SetupFrame = <function> defined @Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua:249
 GetTextureKitInfo = <function> defined @Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua:110
 GetChildPadding = <function> defined @SharedXML/LayoutFrame.lua:150
 OnCleaned = <function> defined @SharedXML/LayoutFrame.lua:131
 OnCloseUIFromExitButton = <function> defined @Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua:227
 TryShow = <function> defined @Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua:121
 GetPlayerChoiceOptionHeightData = <function> defined @Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua:296
 alignedSectionMaxHeights = <table> {
 }
 expand = true
 OnShow = <function> defined @Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua:165
 rightPadding = 65
 optionPools = <table> {
 }
 leftPadding = 65
 LayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:280
 bottomPadding = 120
 choiceInfo = <table> {
 }
 topPadding = 120
 Header = Frame {
 }
 optionsAligned = true
 textureKitInfo = <table> {
 }
 isLegacy = false
 uiTextureKit = "genericplayerchoice"
 GetObjectGUID = <function> defined @Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua:149
 BlackBackground = Frame {
 }
 AreOptionsAligned = <function> defined @Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua:350
 ResetPlayerChoiceOptionHeightData = <function> defined @Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua:292
 FadeOutAllOptions = <function> defined @Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua:215
 MarkDirty = <function> defined @SharedXML/LayoutFrame.lua:99
 Title = Frame {
 }
 CalculateFrameSize = <function> defined @SharedXML/LayoutFrame.lua:165
 AddLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:55
 Background = Frame {
 }
 NineSlice = Frame {
 }
 IsLegacy = <function> defined @Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua:354
 spacing = 20
 OnUpdate = <function> defined @SharedXML/LayoutFrame.lua:93
 GetLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:73
 BorderLayerModelScene = ModelScene {
 }
 AlignOptionHeights = <function> defined @Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua:328
 GetAdditionalRegions = <function> defined @SharedXML/LayoutFrame.lua:85
 onCloseCallback = <function> defined @SharedXML/FunctionUtil.lua:89
 IsDirty = <function> defined @SharedXML/LayoutFrame.lua:127
 OnLoad = <function> defined @Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua:3
 OnHide = <function> defined @Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua:189
 Layout = <function> defined @SharedXML/LayoutFrame.lua:187
 0 = <userdata>
 OnEvent = <function> defined @Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua:8
 GetPadding = <function> defined @SharedXML/LayoutFrame.lua:141
 CloseButton = Button {
 }
 SetupTextureKits = <function> defined @Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua:115
 MarkClean = <function> defined @SharedXML/LayoutFrame.lua:117
 MarkIgnoreInLayout = <function> defined @SharedXML/LayoutFrame.lua:44
 fixedWidth = 100
 SetupOptions = <function> defined =[C]:-1
 IgnoreLayoutIndex = <function> defined @SharedXML/LayoutFrame.lua:40
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = PlayerChoiceFrame {
 IsLayoutFrame = <function> defined @SharedXML/LayoutFrame.lua:36
 OnSelectionMade = <function> defined @Blizzard_PlayerChoice/Blizzard_PlayerChoice.lua:221
 optionFrameTemplate = "PlayerCho

**Expected behavior**
I would like to keep the shadow affect disabled on my UI while not having lua errors during player choice panels because the shadow effect looks blurry and hurts my eyes.

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 3.34
 - ElvUI Version: 13.38
 - WoW Build: 10.1.5 (50585)

**Additional context**
The option "WeakAuras Shadows" does not seem to have an effect on this error at all, off or on it doesn't cause the lua error, only when Shadow is disabled and a player choice panel pops up.

**Comment by fang2hou** [comment]
Fixed!
Thanks for your reporting.
