### ISSUE TITLE
Skin for Auctionator won't work [Bug]

### ISSUE THREAD

**Issue by degedd** [fang2hou/ElvUI_WindTools#346]
The window to sell is in background just adjust the layer 

![Bild_2023-08-19_124447588](https://github.com/fang2hou/ElvUI_WindTools/assets/44030478/55e79355-a592-43e0-a7a9-7c73a3b85ad1)

**Comment by fang2hou** [comment]
Try test with `/wtdebug on`
There is no additional overlay in my game.

**Comment by lipelipe2** [comment]
Hello windtools + paste addon is causing this on my ui. Check if you have same addons

**Comment by duckies** [comment]
> Hello windtools + paste addon is causing this on my ui. Check if you have same addons

I can confirm this. Paste is also causing issues with the shadow frame levels, probably due to the libraries included being ancient. If you enjoy Paste, there's an updated version called [Paste NG](https://www.curseforge.com/wow/addons/pasteng).
