### ISSUE TITLE
[Bug] Wow crash upon loading into game

### ISSUE THREAD

**Issue by Konsafloof** [fang2hou/ElvUI_WindTools#350]
**Describe the bug**
Upon loading into character wow crashes

**To Reproduce**
1. Enable addon
2. Load into WoW
3. Wow Crashes

**Expected behavior**
WoW not crash

**Screenshots**
![Wow_P8LcIXVrGS](https://github.com/fang2hou/ElvUI_WindTools/assets/109347817/edcb2043-c0ae-4e3d-8a2d-5b3fa55487ef)

**Information (you can find these in [WindTools-Information]):**
 - 3.35-fix-1
 - 13.40
 - 10.1.7.51187

**Additional context**
[2023-09-06 08.58.45 Crash - 18228.txt](https://github.com/fang2hou/ElvUI_WindTools/files/12537555/2023-09-06.08.58.45.Crash.-.18228.txt)

**Comment by fang2hou** [comment]
I wasn't able to replicate the issue on my end.
Generally, memory errors occur when the client files are corrupted. Have you tried fixing the game with Battle.net?

**Comment by Flamanis** [comment]
Error is in GetItemStats (Blizzard Function), when it is trying to lookup one of the items you have equipped. It is a Blizzard issue. Try repairing your game, and/or report it to them.

You can verify this fact by mousing over all of your items after loading back in. One of them will crash the game. One user from Details had it occur on a pair of TBC crafted mail boots. Earthen Netherscale Boots

**Comment by Flamanis** [comment]
Narrowed it down to any item with specific speed increase effect.

https://github.com/Stanzilla/WoWUIBugs/issues/471

**Comment by Flamanis** [comment]
Looks to be fixed at least with my one testing item. I can compare them in my bags and it does not crash anymore. So GetItemStats should be fine.

Should be good to close.
