### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Milky063** [fang2hou/ElvUI_WindTools#351]
**Describe the bug**
Just log into the game and this pops up. 

**To Reproduce**

**Expected behavior**
not to happen.

**Screenshots**

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: [e.g. 2.00] ElvUI_WindTools-3.35-fix-1.zip
 - ElvUI Version [e.g. 12.00]  version: 13.40
 - WoW Build [e.g. 9.0.1 (25600)] build: 10.1.7.51237

**Additional context**
4x WindTools [ERROR]
...dOns/ElvUI_WindTools/Modules/Skins/Blizzard/Misc.lua:32: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@AdiBags/libs/AceHook-3.0-9/AceHook-3.0.lua"]:210: in function <...faceAdiBags/libs/AceHook-3.0/AceHook-3.0.lua:118>
[string "@AdiBags/libs/AceHook-3.0-9/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@ElvUI_WindTools/Modules/Skins/Blizzard/Misc.lua"]:32: in function <...dOns/ElvUI_WindTools/Modules/Skins/Blizzard/Misc.lua:23>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Modules/Skins/Core.lua"]:505: in function <ElvUI_WindTools/Modules/Skins/Core.lua:498>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Core/Core.lua"]:111: in function `InitializeModules'
[string "@ElvUI_WindTools/Initialize.lua"]:69: in function `?'
[string "@ElvUI_Libraries/Core/LibElvUIPlugin-1.0-42/LibElvUIPlugin-1.0.lua"]:303: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:299>
[string "=[C]"]: in function `Initialize'
[string "@ElvUI/Core/init.lua"]:275: in function <ElvUI/Core/init.lua:274>
...
[string "@FrameXML/UIParent.lua"]:752: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
(*temporary) = "Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target"

**Comment by Jaidy88** [comment]
2x WindTools [ERROR]
...dOns/ElvUI_WindTools/Modules/Skins/Blizzard/Misc.lua:32: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:210: in function <...lvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@ElvUI_Libraries/Core/Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@ElvUI_WindTools/Modules/Skins/Blizzard/Misc.lua"]:32: in function <...dOns/ElvUI_WindTools/Modules/Skins/Blizzard/Misc.lua:23>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Modules/Skins/Core.lua"]:505: in function <ElvUI_WindTools/Modules/Skins/Core.lua:498>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Core/Core.lua"]:111: in function `InitializeModules'
[string "@ElvUI_WindTools/Initialize.lua"]:69: in function `?'
[string "@ElvUI_Libraries/Core/LibElvUIPlugin-1.0-42/LibElvUIPlugin-1.0.lua"]:303: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:299>
[string "=[C]"]: in function `Initialize'
[string "@ElvUI/Core/init.lua"]:275: in function <ElvUI/Core/init.lua:274>
...
[string "@FrameXML/UIParent.lua"]:547: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:752: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
(*temporary) = "Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target"

**Comment by fang2hou** [comment]
fixed in 3.36
