### ISSUE TITLE
[Bug]Recent WeakAura update broken WeakAura skins

### ISSUE THREAD

**Issue by Konsafloof** [fang2hou/ElvUI_WindTools#353]
**Describe the bug**
Recent Weakaura updates, Weakauras-5.7.2 and Weakauras-5.8.0

**To Reproduce**
1. Download newer Weakaura updates
2. Enable Weakaura skins in Windtools

**Expected behavior**
Weakaura skin works properly
Works properly with Weakauras-5.7.1

**Screenshots**
After
![Wow_Ktvc16uGqC](https://github.com/fang2hou/ElvUI_WindTools/assets/109347817/4fc71c11-091a-46b7-a2d2-3c69c36312e9)

Before
![Wow_clv8EIhGU9](https://github.com/fang2hou/ElvUI_WindTools/assets/109347817/c5ae120f-e65e-4e33-aa4a-0fe853b1232a)

**Information (you can find these in [WindTools-Information]):**
 - Weakauras Versions 5.7.1, 5.7.2, 5.8.0
 - ElvUI Version 13.42
 - WoW Build 10.1.7.51536

**Additional context**
3x WindTools [ERROR]
...s/ElvUI_WindTools/Modules/Skins/Addons/WeakAuras.lua:201: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:210: in function <...lvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@ElvUI_Libraries/Core/Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@ElvUI_WindTools/Modules/Skins/Addons/WeakAuras.lua"]:201: in function <...s/ElvUI_WindTools/Modules/Skins/Addons/WeakAuras.lua:181>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Modules/Skins/Core.lua"]:335: in function `CallLoadedAddon'
[string "@ElvUI_WindTools/Modules/Skins/Core.lua"]:513: in function <ElvUI_WindTools/Modules/Skins/Core.lua:498>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Core/Core.lua"]:111: in function `InitializeModules'
[string "@ElvUI_WindTools/Initialize.lua"]:69: in function `?'
[string "@ElvUI_Libraries/Core/LibElvUIPlugin-1.0-42/LibElvUIPlugin-1.0.lua"]:303: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:299>
[string "=[C]"]: in function `Initialize'
...
[string "@FrameXML/UIParent.lua"]:547: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:752: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
(*temporary) = "Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target"

**Comment by fang2hou** [comment]
Unfortunately, WeakAuras2 blocks the skinning, so the problem cannot be solved.
https://github.com/WeakAuras/WeakAuras2/commit/de7f8e29114bf52713d803251fdfdb12fda750e5
