### ISSUE TITLE
[Bug] auctionator skin causes error

### ISSUE THREAD

**Issue by jisamcom** [fang2hou/ElvUI_WindTools#354]
**To Reproduce**
1. after game is loaded.

**Information (you can find these in [WindTools-Information]):**
 - Addon Version:   Auctionator : 10.1.24
 - ElvUI Version 13.44
 - WoW Build  3.99

**Additional context**
after today's auctionator update, skin causes error.

1x WindTools [ERROR]
...ElvUI_WindTools/Modules/Skins/Addons/Auctionator.lua:410: Usage: hooksecurefunc([table,] "function", hookfunc)
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Modules/Skins/Addons/Auctionator.lua"]:410: in function <...ElvUI_WindTools/Modules/Skins/Addons/Auctionator.lua:402>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Modules/Skins/Core.lua"]:335: in function `CallLoadedAddon'
[string "@ElvUI_WindTools/Modules/Skins/Core.lua"]:513: in function <ElvUI_WindTools/Modules/Skins/Core.lua:498>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Core/Core.lua"]:111: in function `InitializeModules'
[string "@ElvUI_WindTools/Initialize.lua"]:69: in function `?'
[string "@ElvUI_Libraries/Core/LibElvUIPlugin-1.0-42/LibElvUIPlugin-1.0.lua"]:303: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:299>
[string "=[C]"]: in function `Initialize'
[string "@ElvUI/Core/init.lua"]:276: in function <ElvUI/Core/init.lua:275>
[string "=[C]"]: ?
...
[string "@FrameXML/UIParent.lua"]:547: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:752: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
(*temporary) = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined =[C]:-1
 ERR_OUT_OF_CHI = "기가 부족합니다."
 DH_HAVOC_CORE_ABILITY_2 = "격노를 소모하는 강력한 근접 공격 능력입니다. 치명타로 적중하면 격노의 일부를 돌려받습니다."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 SettingsSliderOptionsMixin = <table> {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "플레이어, NPC, 몬스터 이름에 색을 입힙니다."
 ElvUI_Bar5Button11Count = ElvUI_Bar5Button11Count {
 }
 HUD_EDIT_MODE_SETTING_ACTION_BAR_HIDE_BAR_ART = "단축바 숨기기"
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 775
 SPELL_FAILED_CUSTOM_ERROR_71 = "파티 하객이 당신과 춤추고 싶어합니다."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 417
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "이 커뮤니티는 초대 링크를 더 생성할 수 없습니다."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "장착 중인 가방은 거래할 수 없습니다."
 PVP_RANK_6_1 = "파수병"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "기본: 우측 행동 단축바 왼쪽에 위치"
 ElvUI_Bar6Button9Shine = ElvUI_Bar6Button9Shine {
 }
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 371
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 PROFESSIONS_COLUMN_REAGENTS_NONE = "없음"
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "단축키를 눌렀다 뗐을 때가 아니라, 누르는 즉시 선택된 행동을 실행합니다."
 BINDING_NAME_NAMEPLATES = "적 이름표 표시"
 INSTANCE_UNAVAILABLE_OTHER_TEMPORARILY_DISABLED = "%s 님이 진입할 수 없습니다. 해당 인스턴스가 임시로 사용 불가 상태입니다."
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 COVENANT_MISSIONS_HEALTH = "생명력"
 MAIL_LETTER_TOOLTIP = "이 편지의 사본을 만들어 영원히
보관하려면 클릭하십시오."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML/UnitFrame.lua:929
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 MultiBar6Button4Flash = MultiBar6Button4Flash {
 }
 MANA = "마나"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 ClassNameplateBarPaladinFrameRune5 = ClassNameplateBarPaladinFrameRune5 {
 }
 FCFDockOverflowButton_OnClick = <function> defined @FrameXML/FloatingChatFrame.lua:2388
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 MoneyFrame_OnEvent = <function> defined @FrameXML/MoneyFrame.lua:202
 BN_UNABLE_TO_RESOLVE_NAME = "'%s' 님께 귓속말을 보낼 수 없습니다. 블리자드 서비스를 이용할 수 없습니다."
 AutoCompleteEditBox_OnKeyDown = <function> defined @FrameXML/AutoComplete.lua:368
 ElvUI_Bar5Button12Shine7 = ElvUI_Bar5Button12Shine7 {
 }
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 36
 INT_SPELL_DURATION_HOURS = "%d시간"
 SLASH_LibQTip1 = "/qtip"
 ToggleEncounterJournal = <function> defined @FrameXML/UIParent.lua:1135
 AdiBagsItemButton4IconQuestTexture = AdiBagsItemButton4IconQuestTexture {
 }
 LOSS_OF_CONTROL_DISPLAY_FEAR = "공포"
 ItemTooltipEnhancer_OPTION_ONXYANNULET = "흑마노 반지 보석 정보 표시"
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 ROGUE_COMBAT_CORE_ABILITY_4 = "연계 점수를 소모하는 근접 공격 능력입니다."
 JoinSkirmish = <function> defined =[C]:-1
 MultiBarRightButton7Shine9 = MultiBarRightButton7Shine9 {
 }
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 ElvUI_Bar6Button6 = ElvUI_Bar6Button6 {
 }
 AUCTIONATOR_L_DEFAULT_LIST_HEADER = "기본 구매목록"
 DMG_LCD = "공"
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 Is6

**Comment by fang2hou** [comment]
fixed in 42ea696fa8edb3d4d4cae9824d79d1fba26cc33c
