### ISSUE TITLE
关于目标距离的信息文字

### ISSUE THREAD

**Issue by LiangYuxuan** [fang2hou/ElvUI_WindTools#36]
之前在使用[ElvUI Enhanced Again (BfA)](https://wow.curseforge.com/projects/elvui-enhanced-again)，它提供了一些信息文字，其中有一个显示目标距离预估的。主要依赖[LibRangeCheck-2.0](https://www.wowace.com/projects/librangecheck-2-0)实现，主体在modules/datatexts/range.lua。

请问能否将其移植到此项目中？

**Comment by fang2hou** [comment]
已經在beta分支中添加
