### ISSUE TITLE
[Bug] Contacts list won't show unless "Update Alts" is enabled

### ISSUE THREAD

**Issue by Squimbert** [fang2hou/ElvUI_WindTools#360]
**Describe the bug**
The new "update alts" option prevents adding more alts, but also incorrectly prevents display of the contacts list on the mail frame when the option is disabled.

**To Reproduce**
1. Disable "update alts" option in windtools > item > contacts
2. reload ui or relog
4. go to a mailbox and see that contacts list is missing

**Expected behavior**
the "update alts" option should not disable the showing of the contacts list

**Screenshots**

![image](https://github.com/fang2hou/ElvUI_WindTools/assets/99698377/df5fee54-57fa-417c-be9e-f0483b7d28b9)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: [3.43]
 - ElvUI Version [13.48]
 - WoW Build 10.2.0 (52106)

**Comment by fang2hou** [comment]
Thanks for your report. It has been fixed in 3673f85d
