### ISSUE TITLE
[Bug] Lua error for pet battle

### ISSUE THREAD

**Issue by ZelsZels** [fang2hou/ElvUI_WindTools#361]
**Describe the bug**

Lua error on pet battle.

7x WindTools [ERROR]
...ceElvUI_WindTools/Modules/Tooltips/Icons.lua:178: attempt to concatenate field '?' (a nil value)
[string "@ElvUI_WindTools/Modules/Tooltips/Icons.lua"]:178: in function <...ceElvUI_WindTools/Modules/Tooltips/Icons.lua:169>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Modules/Tooltips/Core.lua"]:119: in function `InspectInfo'
[string "@ElvUI_WindTools/Modules/Tooltips/Core.lua"]:187: in function <...aceElvUI_WindTools/Modules/Tooltips/Core.lua:180>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:162: in function <SharedXML/Tooltip/TooltipDataHandler.lua:157>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:182: in function <SharedXML/Tooltip/TooltipDataHandler.lua:178>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:218: in function <SharedXML/Tooltip/TooltipDataHandler.lua:208>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:243: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:389: in function <SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function `ProcessInfo'
[string "@FrameXML/GameTooltip.lua"]:1092: in function `SetWorldCursor'
[string "@FrameXML/UIParent.lua"]:1484: in function <FrameXML/UIParent.lua:1407>

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 3.43
 - ElvUI Version 13.48
 - WoW Build 10.2

**Comment by fang2hou** [comment]
fixed in f8e38e82
