### ISSUE TITLE
[Bug] chat lua error with elvui 13.53

### ISSUE THREAD

**Issue by jisamcom** [fang2hou/ElvUI_WindTools#366]
after update elvui to 13.53 infinite error of below.

i had to turn off chatting text option in windtools to not popping up error.

2427x ...eElvUI_WindTools/Modules/Social/ChatText.lua:516: attempt to call method 'GetChatTime' (a nil value)
[string "@ElvUI_WindTools/Modules/Social/ChatText.lua"]:516: in function `AddMessage'
[string "@FrameXML/ChatFrame.lua"]:3509: in function `ChatFrame_DisplayGMOTD'
[string "@FrameXML/ChatFrame.lua"]:3390: in function <FrameXML/ChatFrame.lua:3369>
[string "=(tail call)"]: ?
[string "@ElvUI/Core/Modules/Chat/Chat.lua"]:2714: in function <ElvUI/Core/Modules/Chat/Chat.lua:2706>

Locals:
self = ChatFrame1 {
 SetJustifyV = <function> defined =[C]:-1
 RefreshIfNecessary = <function> defined =[C]:-1
 OnPostShow = <function> defined =[C]:-1
 SetScript = <function> defined =[C]:-1
 CalculateLineAlphaValueFromTimestamp = <function> defined =[C]:-1
 ScrollUp = <function> defined =[C]:-1
 GetSnapOffsets = <function> defined @FrameXML/EditModeSystemTemplates.lua:609
 EditMode_OnResized = <function> defined @FrameXML/EditModeSystemTemplates.lua:1880
 systemInfo = <table> {
 }
 OnFontObjectUpdated = <function> defined =[C]:-1
 IsFrameAnchoredToMe = <function> defined @FrameXML/EditModeSystemTemplates.lua:694
 TrySetCompositeNumberSettingValue = <function> defined @FrameXML/EditModeSystemTemplates.lua:212
 GetFading = <function> defined =[C]:-1
 IsTextCopyable = <function> defined =[C]:-1
 BaseAddMessage = <function> defined =[C]:-1
 shouldFadeAfterInactivity = true
 SetIndentedWordWrap = <function> defined =[C]:-1
 GetJustifyV = <function> defined =[C]:-1
 ScrollToBottom = <function> defined =[C]:-1
 GetMaxLines = <function> defined =[C]:-1
 GetSelectionOffset = <function> defined @FrameXML/EditModeSystemTemplates.lua:540
 font = "Fonts_Extra\Pretendard-Bold.otf"
 ResetToDefaultPosition = <function> defined @FrameXML/EditModeSystemTemplates.lua:254
 GetScaledSelectionSides = <function> defined @FrameXML/EditModeSystemTemplates.lua:532
 GetIndentedWordWrap = <function> defined =[C]:-1
 SelectSystem = <function> defined @FrameXML/EditModeSystemTemplates.lua:763
 GetFont = <function> defined =[C]:-1
 GetFrameMagneticEligibility = <function> defined @FrameXML/EditModeSystemTemplates.lua:714
 SetMaxLines = <function> defined =[C]:-1
 CalculateSelectingCharacterIndicesForVisibleLine = <function> defined =[C]:-1
 OnPostUpdate = <function> defined =[C]:-1
 RefreshDisplay = <function> defined =[C]:-1
 SetFontObject = <function> defined =[C]:-1
 IsBelowFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:499
 SetOnScrollChangedCallback = <function> defined =[C]:-1
 HasActiveChanges = <function> defined @FrameXML/EditModeSystemTemplates.lua:381
 GetScaledCenter = <function> defined @FrameXML/EditModeSystemTemplates.lua:525
 overrideFadeTimestamp = 0
 DoesSettingDisplayValueEqual = <function> defined @FrameXML/EditModeSystemTemplates.lua:445
 MarkDisplayDirty = <function> defined =[C]:-1
 UpdateDisplayInfoOptions = <function> defined @FrameXML/EditModeSystemTemplates.lua:456
 SetScaleBase = <function> defined =[C]:-1
 GetMessageInfo = <function> defined =[C]:-1
 GetOnScrollChangedCallback = <function> defined =[C]:-1
 ProcessMovementKey = <function> defined @FrameXML/EditModeSystemTemplates.lua:39
 GetSettingValueBool = <function> defined @FrameXML/EditModeSystemTemplates.lua:436
 AtTop = <function> defined =[C]:-1
 GetFontObject = <function> defined =[C]:-1
 defaultLanguage = "오크어"
 historyBuffer = <table> {
 }
 oldestFadingLineTimestamp = 1032935.135000
 fontStringPool = <table> {
 }
 DoesSettingValueEqual = <function> defined @FrameXML/EditModeSystemTemplates.lua:440
 styled = true
 CanEffectivelyFade = <function> defined =[C]:-1
 isDocked = 1
 fontSize = 12
 ShouldResetSettingsDialogAnchors = <function> defined @FrameXML/EditModeSystemTemplates.lua:168
 AtBottom = <function> defined =[C]:-1
 OnPreSizeChanged = <function> defined =[C]:-1
 dirtySettings = <table> {
 }
 OnPostMouseUp = <function> defined =[C]:-1
 IsToTheLeftOfFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:481
 GetSettingsDialogAnchor = <function> defined @FrameXML/EditModeSystemTemplates.lua:465
 hasActiveChanges = false
 OnSystemLoad = <function> defined @FrameXML/EditModeSystemTemplates.lua:3
 ClearFrameSnap = <function> defined @FrameXML/EditModeSystemTemplates.lua:653
 GetCombinedCenterOffset = <function> defined @FrameXML/EditModeSystemTemplates.lua:596
 SetupSettingsDialogAnchor = <function>

**Comment by free4one** [comment]
You can temporarily change the code at line 516 to the following:
local timeStamp = BetterDate(CH.db.timeStampFormat, historyTimestamp or E:GetDateTime(CH.db.timeStampLocalTime, true))

**Comment by fang2hou** [comment]
this issue already fixed in dev branch brefore, i will release the new version later
