### ISSUE TITLE
3 lua errors

### ISSUE THREAD

**Issue by Squimbert** [fang2hou/ElvUI_WindTools#369]
2x SharedXML/TableUtil.lua:249: bad argument #1 to 'pairs' (table expected, got nil)
[string "@SharedXML/TableUtil.lua"]:249: in function `MergeTable'
[string "@Blizzard_Deprecated/Deprecated_10_2_5.lua"]:19: in function <...aceBlizzard_Deprecated/Deprecated_10_2_5.lua:16>
[string "@ElvUI_WindTools/Libraries/LibOpenRaid/GetPlayerInformation.lua"]:379: in function `GetPlayerGemsAndEnchantInfo'
[string "@ElvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua"]:1684: in function `GetPlayerFullGearInfo'
[string "@ElvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua"]:1094: in function <...lvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua:1086>
[string "=[C]"]: in function `xpcall'
[string "@ElvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua"]:590: in function <...lvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua:575>

Locals:
destination = <table> {
}
source = nil

2x SharedXML/TableUtil.lua:249: bad argument #1 to 'pairs' (table expected, got nil)
[string "@SharedXML/TableUtil.lua"]:249: in function `MergeTable'
[string "@Blizzard_Deprecated/Deprecated_10_2_5.lua"]:19: in function <...aceBlizzard_Deprecated/Deprecated_10_2_5.lua:16>
[string "@ElvUI_WindTools/Libraries/LibOpenRaid/GetPlayerInformation.lua"]:379: in function `GetPlayerGemsAndEnchantInfo'
[string "@ElvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua"]:1684: in function `GetPlayerFullGearInfo'
[string "@ElvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua"]:1094: in function <...lvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua:1086>
[string "=[C]"]: in function `xpcall'
[string "@ElvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua"]:590: in function <...lvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua:575>

Locals:
destination = <table> {
}
source = nil

openRaidLib: error on scheduler: sendAllPlayerCooldowns_Schedule [string "@Interface/AddOns/ElvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua"]:624: in function `NewUniqueTimer'
[string "@Interface/AddOns/ElvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua"]:2147: in function <...lvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua:2145>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/ElvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua"]:590: in function <...lvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua:575>

**Comment by fang2hou** [comment]
fixed in 3fffd9c4cc2759925cf26aa8802871c5b5ddc526
