### ISSUE TITLE
[Bug]as soon as you enter a dungeon

### ISSUE THREAD

**Issue by Imna1975** [fang2hou/ElvUI_WindTools#370]
86x bad argument #3 to '?' (outside of expected range 0 to 4294967295 - Usage: local outContinuationToken, (slots)* = C_UnitAuras.GetAuraSlots(unitToken [, filter, maxSlots, continuationToken]))
[string "@FrameXML/AuraUtil.lua"]:83: in function `ForEachAura'
[string "@ElvUI_WindTools/Libraries/LibOpenRaid/GetPlayerInformation.lua"]:746: in function <...Tools/Libraries/LibOpenRaid/GetPlayerInformation.lua:728>
[string "@ElvUI_WindTools/Libraries/LibOpenRaid/GetPlayerInformation.lua"]:776: in function `GetPlayerCooldownStatus'
[string "@ElvUI_WindTools/Libraries/LibOpenRaid/GetPlayerInformation.lua"]:471: in function <...Tools/Libraries/LibOpenRaid/GetPlayerInformation.lua:470>
[string "@ElvUI_WindTools/Libraries/LibOpenRaid/GetPlayerInformation.lua"]:695: in function `GetPlayerCooldownList'
[string "@ElvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua"]:2357: in function `UpdatePlayerCooldownsLocally'
[string "@ElvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua"]:1099: in function <...lvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua:1086>
[string "=[C]"]: in function `xpcall'
[string "@ElvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua"]:590: in function <...lvUI_WindTools/Libraries/LibOpenRaid/LibOpenRaid.lua:575>

Locals:
unit = "player"
filter = "HELPFUL"
maxCount = false
func = <function> defined @ElvUI_WindTools/Libraries/LibOpenRaid/GetPlayerInformation.lua:716
usePackedAura = true
continuationToken = nil
(*temporary) = <function> defined @FrameXML/AuraUtil.lua:56
(*temporary) = "player"
(*temporary) = "HELPFUL"
(*temporary) = <function> defined @ElvUI_WindTools/Libraries/LibOpenRaid/GetPlayerInformation.lua:716
(*temporary) = true
ForEachAuraHelper = <function> defined @FrameXML/AuraUtil.lua:56

**Comment by fang2hou** [comment]
fixed in 3fffd9c4cc2759925cf26aa8802871c5b5ddc526
