### ISSUE TITLE
[Bug] Timer for Big Dig is incorrect

### ISSUE THREAD

**Issue by Nelmarai** [fang2hou/ElvUI_WindTools#372]
**Describe the bug**
The timer for the Big Dig event is incorrect, as Windtools is showing it as running every 30 minutes, when it actually runs once an hour.

**To Reproduce**
Nothing specific needs to be done, it's just that the timing is incorrect.

**Expected behavior**
The timer for the Big Dig should be every hour, at xx:30.

**Screenshots**
N/A

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: [3.48]
 - ElvUI Version [13.55]
 - WoW Build [10.2.5.52902]

**Comment by fang2hou** [comment]
It should be solved in the latest version
