### ISSUE TITLE
Wind Tools LFG filter frame [Bug]

### ISSUE THREAD

**Issue by pozzer18** [fang2hou/ElvUI_WindTools#389]
**Describe the bug**
due to blizzards new LFG filters you are unable to use any of the filter options on the windtools LFG filter frame.

**Screenshots**
please see the links below
https://imgur.com/a/PXePooU

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: [e.g. 3.56]
 - ElvUI Version [e.g. 13.64]
 - WoW Build [e.g. 10.2.7

**Comment by fang2hou** [comment]
The module has been fixed in 3.57
