### ISSUE TITLE
有国服WLK 3.4.3 支持版本么？

### ISSUE THREAD

**Issue by carpediem-777** [fang2hou/ElvUI_WindTools#394]
**描述问题**
清晰明了地描述遇到的错误.

**错误复现**
错误复现步骤:
1. 打开 '...'
2. 点击 '....'
3. 翻页到 to '....'
4. 看到了错误

**预期功能**
清晰明了地描述你觉得插件应该如何工作.

**截图**
有截图往往能使你的问题更加容易被理解, 处理.

**插件信息 (请填写基本信息, 你可以在 [信息] 中找到):**
 - 插件版本: [例. 2.00]
 - ElvUI 版本 [例. 12.00]
 - 游戏版本 [例. 9.0.1 (25600)]

**更多信息**
如果你有更多信息, 在这里填写.

**Comment by carpediem-777** [comment]
Elv 13.61可支持

**Comment by fang2hou** [comment]
ElvUI 支持是因为 ElvUI 在内部做了非常多的判定, 比如 WLK 用这个代码, 正式服用另外一个代码.
WindTools 除去和 ElvUI 密切相关的部分其实更像单体插件集合, 所以没有适配的情况下是不能直接用的.
主要是我对怀旧完全提不起兴趣, 10级都练不到就卸载了, 没法做支持的.

**Comment by carpediem-777** [comment]
好的，感谢回复，等正式服再来用。
