### ISSUE TITLE
[Bug] Hidden setting forces minimap skinning

### ISSUE THREAD

**Issue by AngelosNaoumis** [fang2hou/ElvUI_WindTools#397]
**Describe the bug**
Something, not visible in the UI settings of WindTools forces square minimap.
When enabling an Eltriusm skin that forces minimap to be circle, even though every settings is disabled in WindTools, something still forces it to be square.

**To Reproduce**
1. Install Eltruism & WindTools
2. Go to Eltriusm settings->Maps->Circle Minimap and enable it
3. Skin is not enabled
4. Disable(dont load) WindTools, addon, skin is working as expected

**Expected behavior**
As i have everything disabled in WindTools, i dont expect it to force square minimap

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 3.58
 - ElvUI Version 13.69
 - Eltriusm Version 4.1.8
 - WoW Build [e.g. 10.2.7 (55664)]

**Comment by fang2hou** [comment]
The problem maybe here

https://github.com/fang2hou/ElvUI_WindTools/blob/424f634bc7dd67861f0cdadd60ef0f5758439ac5/Modules/Maps/RectangleMinimap.lua#L178

I will try to fix this in the next release.

**Comment by fang2hou** [comment]
I rewrite the rectangle map module in 11.0 prepatch, if you still have this issue, please reopen this ticket.
