### ISSUE TITLE
[Bug] Spellbook and Talent buttons in the gamebar don't work

### ISSUE THREAD

**Issue by Kussie** [fang2hou/ElvUI_WindTools#398]
**Describe the bug**
With the gamebar active at the top of the screen, clicking the spellbook or talent buttons nothing happens

**Expected behavior**
The spellbook and talents windows should open

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: [e.g. 2.00]
 - ElvUI Version [e.g. 12.00] 13.71
 - WoW Build [e.g. 9.0.1 (25600)]  11.0.0.55818

**Comment by claytonkimber** [comment]
can confirm this, was coming to report

**Comment by fang2hou** [comment]
as always, the fix work will be started when prepatch come to tw server (which always 2 days later than na)

**Comment by fang2hou** [comment]
Fixed in latest version
