### ISSUE TITLE
[Bug] error 

### ISSUE THREAD

**Issue by Imna1975** [fang2hou/ElvUI_WindTools#399]
12x WindTools [ERROR]
...indTools/Modules/Skins/Blizzard/ObjectiveTracker.lua:85: attempt to index field 'HeaderMenu' (a nil value)
[string "@ElvUI_WindTools/Modules/Skins/Blizzard/ObjectiveTracker.lua"]:85: in function <...indTools/Modules/Skins/Blizzard/ObjectiveTracker.lua:79>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Modules/Skins/Core.lua"]:514: in function <ElvUI_WindTools/Modules/Skins/Core.lua:507>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Core/Core.lua"]:110: in function `InitializeModules'
[string "@ElvUI_WindTools/Initialize.lua"]:68: in function `?'
[string "@ElvUI_Libraries/Core/LibElvUIPlugin-1.0-45/LibElvUIPlugin-1.0.lua"]:309: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:305>
[string "=[C]"]: in function `Initialize'
[string "@ElvUI/Core/init.lua"]:302: in function <ElvUI/Core/init.lua:301>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 modules = <table> {
 }
 enteredLoad = <table> {
 }
 name = "ElvUI_WindTools_Skins"
 defaultModuleState = true
 Widgets = <table> {
 }
 aceWidgets = <table> {
 }
 hooks = <table> {
 }
 VignettingFrame = ShadowBackground {
 }
 moduleName = "Skins"
 baseName = "ElvUI_WindTools"
 enabledState = true
 defaultModuleLibraries = <table> {
 }
 orderedModules = <table> {
 }
 addonsToLoad = <table> {
 }
 updateProfile = <table> {
 }
 nonAddonsToLoad = <table> {
 }
}
ObjectiveTrackerFrame = ObjectiveTrackerFrame {
 downKeys = <table> {
 }
 breakSnappedFramesOnSave = true
 init = false
 bottomModulePadding = 10
 snappedFrames = <table> {
 }
 isRightManagedFrame = true
 layoutParent = UIParentRightManagedFrameContainer {
 }
 systemNameString = "Questzielverfolgung"
 topPadding = 0
 Selection = Frame {
 }
 align = "right"
 AutoHider = Frame {
 }
 settingDisplayInfoMap = <table> {
 }
 settingsDialogAnchor = <table> {
 }
 Header = Frame {
 }
 NineSlice = Frame {
 }
 layoutIndex = 50
 headerText = "Alle Ziele"
 needsSorting = false
 moduleSpacing = 10
 topModulePadding = 38
 hideWhenActionBarIsOverriden = false
 isCollapsed = false
 isManagedFrame = true
 system = 12
}
(*temporary) = nil
(*temporary) = "objectiveTracker"
(*temporary) = "objectiveTracker"
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'HeaderMenu' (a nil value)"
_G = <table> {
 ERR_OUT_OF_CHI = "Nicht genügend Chi"
 DH_HAVOC_CORE_ABILITY_2 = "Starker Nahkampfangriff. Verbraucht Jähzorn. Kritische Treffer erstatten einen Teil des Jähzorns zurück."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Namen von Einheiten einfärben."
 ElvUI_Bar5Button11Count = ElvUI_Bar5Button11Count {
 }
 HUD_EDIT_MODE_SETTING_ACTION_BAR_HIDE_BAR_ART = "Leistenverzierung verbergen"
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 783
 SPELL_FAILED_CUSTOM_ERROR_71 = "Dieser Partygast möchte mit Euch tanzen."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 421
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Für diese Community können keine weiteren Einladungslinks generiert werden."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "Mit von Euch angelegten Taschen könnt Ihr nicht handeln."
 PVP_RANK_6_1 = "Fußknecht"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "Standardmäßig links von der rechten Aktionsleiste 1 platziert"
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 375
 MerchantItem3AltCurrencyFrameItem1Text = MerchantItem3AltCurrencyFrameItem1Text {
 }
 PROFESSIONS_COLUMN_REAGENTS_NONE = "Keine"
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Vordefinierte Tastaturbelegungen für Aktionen reagieren bei gedrückter statt bei losgelassener Taste."
 BINDING_NAME_NAMEPLATES = "Namensplaketten von gegnerischen Einheiten anzeigen"
 CHAT_HEADER_SUFFIX = ": "
 COVENANT_MISSIONS_HEALTH = "Gesundheit"
 MAIL_LETTER_TOOLTIP = "Klicken, um eine dauerhafte
Kopie dieses Briefs anzufertigen."
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 MultiBar6Button4Flash = MultiBar6Button4Flash {
 }
 ERR_NOAMMO_S = "%s"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 ClassNameplateBarPaladinFrameRune5 = ClassNameplateBarPaladinFrameRune5 {
 }
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 BN_UNABLE_TO_RESOLVE_NAME = "'%s' kann nicht angeflüstert werden. Möglicherweise sind die Blizzard-Dienste nicht verfügbar."
 CinematicFrameRaidBossEmoteFrame = CinematicFrameRaidBossEmoteFrame {
 }
 LE_GAME_ERR_ONLY_ONE_QUIVER = 36
 INT_SPELL_DURATION_HOURS = "%d |4Stunde:Stunden;"
 ElvUIWarbandBankFrame1Item90Stock = ElvUIWarbandBankFrame1Item90Stock {
 }
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Verängstigt"
 POWERBAR_PREDICTION_COLOR_MAELSTROM_CODE = "|cff003366"
 AUCTIONATOR_L_CONFIG_ALTERNATE_SCAN = "Standardmäßig den alternativen langsameren Scanmodus verwenden"
 BankFrameItem17

**Comment by Imna1975** [comment]
12x WindTools [ERROR]
.../ElvUI_WindTools/Modules/Skins/Blizzard/Scenario.lua:140: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:210: in function <...lvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@ElvUI_Libraries/Core/Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@ElvUI_WindTools/Modules/Skins/Blizzard/Scenario.lua"]:140: in function <.../ElvUI_WindTools/Modules/Skins/Blizzard/Scenario.lua:135>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Modules/Skins/Core.lua"]:514: in function <ElvUI_WindTools/Modules/Skins/Core.lua:507>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Core/Core.lua"]:110: in function `InitializeModules'
[string "@ElvUI_WindTools/Initialize.lua"]:68: in function `?'
[string "@ElvUI_Libraries/Core/LibElvUIPlugin-1.0-45/LibElvUIPlugin-1.0.lua"]:309: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:305>
[string "=[C]"]: in function `Initialize'
[string "@ElvUI/Core/init.lua"]:302: in function <ElvUI/Core/init.lua:301>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
(*temporary) = "Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target"

**Comment by Imna1975** [comment]
12x WindTools [ERROR]
...ElvUI_WindTools/Modules/Skins/Blizzard/SpellBook.lua:18: 'for' limit must be a number
[string "@ElvUI_WindTools/Modules/Skins/Blizzard/SpellBook.lua"]:18: in function <...ElvUI_WindTools/Modules/Skins/Blizzard/SpellBook.lua:7>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Modules/Skins/Core.lua"]:514: in function <ElvUI_WindTools/Modules/Skins/Core.lua:507>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Core/Core.lua"]:110: in function `InitializeModules'
[string "@ElvUI_WindTools/Initialize.lua"]:68: in function `?'
[string "@ElvUI_Libraries/Core/LibElvUIPlugin-1.0-45/LibElvUIPlugin-1.0.lua"]:309: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:305>
[string "=[C]"]: in function `Initialize'
[string "@ElvUI/Core/init.lua"]:302: in function <ElvUI/Core/init.lua:301>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 modules = <table> {
 }
 enteredLoad = <table> {
 }
 name = "ElvUI_WindTools_Skins"
 defaultModuleState = true
 Widgets = <table> {
 }
 aceWidgets = <table> {
 }
 hooks = <table> {
 }
 VignettingFrame = ShadowBackground {
 }
 moduleName = "Skins"
 baseName = "ElvUI_WindTools"
 enabledState = true
 defaultModuleLibraries = <table> {
 }
 orderedModules = <table> {
 }
 addonsToLoad = <table> {
 }
 updateProfile = <table> {
 }
 nonAddonsToLoad = <table> {
 }
}
(for index) = 1
(for limit) = nil
(for step) = 1
(*temporary) = 5
(*temporary) = <table> {
 modules = <table> {
 }
 enteredLoad = <table> {
 }
 name = "ElvUI_WindTools_Skins"
 defaultModuleState = true
 Widgets = <table> {
 }
 aceWidgets = <table> {
 }
 hooks = <table> {
 }
 VignettingFrame = ShadowBackground {
 }
 moduleName = "Skins"
 baseName = "ElvUI_WindTools"
 enabledState = true
 defaultModuleLibraries = <table> {
 }
 orderedModules = <table> {
 }
 addonsToLoad = <table> {
 }
 updateProfile = <table> {
 }
 nonAddonsToLoad = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "'for' limit must be a number"
_G = <table> {
 ERR_OUT_OF_CHI = "Nicht genügend Chi"
 DH_HAVOC_CORE_ABILITY_2 = "Starker Nahkampfangriff. Verbraucht Jähzorn. Kritische Treffer erstatten einen Teil des Jähzorns zurück."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Namen von Einheiten einfärben."
 ElvUI_Bar5Button11Count = ElvUI_Bar5Button11Count {
 }
 HUD_EDIT_MODE_SETTING_ACTION_BAR_HIDE_BAR_ART = "Leistenverzierung verbergen"
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 783
 SPELL_FAILED_CUSTOM_ERROR_71 = "Dieser Partygast möchte mit Euch tanzen."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 421
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Für diese Community können keine weiteren Einladungslinks generiert werden."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "Mit von Euch angelegten Taschen könnt Ihr nicht handeln."
 PVP_RANK_6_1 = "Fußknecht"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "Standardmäßig links von der rechten Aktionsleiste 1 platziert"
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 375
 MerchantItem3AltCurrencyFrameItem1Text = MerchantItem3AltCurrencyFrameItem1Text {
 }
 PROFESSIONS_COLUMN_REAGENTS_NONE = "Keine"
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Vordefinierte Tastaturbelegungen für Aktionen reagieren bei gedrückter statt bei losgelassener Taste."
 BINDING_NAME_NAMEPLATES = "Namensplaketten von gegnerischen Einheiten anzeigen"
 CHAT_HEADER_SUFFIX = ": "
 COVENANT_MISSIONS_HEALTH = "Gesundheit"
 MAIL_LETTER_TOOLTIP = "Klicken, um eine dauerhafte
Kopie dieses Briefs anzufertigen."
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 MultiBar6Button4Flash = MultiBar6Button4Flash {
 }
 ERR_NOAMMO_S = "%s"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 ClassNameplateBarPaladinFrameRune5 = ClassNameplateBarPaladinFrameRune5 {
 }
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 BN_UNABLE_TO_RESOLVE_NAME = "'%s' kann nicht angeflüstert werden. Möglicherweise sind die Blizzard-Dienste nicht verfügbar."
 CinematicFrameRaidBossEmoteFrame = CinematicFrameRaidBossEmoteFrame {
 }
 LE_GAME_ERR_ONLY_ONE_QUIVER = 36
 INT_SPELL_DURATION_HOURS = "%d |4Stunde:Stunden;"
 ElvUIWarbandBankFrame1Item90Stock = ElvUIWarbandBankFrame1Item90Stock {
 }
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Verängstigt"
 POWERBAR_PREDICTION_COLOR_MAELSTROM_CODE = "|cff003366"
 AUCTIONATOR_L_CONFIG_ALTERNATE_SCAN = "Standardmäßig den alternativen langsameren Scanmodus verwenden"
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 ElvUI_Bar6Button6 = ElvUI_Bar6Button6 {
 }
 AUCTIONATOR_L_DEFAULT_LIST_HEADER = "Standard Einkaufsliste"
 DMG_LCD = "SCHA"
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 RaidUtility_CloseButton = RaidUtility_CloseButton {
 }

**Comment by Imna1975** [comment]
12x WindTools [ERROR]
.../ElvUI_WindTools/Modules/Skins/Blizzard/WorldMap.lua:27: attempt to index field 'RewardsFrame' (a nil value)
[string "@ElvUI_WindTools/Modules/Skins/Blizzard/WorldMap.lua"]:27: in function <.../ElvUI_WindTools/Modules/Skins/Blizzard/WorldMap.lua:7>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Modules/Skins/Core.lua"]:514: in function <ElvUI_WindTools/Modules/Skins/Core.lua:507>
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Core/Core.lua"]:110: in function `InitializeModules'
[string "@ElvUI_WindTools/Initialize.lua"]:68: in function `?'
[string "@ElvUI_Libraries/Core/LibElvUIPlugin-1.0-45/LibElvUIPlugin-1.0.lua"]:309: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:305>
[string "=[C]"]: in function `Initialize'
[string "@ElvUI/Core/init.lua"]:302: in function <ElvUI/Core/init.lua:301>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 modules = <table> {
 }
 enteredLoad = <table> {
 }
 name = "ElvUI_WindTools_Skins"
 defaultModuleState = true
 Widgets = <table> {
 }
 aceWidgets = <table> {
 }
 hooks = <table> {
 }
 VignettingFrame = ShadowBackground {
 }
 moduleName = "Skins"
 baseName = "ElvUI_WindTools"
 enabledState = true
 defaultModuleLibraries = <table> {
 }
 orderedModules = <table> {
 }
 addonsToLoad = <table> {
 }
 updateProfile = <table> {
 }
 nonAddonsToLoad = <table> {
 }
}
QuestScrollFrame = QuestScrollFrame {
 scrollBarX = 8
 objectiveFramePool = <table> {
 }
 titleFramePool = <table> {
 }
 covenantCallingsHeaderFramePool = <table> {
 }
 scrollBarBottomY = -4
 BorderFrame = Frame {
 }
 callbackTables = <table> {
 }
 scrollBarTopY = 2
 CampaignTooltip = Frame {
 }
 campaignHeaderMinimalFramePool = <table> {
 }
 campaignHeaderFramePool = <table> {
 }
 panExtent = 30
 ScrollBar = Frame {
 }
 Background = Texture {
 }
 Contents = Frame {
 }
 SearchBox = EditBox {
 }
 EmptyText = FontString {
 }
 Event = <table> {
 }
 NoSearchResultsText = FontString {
 }
 headerFramePool = <table> {
 }
 StoryTooltip = Frame {
 }
 Edge = Texture {
 }
}
QuestMapFrame = QuestMapFrame {
 QuestsFrame = QuestScrollFrame {
 }
 completedCriteria = <table> {
 }
 DetailsFrame = Frame {
 }
 windFrameName = "QuestMapFrame"
 SettingsDropdown = Button {
 }
 initialCampaignHeadersUpdate = false
 MapLegend = Frame {
 }
 QuestSessionManagement = Frame {
 }
 CampaignOverview = Frame {
 }
 MoveFrame = WorldMapFrame {
 }
 VerticalSeparator = Texture {
 }
}
(*temporary) = nil
(*temporary) = Frame {
 BottomLeftCorner = Texture {
 }
 PixelSnapDisabled = true
 BottomRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 TopRightCorner = Texture {
 }
 template = "Transparent"
 Center = Texture {
 }
 TopEdge = Texture {
 }
 backdropInfo = <table> {
 }
 LeftEdge = Texture {
 }
 BottomEdge = Texture {
 }
}
(*temporary) = "Transparent"
(*temporary) = nil
(*temporary) = "attempt to index field 'RewardsFrame' (a nil value)"
_G = <table> {
 ERR_OUT_OF_CHI = "Nicht genügend Chi"
 DH_HAVOC_CORE_ABILITY_2 = "Starker Nahkampfangriff. Verbraucht Jähzorn. Kritische Treffer erstatten einen Teil des Jähzorns zurück."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Namen von Einheiten einfärben."
 ElvUI_Bar5Button11Count = ElvUI_Bar5Button11Count {
 }
 HUD_EDIT_MODE_SETTING_ACTION_BAR_HIDE_BAR_ART = "Leistenverzierung verbergen"
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 783
 SPELL_FAILED_CUSTOM_ERROR_71 = "Dieser Partygast möchte mit Euch tanzen."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 421
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Für diese Community können keine weiteren Einladungslinks generiert werden."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "Mit von Euch angelegten Taschen könnt Ihr nicht handeln."
 PVP_RANK_6_1 = "Fußknecht"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "Standardmäßig links von der rechten Aktionsleiste 1 platziert"
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 375
 MerchantItem3AltCurrencyFrameItem1Text = MerchantItem3AltCurrencyFrameItem1Text {
 }
 PROFESSIONS_COLUMN_REAGENTS_NONE = "Keine"
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Vordefinierte Tastaturbelegungen für Aktionen reagieren bei gedrückter statt bei losgelassener Taste."
 BINDING_NAME_NAMEPLATES = "Namensplaketten von gegnerischen Einheiten anzeigen"
 CHAT_HEADER_SUFFIX = ": "
 COVENANT_MISSIONS_HEALTH = "Gesundheit"
 MAIL_LETTER_TOOLTIP = "Klicken, um eine dauerhafte
Kopie dieses Briefs anzufertigen."
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 MultiBar6Button4Flash = MultiBar6Button4Flash {
 }
 ERR_NOAMMO_S = "%s"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 ClassNameplateBarPaladinFrameRune5 = ClassNameplateBarPaladinFrameRune5 {
 }
 T

**Comment by fang2hou** [comment]
Please following the issue format to submit the errors.
Besides, as always, the fix work will be started when prepatch come to tw server (which always 2 days later than na)
