### ISSUE TITLE
若干反馈

### ISSUE THREAD

**Issue by Rubgrsch** [fang2hou/ElvUI_WindTools#41]
（云反馈测试）
懒得发多个issues了，全部扔一起
1. 整理一份文档？写在wiki或者README都行。需要知道你修复了哪些elv中的问题
2. 加个LICENSE。
3. 不建议右键增强，各种taint。要保留最好默认不开启外加一个开启时确认提醒
4. Elv里头有的libs不需要打包，因为你的deps里有
5. 传到tukui.org？

**Comment by fang2hou** [comment]
已经上传到了 Tukui.org, 之后也会继续更新.
