### ISSUE TITLE
关于Modules/More/AnnounceSystem.lua

### ISSUE THREAD

**Issue by q513902026** [fang2hou/ElvUI_WindTools#51]
https://github.com/fang2hou/ElvUI_WindTools/blob/91c02a9fdfb936d0c85369d21adb6ee6d9a7ebc6/Modules/More/AnnounceSystem.lua#L309

这里事件传入的是法术id 而FeastSpells计入的当前版本大餐和锅 是物品id而非法术id

参考解决
http://bbs.nga.cn/read.php?tid=15656285&pid=307429755&to=1
通过传入的物品id 然后转换到法术id

或者直接通过 
spellName, spellID = GetItemSpell(itemID or "itemString" or "itemName" or "itemLink")
获取法术id

**Comment by someblu** [comment]
在刚才push的[commit](https://github.com/fang2hou/ElvUI_WindTools/commit/7fe0c2f152c1bc82c2e069c695ede2822ffbabd9)中修复了这处问题。

**Comment by q513902026** [comment]
修理机器人同样存在问题
    [132514] = true, -- 自動鐵錘
    [141333] = true, -- 宁神圣典
    [153646] = true, -- 静心圣典
应该是
   [199109] = true,  --自动铁锤
   [226241] = true,  --宁神圣典
   [256230] = true,  --静心圣典

**Comment by q513902026** [comment]
@someblu

**Comment by someblu** [comment]
在[commit](https://github.com/fang2hou/ElvUI_WindTools/commit/563594263278639b025c3fc6084a130ffd6879d3)中改正了。同时添加了里弗斯模块对应的法术id，没怎么测试，半小时的冷却测试起来太麻烦。

**Comment by someblu** [comment]
```LUA
11/16 16:32:38.640  SPELL_CAST_SUCCESS,Player-851-04F8FC63,"这段是马赛克",0x511,0x0,0000000000000000,nil,0x80000000,0x80000000,200061,"召唤里弗斯",0x1,Player-851-04F8FC63,0000000000000000,156520,156520,6942,6675,1858,0,100000,100000,0,-740.30,4473.70,627,2.8912,381
11/16 16:32:46.029  SPELL_CAST_START,Vehicle-0-3912-1220-31397-101462-00006F61A7,"里弗斯",0x12111,0x0,0000000000000000,nil,0x80000000,0x80000000,200205,"自动铁锤模式",0x1
11/16 16:32:48.162  SPELL_CAST_SUCCESS,Vehicle-0-3912-1220-31397-101462-00006F61A7,"里弗斯",0x12111,0x0,0000000000000000,nil,0x80000000,0x80000000,200205,"自动铁锤模式",0x1,Vehicle-0-3912-1220-31397-101462-00006F61A7,Player-851-04F8FC63,9135,9135,0,0,2700,1,0,0,0,-740.64,4472.60,627,4.8353,381
11/16 16:32:48.163  SPELL_SUMMON,Vehicle-0-3912-1220-31397-101462-00006F61A7,"里弗斯",0x12111,0x0,Creature-0-3912-1220-31397-113831-00006F61AF,"自动铁锤",0xa28,0x0,200205,"自动铁锤模式",0x1
```
目前里弗斯模块的通告没有正常工作，我这里收集了和里弗斯相关的几处log。

**Comment by someblu** [comment]
```LUA
elseif subEvent == "SPELL_SUMMON" then
	-- 修理機器人
	if Bots[spellID] then
		SendChatMessage(format(ASL["PutNormal"], srcName, GetSpellLink(spellID)), CheckChat(true))
	end
```
很奇怪，讲道理应该被这处entry处理并通告才对。

**Comment by someblu** [comment]
@fang2hou

**Comment by fang2hou** [comment]
学校作业和任务有点重，几个月没上魔兽了，如果一直有问题的话，我下次上线的时候解决一下。
