### ISSUE TITLE
与 ElvUI 10.88+ 不兼容

### ISSUE THREAD

**Issue by LiangYuxuan** [fang2hou/ElvUI_WindTools#55]
https://git.tukui.org/elvui/elvui/blob/development/ElvUI/Modules/Tooltip/Tooltip.lua#L384

原函数`ShowInspectInfo`现在为`AddInspectInfo`

**Comment by someblu** [comment]
fixed in [this commit](https://github.com/fang2hou/ElvUI_WindTools/commit/1595ba32dfdefdf934d20f5fae92bdf0c2d2ee85)
