### ISSUE TITLE
团本进度模块-达萨罗之战与阵营

### ISSUE THREAD

**Issue by LiangYuxuan** [fang2hou/ElvUI_WindTools#57]
https://github.com/fang2hou/ElvUI_WindTools/blob/86eadbea91f1a3a4606810a5b275b35a9290c8c8/Modules/Interface/EnhancedTooltip.lua#L115

现在套用的是玩家自身的的阵营，但是在战争模式与PvP都关闭的情况下，可以对敌对阵营玩家进行观察与比较成就，此时显示的团本进度将不正确。

**Comment by someblu** [comment]
我才知道还能开敌对玩家的成就。。。明天改下

**Comment by someblu** [comment]
如果不缓存玩家阵营，每次鼠标提示显示时调用UnitFactionGroup("mouseover")，那么当玩家处在达萨罗之战中阵营转换的阶段的话，会返回的是当前阵营（比如联盟换到了部落，函数返回的部落），那样团本进度会出错。我没找到有哪个函数可以知道某个玩家原有的阵营。。。如果检测阵营转换这个事件，那么当转换发生后重载界面又没法知道某个玩家的原有阵营。
我现在没有相应的团本进度可以用来测试，如果你方便的话可以帮忙测试下UnitFactionGroup("mouseover")，GetPlayerInfoByGUID(UnitGUID("mouseover"))在阵营转换后时候能返回原来的阵营（种族）。

**Comment by someblu** [comment]
即使现在所采用的缓存的方案，依然无法应对阵营转换后重载界面的情况。。

**Comment by someblu** [comment]
GetPlayerInfoByGUID(UnitGUID("mouseover"))会返回原有种族，问题终结。。。

**Comment by someblu** [comment]
UnitFactionGroup("player") 也是返回的原有种族，
```LUA
Dump: value=UnitFactionGroup("player") 
[1]="Alliance", 
[2]="联盟"
```
```LUA
Dump: value=UnitFactionGroup("mouseover") 
[1]="Horde", 
[2]="部落" 
Dump: value=UnitIsUnit("player","mouseover") 
[1]=true
```
这可真神奇。。。

**Comment by someblu** [comment]
在这个[commit](https://github.com/fang2hou/ElvUI_WindTools/commit/d1a77a4fd7d6abafe85e0ebc202f254055ec9735)中修复了
