### ISSUE TITLE
世界任务奖励的艾泽利特护甲的特质信息无法获取

### ISSUE THREAD

**Issue by someblu** [fang2hou/ElvUI_WindTools#62]
暴雪在8.1.5中移除了WorldMapTooltip以及WorldMapCompareTooltip1，转而使用GameToolTip构建任务奖励的鼠标提示。对应的艾泽利特鼠标提示的改动应为（[相关commit](https://github.com/fang2hou/ElvUI_WindTools/commit/b5804da2ad0b59f4440baf38ce4c6ecc4af699cc)）
```LUA
local name, link
if GameTooltip:GetOwner().worldQuest then
	name, link = GetItemInfo(GameTooltip.ItemTooltip.itemID) 
else
	name, link = self:GetItem()
end
```
到这一步，世界任务奖励的物品名字和物品链接能被正常获取。
然而在调用```C_AzeriteEmpoweredItem.GetAllTierInfoByItemID```获取艾泽利特特质信息的时候，只能获取解锁等级，特质内容显示为空。疑似是暴雪故意隐藏了任务奖励的护甲信息。
相关Dump信息,
```LUA
Dump: value=C_AzeriteEmpoweredItem.GetAllTierInfoByItemID(select(2,GetItemInfo(GameTooltip.ItemTooltip.itemID))) 
[1]={ 
  [1]={ 
    azeritePowerIDs={ 
    }, 
    unlockLevel=11 
  }, 
  [2]={ 
    azeritePowerIDs={ 
    }, 
    unlockLevel=16 
  }, 
  [3]={ 
    azeritePowerIDs={ 
    }, 
    unlockLevel=21 
  } 
}
```

**Comment by fang2hou** [comment]
看了下现在wq好像已经没有特质装了
