### ISSUE TITLE
建议使用BigWigsMods的版本发布脚本

### ISSUE THREAD

**Issue by someblu** [fang2hou/ElvUI_WindTools#63]
BigWigsMods的[packager](https://github.com/BigWigsMods/packager/)支持.pkgmeta中的大部分关键词，且能生成包含远程库文件的完整的zip文件并发布到Github Release。

[WeakAuras2](https://github.com/WeakAuras/WeakAuras2/blob/master/.travis.yml)和[BigWigs](https://github.com/BigWigsMods/BigWigs/blob/master/.travis.yml)都在CI中运行了这一发布脚本。

如果使用这一脚本进行版本发布，需要额外配置Travis CI或者Circle CI来完成自动化发布。

**Comment by fang2hou** [comment]
我有空的时候看看，学习一下
