### ISSUE TITLE
延时发话bug的（可能的）解决办法

### ISSUE THREAD

**Issue by someblu** [fang2hou/ElvUI_WindTools#64]
参考[Programming in Lua](https://www.lua.org/pil/16.html),在[commit](https://github.com/fang2hou/ElvUI_WindTools/commit/d8636ad8f368f82f2197aa751216be70a713ff85#diff-f208fa19ee15e2ec2ffaa9a17152457c)中出错的这段代码
```LUA
C_Timer.After(2, AS:SayThanks_Goodbye())
```
可改为
```LUA
C_Timer.After(2, AS.SayThanks_Goodbye(AS))
```
如有必要
```LUA
function AS:SayThanks_Goodbye()
	local config = self.db.thanks
	if not config.enabled or not config.goodbye.enabled then return end
	self:SendMessage(config.goodbye.text, self:GetChannel(config.goodbye.channel))
end
```
应改为
```LUA
function AS.SayThanks_Goodbye(self)
	local config = self.db.thanks
	if not config.enabled or not config.goodbye.enabled then return end
	self:SendMessage(config.goodbye.text, self:GetChannel(config.goodbye.channel))
end
```

**Comment by fang2hou** [comment]
这个延时发话本来是想和我另外一个插件避免同时发话弄乱次序才想弄的，但是今天我M+打完结束，插件报错的时候还是在队伍中有发言，可能另外一个事件也在副本结束时触发了，如果真的是这样的话就不需要延时了，具体还有待测试。

**Comment by someblu** [comment]
使用[Ace-Timer](https://www.wowace.com/projects/ace3/pages/api/ace-timer-3-0)的话应该能更好的处理object method和function reference。

**Comment by fang2hou** [comment]
嗯，有需要的话我会去看的。
今天我再解决下团队内多人通告的问题就好好玩游戏了，这几天大密都没怎么打。😩
