### ISSUE TITLE
关于代码的权利

### ISSUE THREAD

**Issue by fang2hou** [fang2hou/ElvUI_WindTools#65]
我今天刚好在NGA看反馈帖看到了@someblu 和新的一个整合包的作者之间有点口角。

WindTools 这个仓库，刚开始如果找得到历史记录的话其实就是我在 nga 上找的功能 lua 集合，也倒不是什么 ElvUI 专用的增强包。

做增强包也算是机缘巧合，S&L 这个主流增强包在体量和功能上让我觉得太大，用不到的功能太多了。接着我又尝试了多个增强包之后发现市面上根本没有自己喜欢的。nga 社区刚好在这个时候又对 EUI 作者口诛笔伐，很多人都转用更加流畅的 ElvUI 纯净版本。考虑到国内社区还没有一款中文支持较好及适合国人习惯的增强包，我决定自己做一个。

由于之前一直在找别人增强包自己用，自己稍微会点 lua，自然想去尝试修改其代码来达到自己想要的效果。也就是这个时候，我自己发现 ElvUI 增强包社区其实互相借鉴修改的先例多到数不过来。就小地图按钮这个功能来说几乎所有包都带了，然而出处已经不明了。所以考虑到社区确实普遍接受借鉴和改良，我就拿了不少别人包的东西来自己做成模块，并留下出处，为的就是如果使用者不喜欢我改的版本，也是OK，直接关掉工具箱的版本自己去下载一个原版，互不影响。

包内很多增强功能说实话和原本的版本已经没什么联系了，有些是本身作者afk很多年没法用的代码，有些是为了加功能重写 90%+。部分增强我修改更新除错后也会联系到作者，如果他愿意，随时都可以合并我的修正代码，比如 Enhanced Again (BfA)。我有空也会去看 ElvUI 官方的开发分支，作出一些微小的贡献。

总的来说，魔兽插件开发社区真的非常友好，而且在插件开发的过程中我自身收获颇多。刚开始总是写 bug，后来慢慢的掌握 Ace3 库的用法，一段时间下来理解了不少东西。我本身学的专业就是研究游戏内 AI 的，所以熟悉 lua 是个让我很开心的事情。

希望所有魔兽玩家都能玩的开心，插件毕竟也就是辅助，顺手就好了。我欢迎任何人使用我写的代码，对于我写的那部分代码，任何人都可以随意的修改，发布，不署名，只要别说是你自己改的就可以。

为了联盟！

**Comment by fang2hou** [comment]
关于新功能的添加，我的态度就是
如果这个功能没有在一些常用插件中存在，且体量不大，不需要频繁更新，需求还挺大就做一下。

虽然总有人喊着做快速团队标记这种功能，但我觉得打团打本用不到 ExRT 来分析战斗的人，其实对快速标记需求也是不大的。而ExRT已经自带了，继续往 WindTools 里加 = 减少自己的游戏时间。

**Comment by fang2hou** [comment]
@someblu 我马上4月开学就要大四了，准备考研，更新随缘！

**Comment by someblu** [comment]
那个插件的作者已经重新整理了他所写的[ElvUI_LvPlus](https://wow.curseforge.com/projects/elvui_lvplus)，并改名为[ElvUI LivvenUI](https://bbs.nga.cn/read.php?tid=16724352)。那次争论之后他应该有去了解开源项目及其协议，新的项目就开源协议一方面没什么问题了。

而后我个人是对那些只fork不contribute的人有一点反感的，尤其是在原项目还在持续开发的状态下。不过大多数开源协议并没有阻止这一点，这也是每个人的自由。

**Comment by someblu** [comment]
我最近在忙着申请GSoC，一直在联系mentor找项目。。。

**Comment by fang2hou** [comment]
也不用不开心，反正插件这东西本来就是娱乐性质比较强，也没这么上纲上线，自己用的顺手开心就好。
别人用我们的代码也是一种肯定。比起游戏，生活更重要，学业一起加油！
