### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by adryan66** [fang2hou/ElvUI_WindTools#66]
> Message: ...Ons\ElvUI_WindTools\Modules\Trade\AzeriteTooltip.lua:186: attempt to index a nil value
> Time: Mon Apr  8 21:19:41 2019
> Count: 1
> Stack: ...Ons\ElvUI_WindTools\Modules\Trade\AzeriteTooltip.lua:186: attempt to index a nil value
> [C]: ?
> ...Ons\ElvUI_WindTools\Modules\Trade\AzeriteTooltip.lua:186: in function <...Ons\ElvUI_WindTools\Modules\Tradew\AzeriteTooltip.lua:184>
> ...Ons\ElvUI_WindTools\Modules\Trade\AzeriteTooltip.lua:482: in function <...Ons\ElvUI_WindTools\Modules\Trade\AzeriteTooltip.lua:481>
> (tail call): ?
> [C]: ?
> [C]: ?
> ...TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:482: in function <...TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:476>
> [C]: ?
> [C]: ?
> [C]: ?
> ...TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:408: in function `SetAuctionSellItem'
> Interface\AddOns\Auctionator\Auctionator.lua:1218: in function `Atr_GetSellItemInfo'
> Interface\AddOns\Auctionator\Auctionator.lua:2880: in function `Atr_OnNewAuctionUpdate'
> Interface\AddOns\Auctionator\Auctionator.lua:178: in function `Atr_EventHandler'
> [string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>
> [C]: in function `ClickAuctionSellItemButton'
> Interface\AddOns\Auctionator\Auctionator.lua:1456: in function `Atr_ClickAuctionSellItemButton'
> Interface\AddOns\Auctionator\Auctionator.lua:1482: in function <Interface\AddOns\Auctionator\Auctionator.lua:1479>
> 
> Locals: 

And second 

> Message: ...Ons\ElvUI_WindTools\Modules\Trade\AzeriteTooltip.lua:186: attempt to index a nil value
> Time: Mon Apr  8 21:19:41 2019
> Count: 1
> Stack: ...Ons\ElvUI_WindTools\Modules\Trade\AzeriteTooltip.lua:186: attempt to index a nil value
> [C]: ?
> ...Ons\ElvUI_WindTools\Modules\Trade\AzeriteTooltip.lua:186: in function <...Ons\ElvUI_WindTools\Modules\Trade\AzeriteTooltip.lua:184>
> ...Ons\ElvUI_WindTools\Modules\Trade\AzeriteTooltip.lua:482: in function <...Ons\ElvUI_WindTools\Modules\Trade\AzeriteTooltip.lua:481>
> (tail call): ?
> [C]: ?
> [C]: ?
> ...TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:482: in function <...TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:476>
> [C]: ?
> [C]: ?
> [C]: ?
> ...TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:408: in function `SetAuctionSellItem'
> Interface\AddOns\Auctionator\Auctionator.lua:1218: in function `Atr_GetSellItemInfo'
> Interface\AddOns\Auctionator\Auctionator.lua:3114: in function `Atr_SetDepositText'
> Interface\AddOns\Auctionator\Auctionator.lua:3074: in function `Atr_UpdateUI_SellPane'
> Interface\AddOns\Auctionator\Auctionator.lua:3011: in function `Atr_UpdateUI'
> Interface\AddOns\Auctionator\Auctionator.lua:2849: in function `Atr_Idle'
> Interface\AddOns\Auctionator\Auctionator.lua:2798: in function `Atr_OnUpdate'
> [string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>
> 
> Locals: 

Both should be regarding interaction with Auctionator

**Comment by fang2hou** [comment]
Fixed on `alpha` branch.
