### ISSUE TITLE
建议右键增强添加战网好友功能

### ISSUE THREAD

**Issue by Jetranger** [fang2hou/ElvUI_WindTools#68]
目前只有邀请入会等，但是长期用到的会是添加战网好友，希望作者添加。

**Comment by someblu** [comment]
我先给出结论：这个功能在聊天面板中不可实现。
原因是：
首先去看FrameXML中添加战网好友的功能实现的[代码](https://www.townlong-yak.com/framexml/live/UnitPopup.lua#1897),其中用到了```BNCheckBattleTagInviteToUnit(unit)```这个函数。而这个函数是只接受```unitId```的输入的。
而后我们再去游戏里面看相关的Dump信息，右击某个玩家的头像，输入下面的指令（保持右键菜单开启）
```LUA
/dump UIDROPDOWNMENU_INIT_MENU.unit,UIDROPDOWNMENU_INIT_MENU.name
```
应该能看到
```LUA
Dump: value=UIDROPDOWNMENU_INIT_MENU.unit,UIDROPDOWNMENU_INIT_MENU.name 
[1]="target", 
[2]="蓝猫超淘气"
```
而如果右击聊天菜单的姓名，再输入一遍指令，能看到
```LUA
Dump: value=UIDROPDOWNMENU_INIT_MENU.unit,UIDROPDOWNMENU_INIT_MENU.name 
[2]="蓝猫超淘气" 
```
```UIDROPDOWNMENU_INIT_MENU.unit```值为```nil```

如果我们只知道```name```而不知道```unitId```，那么插件只有在该单位可以被遍历到的情况下，才能将```name```和```unitId```匹配对应（例如这个单位是你的队友、竞技场或战场或副本首领战斗敌对目标、屏幕上显示的姓名版的目标），类似Brute-force attack。如果该单位退出了你的队伍，不在你的屏幕上显示的姓名版中等等，就不能获取到```unitId```了。因此像聊天框的名字这种就没办法（保证一定能）获取到它对应的```unitId```，也就无法调用函数去添加战网好友。

换言之，如果插件可以通过穷举的方式遍历到```unitId```，那么该单位也一定能通过鼠标右键点击它的头像，也就能直接通过```UIDROPDOWNMENU_INIT_MENU.unit```来获取```unitId```了。

**Comment by someblu** [comment]
这是FrameXML中邀请公会的[代码](https://www.townlong-yak.com/framexml/live/ChatFrame.lua#2008)，相关函数为
```LUA
GuildInvite(GetUnitName("target", true))
```
这个函数接受```name```的输入，所以可以在聊天框的右键菜单中添加邀请公会的功能。
