### ISSUE TITLE
采用Programming Gems中的建议

### ISSUE THREAD

**Issue by someblu** [fang2hou/ElvUI_WindTools#69]
我最近意外的谷歌到了[Gems](https://www.lua.org/gems/)这本书，看了其中的一篇[文章](https://www.lua.org/gems/sample.pdf)，还蛮有用的，有很多优化的小技巧，发这分享下。

**Comment by someblu** [comment]
忙完啦，开始看新的commit。。最近好高产。。

**Comment by fang2hou** [comment]
也不用看什么commit，因为我也就改了2个模块而已，前后有改来改去，看代码可能快一点。
本来刚开学还没忙起来就写了些，这周开始要开始给教授报告研究进度了。现在手上7个满级号，每周H，M，大米打完，也就没什么空了。
