### ISSUE TITLE
最新的ElvUI Dev版本在一般选项中增加了一个语言的选择项，选择Chinese后 Windtools 仍然是英文，可能是代码架构变动，请作者关注一下。

### ISSUE THREAD

**Issue by parawii** [fang2hou/ElvUI_WindTools#71]
最新的ElvUI Dev版本在一般选项中增加了一个语言的选择项，选择Chinese后 Windtools 仍然是英文，可能是代码架构变动，请作者关注一下。

**Comment by someblu** [comment]
WindTools是根据客户端语言选择Locales的，ElvUI新增的这个功能会等正式版发布后添加支持。

**Comment by fang2hou** [comment]
现在改功能还在不断改动中，我也是ElvUI这块功能的修改者，等稳定下来后适配。

**Comment by fang2hou** [comment]
已经适配
