### ISSUE TITLE
在elvui 11.13 和 11.14中冒险指南不显示

### ISSUE THREAD

**Issue by liugongkai111** [fang2hou/ElvUI_WindTools#74]
在新版Elvui(11.13 or 11.14)冒险指南窗口显示为全黑，并且点击穿越

**Comment by liugongkai111** [comment]
> 在新版Elvui(11.13 or 11.14)冒险指南窗口显示为全黑，并且点击穿越

经过实验, 是'记住窗口位置功能'与冒险指南窗口发生冲突

**Comment by fang2hou** [comment]
最近在肝FF14，我有空会上线更新一下的。

**Comment by someblu** [comment]
正式版[1.4.7](https://www.curseforge.com/wow/addons/elvui_windtools/files/2737735)中修复了这个问题。
