### ISSUE TITLE
当设置了亲密好友后，增强好友列表功能出现了异常

### ISSUE THREAD

**Issue by qyh214** [fang2hou/ElvUI_WindTools#76]
hash：  4106cf9aee322cdf11a4db389b8e67b712ca055f
elvui：11.16
游戏版本：8.2
详细描述：
- 开启好友列表增强功能，并设置若干好友为亲密好友。
- 依次查看好友信息，亲密好友正常，但是看到后面的好友产生错位，鼠标放在A上面，但是tooltip显示的是B，如果邀请这些好友就会出现错乱。

临时解决办法：
- 禁用好友增强或删除亲密好友

**Comment by someblu** [comment]
在这个[commit](../commit/ce28db5f107c726fcf66f38a8695fad3877a4dd3)中修复了。
