### ISSUE TITLE
针对艾泽利特精华的搭配的新增模块建议

### ISSUE THREAD

**Issue by someblu** [fang2hou/ElvUI_WindTools#77]
目前准备新建一个模块，参考[SubSpec](https://www.curseforge.com/wow/addons/subspec)，为艾泽利特精华的搭配提供保存和导入功能。同时也可以整合SubSpec对天赋的搭配的保存和导入功能。

Note：
```LUA
for _, milestone in ipairs(C_AzeriteEssence.GetMilestones()) do
   if milestone.slot and milestone.unlocked then
      local essenceID = (C_AzeriteEssence.GetMilestoneEssence(milestone.ID))
      -- save(essenceID, milestone.ID);
   end
end

C_AzeriteEssence.ActivateEssence(essenceID,milestoneID)
C_AzeriteEssence.CanActivateEssence(essenceID,milestoneID)

C_AzeriteEssence.GetEssenceInfo(essenceID).name
C_AzeriteEssence.HasNeverActivatedAnyEssences()
```

Reference:
[AzeriteEssenceDocumentation](https://www.townlong-yak.com/framexml/live/Blizzard_APIDocumentation/AzeriteEssenceDocumentation.lua)
[Blizzard_AzeriteEssenceUI](https://www.townlong-yak.com/framexml/live/Blizzard_AzeriteEssenceUI/Blizzard_AzeriteEssenceUI.lua)

**Comment by fang2hou** [comment]
这个确实挺有用的。
