### ISSUE TITLE
增强好友功能似乎意外导致游戏内置语音聊天出现了异常

### ISSUE THREAD

**Issue by qyh214** [fang2hou/ElvUI_WindTools#78]
我在启用了最新的增强好友列表功能后，出现了当使用游戏内置语音聊天时，只能听到对话声音，一旦进行对话，播放中的游戏内音乐就会停止播放，结束对话后又恢复游戏内音乐播放，这个问题似乎很奇怪，但是经过多次对插件的测试，定位到只需要关闭好友列表增强就能解决这个问题，我的复现方式是：
- wind工具箱关闭增强好友功能
- 重载界面
- 队伍里使用内置语音聊天功能，能既有对话声音又有游戏音乐（游戏音乐不会因对话而停止播放）

- 然后启用增强好友功能
- 重载界面
- 队伍里使用内置语音聊天功能，能听到对话声音，但是当有人对话时不再播放游戏音乐/音效，这将导致dbm等类似的语音插件不再听到提示语，引起不便。

如果确实因为这一问题导致，我建议可以作为一个单独开关，供大家选择，比如名称叫作 启用纯对话功能（在对话阶段将对所有其他游戏声音静音）

--- 

补充下：

经过再次测试，可以启用增强好友列表功能，只需要禁用里面的材质增强即可，如果启用材质增强就会导致本issue发生——即，当有聊天对话发生后，游戏内正在播放的音乐就会被静音

**Comment by someblu** [comment]
了解了，你是用的正式版1.4.7吗？如果是的话，可以帮我测试下这个问题能否在正式版1.4.6以及测试版1.5.0-alpha-3中复现么？

**Comment by qyh214** [comment]
正式版1.4.6、1.4.7和测试版1.5.0-alpha-3均复现，1.5.0-alpha-3修复了我之前提出的#76 的问题。

现在这个issue临时解决办法只需要取消勾选材质增强（工具箱-聊天框-增强好友列表）即可。

**Comment by qyh214** [comment]
额，应该某个版本elvui更新后，此问题已不能复现。

忘记来这里关闭了……
