### ISSUE TITLE
光柱标记与实际图标不相符

### ISSUE THREAD

**Issue by xineyu01** [fang2hou/ElvUI_WindTools#83]
![image](https://user-images.githubusercontent.com/50855749/65389046-4126e380-dd84-11e9-9e3c-7e23c9f3443a.png)
插件图示顺序

![image](https://user-images.githubusercontent.com/50855749/65389054-5ac82b00-dd84-11e9-9abe-1e9dc54bf489.png)
实际图示顺序

出现了不对应的情况,望修复

**Comment by fang2hou** [comment]
最新版本已经修复。
