### ISSUE TITLE
大佬敲碗等更新啊

### ISSUE THREAD

**Issue by Remberance** [fang2hou/ElvUI_WindTools#84]
大佬，这更新了825之后，好像好友增强列表出问题了，魔兽世界的图标不是那种扁平化的，也没有职业色和等级显示了。
希望大佬加入的功能：增强声望显示，其他的暂时没想到了。

**Comment by fang2hou** [comment]
最近在忙升学，更新的话要过一段阵子了。

**Comment by 404Polaris** [comment]
> 最近在忙升学，更新的话要过一段阵子了。

大佬有空发个版本呗

**Comment by fang2hou** [comment]
更新咯~
