### ISSUE TITLE
新版拍卖行的拖动问题

### ISSUE THREAD

**Issue by 404Polaris** [fang2hou/ElvUI_WindTools#87]
新版拍卖行现在无法拖动，即使在对应白名单中加入AuctionHouseFrame也无效，经过实验发现当前AuctionHouseFrame在游戏载入完成后并不存在，当第一次主动打开拍卖行后AuctionHouseFrame才第一次被初始化，作者有时间的话可以改一改

**Comment by fang2hou** [comment]
已经修改！
