### ISSUE TITLE
小地图按钮bug

### ISSUE THREAD

**Issue by WeijieH** [fang2hou/ElvUI_WindTools#88]
因为某些原因我一直都同时使用windtools和S&L，两个插件冲突的部分我会选择一个禁用掉。小地图按钮部分我通常都是开启SL并且关闭了windtools的相关模块。
今天WT更新后，我发现无论WT的小地图按钮模块是否开启，SL的小地图模块都不能正常工作。具体表现为可以收纳3-4个按钮，但其他的分散在小地图上。
希望可以下个版本修复。

**Comment by fang2hou** [comment]
1.5.10 有尝试过么

**Comment by WeijieH** [comment]
就是从1.5.10开始出现的问题，之前一直都是好的

**Comment by WeijieH** [comment]
更新一下，我一般是早上用twitch更新一次插件，然后今天更新后出的问题。所以我可以确定1.5.7一定没有问题，1.5.10问题已经出现。我看了下更新日志，也许是从1.5.8出现的问题？

**Comment by fang2hou** [comment]
1.5.10 是我今天晚上发出的新版本，理论上应该已经解决了

**Comment by fang2hou** [comment]
我自己也装了S&L实验，没有发现散掉的问题啊
![1](https://user-images.githubusercontent.com/6694722/78574649-41408980-7865-11ea-8e2f-ae3c2795f499.png)

**Comment by WeijieH** [comment]
![Snipaste_2020-04-06_12-08-23](https://user-images.githubusercontent.com/16510655/78579753-67334300-77ff-11ea-956b-e6abc7074ef7.png)
你看我这个，我关闭了wt的小地图按钮，然后打开了sl的。sl只能收录3个到框体里，其他的散乱在小地图上。
![Snipaste_2020-04-06_12-11-44](https://user-images.githubusercontent.com/16510655/78580021-ce50f780-77ff-11ea-8ad7-361e82e0e4dc.png)
然后我彻底禁用WT，或者换成1.5.7，小地图按钮恢复正常

**Comment by fang2hou** [comment]
那你能不能贴下报错？
用 Twitch 装 BugSuck + BugGrabber 就可以复制出来。

**Comment by WeijieH** [comment]
![Snipaste_2020-04-06_12-39-56](https://user-images.githubusercontent.com/16510655/78582745-c3986180-7803-11ea-8ae5-b23d615bcae9.png)
没有任何报错，不知道这是什么情况

**Comment by fang2hou** [comment]
把S&L小地图条关闭，用WindTools的小地图会错误么？

**Comment by WeijieH** [comment]
不会，我之前一直用sl的是因为可以调按钮间距，而且上面会有一条bar我觉得比较好看。目前我只能禁用sl开wt的

**Comment by fang2hou** [comment]
OK，找到问题了，马上发一版修复

**Comment by fang2hou** [comment]
感谢回报

**Comment by WeijieH** [comment]
感谢！
