### ISSUE TITLE
1.5.10-12版本之后特质装特质图标显示bug

### ISSUE THREAD

**Issue by xineyu01** [fang2hou/ElvUI_WindTools#89]
![TIM截图20200408011309](https://user-images.githubusercontent.com/50855749/78699217-1eca7100-7936-11ea-8cac-3af7b610e3a0.png)
如图
1.5.7版本表示正常

**Comment by fang2hou** [comment]
最新的beta版本有尝试过么？

**Comment by xineyu01** [comment]
1.5.12-beta-4
正常显示

**Comment by fang2hou** [comment]
OK，感谢你的回报哦~
