### ISSUE TITLE
3项lua报错

### ISSUE THREAD

**Issue by xineyu01** [fang2hou/ElvUI_WindTools#90]
1x ...\ElvUI_WindTools\Modules\Quest\ObjectiveProgress.lua:10: Cannot find a library instance of "LibObjectiveProgress-1.0".
[string "=[C]"]: in function `error'
[string "@AddOnSkins\Libs\Ace3\LibStub\LibStub.lua"]:23: in function `LibStub'
[string "@ElvUI_WindTools\Modules\Quest\ObjectiveProgress.lua"]:10: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibObjectiveProgress-1.0"."

--------------------------------------------------------------------------------------------------

3x Error loading ElvUI_WindTools\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0-100204.lua

--------------------------------------------------------------------------------------------------

3x Couldn't open ElvUI_WindTools\Libs\LibObjectiveProgress-1.0-41\embed.xml

**Comment by fang2hou** [comment]
你是用什么版本的？

**Comment by xineyu01** [comment]
curseforge.com/wow/addons/elvui_windtools
elvui_windtools-1.5.12

**Comment by fang2hou** [comment]
你打开插件文件夹下的Libs文件夹里面有几个文件？

**Comment by xineyu01** [comment]
怀疑是curse推送问题.
完全删除后re-install,报错消失
报错时只有一个.xml文档
re-install之后多出2个文件夹,报错消失

**Comment by fang2hou** [comment]
好的👌
