### ISSUE TITLE
能加一个在怪物姓名版施法条显示点名目标姓名的功能吗

### ISSUE THREAD

**Issue by parawii** [fang2hou/ElvUI_WindTools#91]
能加一个在怪物姓名版施法条显示点名目标姓名的功能吗。
聊天条能加一个鼠标指向显示吗 
谢谢大侠

**Comment by fang2hou** [comment]
聊天条鼠标滑过显示已经加上了。
姓名版我现在用的是 Plater，所以一直没在做相关增强，有空切到ElvUI自带的姓名版试一下。
