### ISSUE TITLE
更新了1.6.2出现大量错误

### ISSUE THREAD

**Issue by AudreyBlanney** [fang2hou/ElvUI_WindTools#93]
Message: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: StaticPopup1:SetPoint.
Time: Mon Apr 20 22:15:29 2020
Count: 1
Stack: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: StaticPopup1:SetPoint.
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetPoint'
[string "@Interface\FrameXML\StaticPopup.lua"]:5168: in function `StaticPopup_SetUpAnchor'
[string "@Interface\FrameXML\StaticPopup.lua"]:5158: in function <Interface\FrameXML\StaticPopup.lua:5156>
[string "=[C]"]: ?
[string "=[C]"]: in function `StaticPopup_SetUpPosition'
[string "@Interface\FrameXML\StaticPopup.lua"]:4803: in function <Interface\FrameXML\StaticPopup.lua:4392>
[string "=[C]"]: ?
[string "=[C]"]: in function `StaticPopup_Show'
[string "@Interface\FrameXML\UIParent.lua"]:1570: in function <Interface\FrameXML\UIParent.lua:1164>

Locals: 

1.死亡后导致释放灵魂窗口无法弹出
2./rl重载之后可以弹出释放灵魂窗口 但跑到尸体位置 无法弹出复活窗口
3.丢弃物品弹出的确认确认窗口只能弹出部分按钮
4.装备宝石镶嵌栏偶尔无法更换宝石 换上宝石后点击应用按钮无效

**Comment by fang2hou** [comment]
插件列表有么

**Comment by fang2hou** [comment]
如果是只有ElvUI + ElvUI_WindTools的情况下出问题，我这里才能进行修复。
你这个问题非常像 Shadow & Light 的移动框架问题

**Comment by AudreyBlanney** [comment]
对的 我找到是哪个模块了 其他功能--暴雪框体增强 我关闭这个功能之后 恢复正常




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhou Fang"<notifications@github.com&gt;; 
发送时间: 2020年4月20日(星期一) 晚上11:36
收件人: "fang2hou/ElvUI_WindTools"<ElvUI_WindTools@noreply.github.com&gt;; 
抄送: "Divergent"<hackbrad4869@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fang2hou/ElvUI_WindTools] 更新了1.6.2出现大量错误 (#93)





 
如果是只有ElvUI + ElvUI_WindTools的情况下出问题，我这里才能进行修复。
 你这个问题非常像 Shadow &amp; Light 的移动框架问题
 
&mdash;

**Comment by AudreyBlanney** [comment]
插件列表：
AddOnSkins
AddOnSkins





4.411





Angry Keystones
Angry Keystones





v0.18.4





DBM-AQ20
DBM-AQ20

DBM-Core



r669





Deadly Boss Mods (DBM) - BC &amp;amp; Vanilla/Classic mods
Deadly Boss Mods (DBM) - BC &amp;amp; Vanilla/Classic mods

DBM-Core



r669





DBM-AntorusBurningThrone
DBM-AntorusBurningThrone

DBM-Core



r16





DBM-Argus
DBM-Argus

DBM-Core



r16





DBM-Azeroth
DBM-Azeroth

DBM-Core



r669





DBM-BWL
DBM-BWL

DBM-Core



r669





DBM-BlackTemple
DBM-BlackTemple

DBM-Core



r669





DBM-BlackrockFoundry
DBM-BlackrockFoundry

DBM-Core



r46





Deadly Boss Mods (DBM) - Cataclysm mods
Deadly Boss Mods (DBM) - Cataclysm mods





r206





DBM-BrokenIsles
DBM-BrokenIsles

DBM-Core



r16





Deadly Boss Mods (DBM): Challenges
Deadly Boss Mods (DBM): Challenges

DBM-Core



r113





Deadly Boss Mods (DBM)
Deadly Boss Mods (DBM)





8.3.20





DBM-CountPack-HotS
DBM-CountPack-HotS

DBM-Core



1.7.5





Deadly Boss Mods (DBM) - Overwatch Countdown Pack
Deadly Boss Mods (DBM) - Overwatch Countdown Pack





1.4.10





DBM-Draenor
DBM-Draenor

DBM-Core



r46





DBM-EmeraldNightmare
DBM-EmeraldNightmare

DBM-Core



r16





DBM-GarrisonInvasions
DBM-GarrisonInvasions

DBM-Core



r46





Deadly Boss Mods (DBM) - Mists of Pandaria (MoP) mods
Deadly Boss Mods (DBM) - Mists of Pandaria (MoP) mods





r134





DBM-HellfireCitadel
DBM-HellfireCitadel

DBM-Core



r46





DBM-Highmaul
DBM-Highmaul

DBM-Core



r46





DBM-Hyjal
DBM-Hyjal

DBM-Core



r669





DBM-Karazhan
DBM-Karazhan

DBM-Core



r669





DBM-MC
DBM-MC

DBM-Core



r669





DBM-Nighthold
DBM-Nighthold

DBM-Core



r16





DBM-Outlands
DBM-Outlands

DBM-Core



r669





DBM-Serpentshrine
DBM-Serpentshrine

DBM-Core



r669





DBM-SpellTimers (Deadly Boss Mods)
DBM-SpellTimers (Deadly Boss Mods)

DBM-Core



80100





DBM-Sunwell
DBM-Sunwell

DBM-Core



r669





DBM-TheEye
DBM-TheEye

DBM-Core



r669





DBM-TombofSargeras
DBM-TombofSargeras

DBM-Core



r16





DBM-TrialofValor
DBM-TrialofValor

DBM-Core



r16





DBM Voicepack: Yike
DBM Voicepack: Yike





DBM-VPYike.zip
2019-12-21 21:57:13





Deadly Boss Mods (DBM) - Wrath of the Lich King mods
Deadly Boss Mods (DBM) - Wrath of the Lich King mods





r292





Details! Damage Meter
Details! Damage Meter





DetailsRetail.8.3.0.7282.140





ElvUI
ElvUI





11.372





ElvUI_BenikUI v3
ElvUI_BenikUI v3





v3.801





ElvUI_WindTools
ElvUI WindTools





1.6.2





Exorsus Raid Tools
Exorsus Raid Tools





Exorsus Raid Tools v.4140





Garrison Mission Manager
Garrison Mission Manager

Blizzard_GarrisonUIBlizzard_OrderHallUI



v59





HandyNotes
HandyNotes





v1.5.9





HandyNotes: Visions of N'Zoth
HandyNotes: Visions of N'Zoth





v38





Handynotes - Warfront Rares
Handynotes - Warfront Rares





0.5.4





KuiNameplates
KuiNameplates





2.25.4





Masque
Masque





8.2.8





Masque: KringelUI
Masque: KringelUI





v1.0





集合石
MeetingStone





MeetingStone-80300.01





Method Dungeon Tools
Method Dungeon Tools





v3.0.4





Postal
Postal





v3.6.2





Quartz
Quartz





3.5.2





RaidAchievement
RaidAchievement











RaidAchievement
RaidAchievement

RaidAchievement









RaidAchievement_LegionRaids
RaidAchievement_LegionRaids

RaidAchievement









RangeDisplay
RangeDisplay





v4.9.3





RangeDisplay_Options
RangeDisplay_Options

RangeDisplay



v4.9.3





SharedMedia
SharedMedia





3.1.0 - r192





SimpleChat
SimpleChat





80000





Simulationcraft
Simulationcraft





v1.12.5





TinyInspect
TinyInspect





8.3.0
2020-02-21 04:21:02





TinyTooltip
TinyTooltip





8.3.0





HandyNotes: Mechagon by TomCat's Tours
HandyNotes: Mechagon by TomCat's Tours





01.04.06





HandyNotes: Nazjatar by TomCat's Tours
HandyNotes: Nazjatar by TomCat's Tours





01.04.06





WeakAuras 2
WeakAuras 2





2.17.2





World Quest Tracker
World Quest Tracker





v8.3.0.393





XIV_Databar







------------------&nbsp;Original&nbsp;------------------

**Comment by fang2hou** [comment]
你关掉暴雪框体增强之后，还能够随便移动框架么？

**Comment by fang2hou** [comment]
看到列表中有 ElvUI_BenikUI，应该是它也自带了暴雪框体增强，如果同时开启两个增强的话可能会冲突到。
建议测试关闭 ElvUI_BenikUI 中的移动窗体模块后再进行尝试，应该可以解决。
因为刚重写过这个模块，目前所有 ElvUI 增强里，我这移动窗体的功能应该是最稳定的。

**Comment by AudreyBlanney** [comment]
所有窗体都固定了 不能移动了------------------ Original ------------------

**Comment by fang2hou** [comment]
不加载 ElvUI_BenikUI v3 的情况下，开启移动模块死亡可以看到框体么？
刚刚在暴风之盾还跳死了几次观察，我这里一切正常，无法复现你的错误。

**Comment by AudreyBlanney** [comment]
刚测试完毕&nbsp;
1.我在完全禁用BenikUI的情况下 开启移动暴雪窗体 任然会出现该情况
2.我开启BeniKUI不改变任何配置选项的情况下,单独关闭移动暴雪窗体选项 不会出现该情况
3.BeniKUI我未找到有任何关于移动暴雪窗体的功能选项 也未装过其他此类插件&nbsp;
4.我朋友和我一直使用同样的插件 今日也出现该问题 每次出现无法弹窗的情况 必须/rl 且窗体会出现在固定右上角的位置
5.附我的插件列表







------------------&nbsp;Original&nbsp;------------------

**Comment by fang2hou** [comment]
好的，我接下来会继续排查。
可以先使用 BlizzMove 单体来代替这个模块。

**Comment by AudreyBlanney** [comment]
好的 辛苦了 白天还上班呢哈哈 晚上下班 我会继续测试 如果方便的话有什么交流群之类的 可以告知下吗 需要的话我可以提供我这边的配置文件或报错信息 视频啥的------------------ Original ------------------

**Comment by fang2hou** [comment]
这里就可以哦，对话框可以直接拖放文件，群什么暂时还是没有的。
