### ISSUE TITLE
修复自动任务物品/装备饰品动作条无法绑定按键问题

### ISSUE THREAD

**Issue by MouJiaoZi** [fang2hou/ElvUI_WindTools#94]
在根目录下新建Bindings.xml文件 内容为：

<Bindings>
	<Binding name="CLICK AutoSlotButton1:LeftButton" header="AutoSlotButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoSlotButton2:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoSlotButton3:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoSlotButton4:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoSlotButton5:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoSlotButton6:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoSlotButton7:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoSlotButton8:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoSlotButton9:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoSlotButton10:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoSlotButton11:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoSlotButton12:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoQuestButton1:LeftButton" header="AutoQuestButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoQuestButton2:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoQuestButton3:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoQuestButton4:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoQuestButton5:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoQuestButton6:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoQuestButton7:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoQuestButton8:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoQuestButton9:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoQuestButton10:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoQuestButton11:LeftButton" category="|cffC495DDWindTools|r"/>
	<Binding name="CLICK AutoQuestButton12:LeftButton" category="|cffC495DDWindTools|r"/>
</Bindings>

**Comment by fang2hou** [comment]
直接pr即可

**Comment by MouJiaoZi** [comment]
[Bindings.txt](https://github.com/fang2hou/ElvUI_WindTools/files/4567044/Bindings.txt)
