### ISSUE TITLE
对话框消失

### ISSUE THREAD

**Issue by WeijieH** [fang2hou/ElvUI_WindTools#96]
应该是更新1.6.4之后的问题，表现为有时游戏中的对话框（比如拉人后的确定对话框，邀请组队的确认对话框）消失不见，就好像是把框体移动了到了屏幕外面。这个问题的诡异之处在于我没有找到什么规律重复这个bug。有时一切正常，有时只能rl重载插件。
我觉得这个bug和windtools有关是因为今天打完大幻象无法看到退出对话框，rl也没用。我尝试挨个插件禁用后发现是WT的问题。
我在尝试重复触发这个bug，有什么发现我会再更新。
我用的插件是ElvUI + BenikUI + S&L + WT

**Comment by WeijieH** [comment]
录了个视频
https://youtu.be/J1wTEK35qnE

开启了移动窗体并记忆位置之后对话框就会消失。如果取消记忆位置则正常。关闭WT，开启SL的移动暴雪窗体会有同样的bug

**Comment by fang2hou** [comment]
只开启 ElvUI+ElvUI_WindTools 的情况下，先在设定中移动模块 Reset，再尝试一下看看会不会消失。

**Comment by WeijieH** [comment]
reset之后会正常一段时间，我现在为了正常游戏把记忆位置关闭了。

**Comment by fang2hou** [comment]
2.0 已经再次重写了一版, 前夕的时候可以再试试.
