### ISSUE TITLE
您好，houshuu大大，关于工具箱后续更新提一些建议，供参考

### ISSUE THREAD

**Issue by dylumian** [fang2hou/ElvUI_WindTools#98]
①任务通报自动交接：可以参考，爱不易、有爱或者Livv那样在任务追踪栏上添加交接，通报两个按钮勾选开启，非勾选关闭

②战斗状态那里希望添加类似爱不易这种战斗计时，毫秒级的计时（希望可以隐藏背景框/透明）然后可以自定义进入战斗的音效，比如：开火，提里奥·弗丁打阿尔萨斯的时候喊的attack , 李云龙的开炮,插件叫163UI_CombatTimer

③希望加入类似有爱的团员信息统计,具有统计团员,装等,腐蚀,宝石附魔,大秘境次数,团本次数,HM模式分别统计,插件叫163UI_TeamStats

直接提取这两个不生效,不知道他们用的哪些库,代码不太懂,希望您有时间看下酌情参考建议,打扰了,最后感谢您给我们带来了这么好的插件工具箱

**Comment by dylumian** [comment]
希望再加上 小地图点击者功能 感谢

**Comment by fang2hou** [comment]
会参考，但是暂时不是很有空进行开发

**Comment by dylumian** [comment]
> 会参考，但是暂时不是很有空进行开发

没事没事 这些东西不着急,您有空的时候再弄就好,现在就是多用点别的插件,等您开发好了,别的插件就可以删了
