### ISSUE TITLE
使用中发现了一个阴影美化的小问题

### ISSUE THREAD

**Issue by LiiVenNn** [fang2hou/ElvUI_WindTools#99]
宠物动作条的阴影美化会失效，改动了宠物动作条会正常，比如在elvui设置界面勾点了动作条背景出来后再取消背景，这时候会正常，重置后失效，其他动作条的阴影美化正常的在使用

**Comment by fang2hou** [comment]
2.0版本已经重写了整个阴影美化，但是由于很多模块还没有整理重写完成，所以请再耐心等待一下，预计前夕更新
